- lib/review/book/index.rb
- test/test_htmlbuilder.rb
付録の第1章を `@<hd>` で参照した場合だけ、appendix_format が使用されていなかったので、使用するようにしました。
> fix `@<hd>` use appendix_format when chapter 1.

- lib/review/pdfmaker.rb
- test/test_pdfmaker.rb
As a PDF file can be re-generated from source files, `review-pdfmaker` should
remove the file when the file exists rather than exiting with error.
`review-epubmaker` do the same way:
https://github.com/kmuto/review/blob/master/lib/review/epubmaker.rb#L44
This change simplify a continuous integration of books.
> review-pdfmaker remove a PDF file if already exists

- lib/review/i18n.rb
- test/test_i18n.rb
#331 の「決めうち名のファイルが増えていくのが嫌だなぁ」に対応するべくReVIEW::I18nクラスに手を入れてみました。
* ReVIEW::I18nにインスタンスメソッドを追加しました
* I18n.setup(nil)とすると、locale.ymlとかを読まないようにしました。これで、最初は`I18n.setup(nil)`にしておいて、localeファイル名が決まったあとで`I18n.setup(locale_filename)`とすると、locale.y(a)ml以外のファイル名も陽に指定できるようになります（例えばconfig.ymlで指定したファイル名とかにできるはず）。
> refactor I18n and add instance methods

- bin/review-compile
- lib/review/epubmaker.rb
- lib/review/i18n.rb
- lib/review/pdfmaker.rb
- test/test_htmlbuilder.rb
- test/test_i18n.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_pdfmaker.rb
- test/test_topbuilder.rb
* use `I18n.setup(language)` after `config["language"]` is loaded.
* remove `I18n.setup` in lib/review/i18n.rb.
* `I18n.i18n()` is removed because you should use I18n.setup in your program.
* If you need to update I18n catalog, use `I18n.update()`.
> fix I18n class to allow delayed initialization

- doc/sample.yml
- lib/review/pdfmaker.rb
#342 に対応するべく、`dvicommand`と`dvioptions`というパラメタを`config.yml`に設定できるようにしてみました。
REVIEW_SAFE_MODEで有効にしないようにもしてあります。
> review-pdfmaker: add parameters dvicommand and dvioptions in config.yml

- lib/review/i18n.rb
- test/test_i18n.rb
#379 に関連して、locale.ymlにi18n.ymlのように複数言語のL10Nを入れられるようにしました。
`locale: XXX` というところがあれば単一のロケール、そうでなくてハッシュの入れ子になっていれば複数のロケール、という様に判別するようになります。
> support multi languages in locale.yml

- lib/review/compiler.rb
- lib/review/htmlbuilder.rb
- lib/review/htmlutils.rb
- test/test_htmlbuilder.rb
まずはPygments対応の拡張として、`//list`や`//emlist`等に引数を追加してlangを指定できるようにしました。
↓こんな感じのソースが、Pygments有効時には、
```review
== listnum
//listnum[foo][listnumのサンプル][ruby]{
def foo(aa, bb=nil, cc=:foo, dd="hoge")
10.times do |i|
"aaa" + %q|aaa| + 'hoge' + <<EOB
aaaaa
bbb
EOB
end
return 1
end
//}
== emlist
//emlist[][ruby]{
def foo(aa, bb=nil, cc=:foo, dd="hoge")
10.times do |i|
"aaa" + %q|aaa| + 'hoge' + <<EOB
aaaaa
bbb
EOB
end
return 1
end
//}
```
↓こんな感じになります。
> add an argument lang to //list, //listnum, //emlist, //emlistnum, and //cmd and highlighting

- lib/review/compiler.rb
- lib/review/latexbuilder.rb
- lib/review/layout.tex.erb
- test/sample-book/src/sty/reviewmacro.sty
- test/test_latexbuilder.rb
LaTeX版の方で、listings packageをサポートしてみました。
こんな感じに書くと、
```review
== emlist
//listnum[hoge][Rubyコードのサンプル][ruby]{
##
#
class Foo
##
#
def foo(aa, bb = "test", cc = :test)
return bar(aa, bb) + 1 + 2
end
end
//}
== cmd
//cmd[コンソール出力のサンプル]{
$ sudo su
aaa
bbb
ccc
aaaaaaaaaaaaaaaaaaaaaaaaaa
bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb 
ccc
//}
```
こうなります。
> LATEXBuilder: support syntax highlighting with listings

- bin/review-init
review-initに`--force`をつけるとすでにディレクトリが存在していても(`*.re`以外の)初期ファイルを生成してくれるようにするものです。
空のディレクトリに`*.re`のファイルを作り始めてしまったときに、
```shell-session
$ review-init --force .
```
と実行すると、そのディレクトリがRe:VIEWのプロジェクト用ディレクトリになると便利かなあ、ということで作ってみました。いかがでしょうか。
> review-init: add option --force to generate even if directory is existed

- lib/review/htmlutils.rb
Pygmentsを使ったシンタックスハイライトを使う際、現状はconfig.ymlに、
```yml
pygments: true
```
と書いて使うことになっています。
が、他のシンタックスハイライトを使いたい場合や、builderごとに使い分けたい場合もあります。
そのため、以下の様な形で設定できればと思います。
```yml
highlight:
html: pygments
latex: listings
```
というわけで、上記のような形でHTML版のPygmentsを設定できるようにするための修正です(LaTeXのlistingsの方はすでに上記で対応済みです)。
* 属性名は`highlight`じゃなくて`highlighting`の方がよい？ でも長いのがちょっと。
* #229 にも最終的には対応したいです（`latex: pygments`の時に有効になる）。その際にはReVIEW::Highlighterクラスをちゃんと作った方が良さそう
* Pygmentsのスタイルにも対応させるには、
```yml
highlight:
html:
engine: pygments
style: bw
```
みたいにした方が良いかもしれないけど、ちょっと長いので今回の修正のようなショートカットは欲しくなるはず。
> use pygments with config.yml "highlight: {html: pygments}"

- lib/epubmaker/epubcommon.rb
#407 と同様の修正で、不要なファイル存在チェックをやめるものです(epubv2.rb, epubv2.rbにはこの種のコードはありませんでした)。
> refactor: use mkdir_p and remove file existance check

- lib/review/htmlbuilder.rb
- test/test_htmlbuilder.rb
- test/test_i18n.rb
#414 の別回答になります。
章番号に限らず、セクション番号すべてを以下のようにspanでマークアップします。
使用するclass名は、W3CのSpecなどでも使われている、secnoを使用しました。
```html
<h1 id="test"><a id="h1"></a><span class="secno">第1章　</span>this is test.</h1>
<h2 id="test"><a id="h1-1"></a><span class="secno">1.1　</span>this is test.</h2>
```
このようなCSSによって、h1 の装飾を図右のように変更できます。
```css
h1 .secno {
display: block;
font-size: .7em;
}
```
> HTMLBuilder: markup section number by span

- lib/review/compiler.rb
- lib/review/lineinput.rb
- test/test_htmlbuilder.rb
以下のようにdlistの途中に ``#@`` が挟まれていると、dlistが途中で終了してしまう（下記の例では2つのdlistができてしまう）。
```
: title
body
#@ comment
: title2
body2
```
途中に ``#@`` が挟まれていても、dlistを継続させる（1つのdlistにする）ように修正。
> Prevent dlist with comments from separating

- lib/review/layout.tex.erb
When using syntax highlighting in review-pdfmaker, a caption of list
does not have a prefix such as 'リスト' or 'List' etc.
Actual caption: 1.1 Sample Code
Expected caption: List 1.1 Sample Code
This is because the value of \lstlistingname is always empty.
> Fix missing listing name when using syntax highlighting

- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
見出し参照の際のクォートも I18n を使うようにしてみました。
章の参照時と変更したいという理由も思いつかなかったため chapter_quote を使用しています。
> use I18n in inline hd chap.

- test/test_pdfmaker.rb
#422 が駄目だったので1.8ではこのテストを飛ばしてみることにしてみます
> skip test_gettemplate_with_backmatter in 1.8.x (for travis error)

- lib/epubmaker/epubv3.rb
表紙画像の抽出に、ファイル名を取り出して完全一致のマッチにするようにしました。
（cover.jpgとしたらbackcover.jpgがマッチした事案がありまして… :scream: ）
> epubmaker: matching coverimage strictly

- doc/quickstart.ja.md
- doc/quickstart.md
フォーマットガイドへのリンクが古くなってしまっているようでしたので、修正いたしました。
> Fix link to format document

- lib/review/epubmaker.rb
- lib/review/htmltoc.rb
- test/test_htmltoc.rb
toc-html.txtを読み書きする部分が何をやっているのかよく分からなかった（テストもなかった）のでReVIEW::HTMLTocクラスに切り出してみました。
> refactor: extract HTMLToc class to read/write toc-html.txt

- lib/review/book/base.rb
- lib/review/htmlbuilder.rb
htmlversionでの分岐の際に、都度`to_i`とかをつけるのが大変になってきたので、`@book.htmlversion == 5`というようにすれば比較できるようにしたいのでした。
> refactor: add a method Book::Base#htmlversion

- lib/review/configure.rb
- test/test_configure.rb
`@config["foo"]` should be same as `@config["barmaker"]["foo"]` after `@config.maker = "barmaker"`
> attributes in Configure should be got without maker's name

- lib/epubmaker/epubcommon.rb
- lib/epubmaker/epubv2.rb
- lib/epubmaker/epubv3.rb
- lib/epubmaker/producer.rb
- lib/review/epubmaker.rb
- lib/review/htmlbuilder.rb
- lib/review/template.rb
- templates/html/layout-html5.html.erb
- templates/html/layout-xhtml1.html.erb
- templates/ncx/epubv2.ncx.erb
- templates/opf/epubv2.opf.erb
- templates/opf/epubv3.opf.erb
- templates/xml/container.xml.erb
- test/assets/test.xml.erb
- test/test_template.rb
ソースコードとHTMLを分離するべく、ERBテンプレートを使えるようにする修正です。
* <del>[ ] partial(include)サポート</del> ←特になくても困らなさそう
> use ERB template

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
> add "\n" before caption

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
> fix caption of //list, //listnum

- bin/review-init
- lib/review/htmlbuilder.rb
- lib/review/htmllayout.rb
- test/sample-book/src/config-epub2.yml
#456 の対応についてちょっと悩んだ結果、review-initに`--epub-version`オプションをつけて、EPUB2用とEPUB3用で別々のファイルを出せるようにしてみました。
オプションをつけない場合はEPUB3です。EPUB3版は拡張子を`.xhtml`にしています。
> review-init: fix to suport epub2 and epub3

- bin/review-vol
- lib/epubmaker/epubcommon.rb
- lib/epubmaker/epubv3.rb
- lib/epubmaker/producer.rb
- lib/review/book/base.rb
- lib/review/book/index.rb
- lib/review/book/part.rb
- lib/review/epubmaker.rb
- lib/review/i18n.rb
- lib/review/latexbuilder.rb
- lib/review/preprocessor.rb
どうもrubocopのデフォルトが変わったようで、警告がばんばん出るので`rubocop -a`で修正してみました。
> fix rubocop warnings

- lib/epubmaker/epubcommon.rb
- lib/epubmaker/producer.rb
colophon_orderを`epubmaker/epubcommon.rb`の中に埋め込むのではなく、`@producer.params[]`から読んでくるようにしました。これでconfig.ymlに書けるようになるはず…。
> EPUBMaker: reflected colophon_order

- bin/review
単一の`review`コマンド＋サブコマンドで使えると便利、と誰かが言ってたような記憶があるので、作ってみました。
```shell
$ review epubmaker config.yml
$ review compile --target=html foo.re
```
> add a new command "review", wrapper command for review-*

- .travis.yml
- doc/sample.css
- lib/review/htmlbuilder.rb
- test/sample-book/src/style.css
- test/test_htmlbuilder.rb
> HTMLBuilder: use class instead of width for //image[scale=XXX]

- bin/review-index
- lib/review/book/chapter.rb
- lib/review/book/index.rb
- lib/review/book/part.rb
- lib/review/extentions/string.rb
- lib/review/preprocessor.rb
- lib/review/tocparser.rb
- lib/review/tocprinter.rb
目次周りを何とかするべく、TOCParserを大工事しています。
* TOCRoot を廃止して、既存のReVIEW::Book::* のクラスに後からincludeする形の修正をなくし、TOCParserで定義しているクラス郡とは完全に別扱いするようになっています。
* 現状はTOCParserをrequireするとReVIEW::Book::*にeach_sectionとかを追加して、上手い感じに扱えるようなハックが入っているのですが、ちょっとハック過ぎるというか、同じ物として扱おうとするのは筋が悪そうです。少なくともTOCParser::ChapterとReVIEW::Book::Chapterの両方がある時点でやばそう
* TOCPrinter側も、TEXT/HTML/IDGで別々のロジックになっていたところを統一しています。
* というかHTMLがまともに動いてなかった。たぶん`--html`オプションは誰も使ってない。
* `-a`で文書全体、`-p`で部単位、`-c`で章単位に出力するところを、print_book, print_part, print_chapterのメソッドに切り分けて、各メソッドの実装もこれらのメソッドを使うようにしています。
* `ruby -w`をつけて警告が出るところを一部修正しています。
今のところTOCParserはreview-indexコマンドでしか使っていないはずですが、本体でも使うようにする予定です。
> review-index: refine TOCParser and TOCPrinter

- lib/review/book/chapter.rb
- lib/review/book/compilable.rb
- lib/review/book/part.rb
- lib/review/tocparser.rb
- test/test_book_chapter.rb
*.re ファイルについて、それに対応するオブジェクトの初期化時に中身を読み込むようにして、それ以降読み込み直さないようにするものです。
また、どうせ読み込んでしまうので、Chapter#open（*.reの中身をIOオブジェクトとして返す）はdeprecatedにして、Chapter#content(*.reの中身をStringオブジェクトとして返す)を使うようにしたいです（IOが必要な場合はStringIOでラップする）。
* Chapter.new and Part.new: read file and set @content immediately
* Compilable#title: use @content instead of self.open
* Compilable#size: use @content instead of load file.
* Compilable#open: do not use File.open
* TOCParser.parse: use Chapter#content instead of Chapter#open
> ReVIEW::Chapter and ReVIEW::Part: do not use lazy loading

- lib/review/configure.rb
- lib/review/converter.rb
- lib/review/epubmaker.rb
- lib/review/pdfmaker.rb
- test/test_pdfmaker.rb
* `ReVIEW::Configure`: add some default values
* `ReVIEW::EPUBMaker`, `ReVIEW::PDFMaker`: basedir should be same as yamlfile
* `ReVIEW::EPUBMaker`: stop building when error occured in compile *.re files.
review-epubmakerとreview-pdfmakerで、内部的にreview-compileを呼ぶのを止めて、compile用のReVIEW::Converterクラスを使うようにするものです。
review-epubmakerは5倍くらいは速くなりそうです(review-pdfmakerはLaTeX側処理が圧倒的に時間がかかっているのであんまり変わらない)。
ただし、review-compileは別コマンドを呼ぶことによってBookオブジェクト等が共有されていなかったのですが、ReVIEW::Converterでは積極的に共有する形にしているので、思わぬ結果になる可能性があります。
> use ReVIEW::Converter instead of system("review-compile ...")

- bin/review-preproc
review-ext.rb同様に、グローバルには入れたくないパッチをサポートするため、review-preproc-ext.rbでの上書きを提供します。
> review-preprocのモンキーパッチ許容

- lib/review/book/base.rb
- lib/review/builder.rb
- lib/review/pdfmaker.rb
Hi.
On Windows, Re:VIEW fails delete temporary directory because of not-explicitly-closed-file object.
I have fixed them.
> fix unclosed file

- doc/sample.yml
- lib/epubmaker/epubv3.rb
- test/test_epub3maker.rb
changelogをミスった気もしますが、とりあえず電書協ガイドラインのほか、今後のEPUB3.1でもrequiredになりそうなので、読み属性の適用範囲を広げました。
書式についてもsample.ymlに書いています。
> booktitleなどにも読みの指定を許可。sample.ymlにドキュメント化

- lib/review/i18n.rb
- test/test_i18n.rb
%pAW、%paW、%pRW、%pJ、%pdW、%pDW をフォーマットに加えるものです。
> 数字のフォーマットを追加

- doc/sample.yml
opf_prefix, opf_metaのとりあえずのコメントをsample.ymlに追加。
本当はepubmaker:の下にしたい（#515 絡み）が、とりあえずこれでマージ。
> note about opf_prefix and opf_meta

- lib/epubmaker/epubcommon.rb
- lib/epubmaker/epubv2.rb
- lib/epubmaker/epubv3.rb
- lib/epubmaker/producer.rb
- lib/review/epubmaker.rb
- test/test_epubmaker.rb
EPUBMakerまわりの修正です。
名前の区切りに”,"を直接文字列で指定していた箇所をi18n.ymlのnamed_splitterの文字列に。
i18n文字列をそのままテンプレートに入れていた箇所をCGI.escapeHTMLするように。
そのほかif→unless、instance_of→kind_of、マージ時のdeep_merge利用です。
- use i18n'd names_splitter string for splitting names (such as
authors or contributors) in titlepage and colophon.
- escape HTML tag of toctitle in toc file.
- escape HTML tag of colophontitle and rights string in colophon file.
- escape HTML tag of title in cover and titlepage.
- use kind_of instead of instance_of.
- use 'unless X' instead of 'if X.nil?' of one liner.
- use deep_merge to merge epubmaker's default preset.
- escape HTML tag of i18n'd part name.
- add tests for HTML escaping.
> refactoring, escaping and i18ning.

- lib/epubmaker/epubcommon.rb
- lib/epubmaker/epubv2.rb
- lib/epubmaker/producer.rb
- lib/review/configure.rb
- lib/review/epubmaker.rb
- lib/review/layout.tex.erb
- lib/review/pdfmaker.rb
#532 の名前付きパラメータへの対策です。
Configureクラスにname, namesというメソッドを加え、name:属性の値を文字列化して取得できるようにしています（本当にnameという属性名で固定になっているのかよくわからないところですが…）。ハッシュになっていなければそのまま中身を返します。namesは配列版です。
なお、PDFmakerでは値代入時にエスケープをしていないようなので、このパッチマージのあとにエスケープのロジックを入れたいところです。
> 名前付きパラメータへのEPUBmaker/PDFmakerの対応

- lib/epubmaker/producer.rb
- lib/review/configure.rb
- lib/review/epubmaker.rb
- lib/review/pdfmaker.rb
- test/test_configure.rb
* enable to use `@config["foo"]` instead of `@config["epubmaker"]["foo"]` when using epubmaker
cf. #515
> allow to use shortcut key of config

- .rubocop.yml
- lib/review/book/index.rb
- lib/review/compiler.rb
- lib/review/htmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/layout.tex.erb
- test/assets/test_template.tex
- test/test_htmlbuilder.rb
- test/test_latexbuilder.rb
画像で作った表を埋め込むコマンドです。
相当前に作ったpatchなので要検証。
> add command //imgtable

- lib/review/pdfmaker.rb
- test/test_pdfmaker.rb
cf. #549 
<tmpname>/book-pdf にするのもできるけれども、とりあえず <bookname>-pdf-<tmpname> で実装してみました。
begin-ensureで囲んで例外にかかわらず削除するようにしています。
取り込むにはpdfmaker_cmdのtestの削除が必要ですね。
> tmpdirをTeXビルドパスに利用する

- lib/review/configure.rb
- lib/review/idgxmlbuilder.rb
- test/test_idgxmlbuilder.rb
これまで表セル幅の計算にJISのpt/mm換算の1pt=0.3514mmを使ってしまっていましたが、InDesign上で表すにはDTPの1pt=0.3528mmを使うべきです（さもないと計算誤差が出ます）。
自身の過去遺産の負債でこれまで目をつむってきましたが、いいかげん支払うことにします。
ただ影響が大きい（既存の組んでしまった原稿を直すことは非現実的）のでフラグpt_to_mm_unitで元の単位数値(float)指定もできるようにしてあります。
> fix wrong calcuration between pt and mm for table cell width on IDGXML.

- lib/epubmaker/epubcommon.rb
- test/test_epub3maker.rb
奥付の発行日をテストするため `EPUBCommon#colophon_history` を独立したメソッドに切り出してみました。
> refactor: extract EPUBCommon#colophon_history method

- lib/review/book/page_metric.rb
- lib/review/configure.rb
- lib/review/htmlbuilder.rb
- lib/review/i18n.rb
- test/test_i18n.rb
* layout.erb -> layout.html.erb
* locale.yaml -> locale.yml
* PageMetric.a5 -> PageMetric::A5
cf. #546
> remove backward compatibility

- lib/review/builder.rb
- lib/review/compiler.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/topbuilder.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_topbuilder.rb
cf #396 
memo, tip, info, important, caution, notice, warning(新設) をcommonなブロックにします。
いずれもキャプションをオプションでとり、空行区切りの複数の段落を格納します。
LaTeXにおいては、今のところcaptionblockにしか実装がないので、すべてreviewminicolumnになります。
> move major block notations to common.

- lib/review/pdfmaker.rb
- test/test_pdfmaker.rb
PDFMakerでもconfig.ymlの`pubhistory`の代わりに`history`をサポートします。
> config: support history instead of pubhistory

- lib/review/book/base.rb
- lib/review/book/chapter.rb
- lib/review/book/part.rb
- lib/review/preprocessor.rb
- lib/review/tocparser.rb
Windows向けに処理。
ちょっと怖いのでドキュメントでテストが必要。
> use read BOM|utf-8 flag for opening files, instead of string replacing

- lib/review/pdfmaker.rb
- templates/latex/layout.tex.erb
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
* use instance variables instead of `values`
* `@config` for Configure
* `@documentclass` and `@documentclassoption` for \documentclass
* `@coverimageoption` for \includegraphics of cover
* `@input_files` to including CHAPS, PREDEF, ...
* remove newline and/or spaces (cosmetic changes)
* use ReVIEW::Template instead of ERB directly
> Breaking Change: fix LaTeX templates

- doc/config.yml.sample
`urnid`と`isbn `が落ちていたので復活させました。
> config.yml.sample: add isbn and urnid

- Rakefile
`rake rubocop`でrubocopが実行できるようになります（インストールされていない場合は警告だけ出して無視されます）。
`rake`だとtestとrubocopの両方が実行されるようになります。
> use rubocop with rake

- lib/review/configure.rb
- test/test_configure.rb
> Allow review_version to be nil, which means that I don't care about the version

- lib/epubmaker/producer.rb
`htmlext`の値の設定によってcoverファイルの拡張子がxhtmlじゃなくてhtmlになってしまうことがあるのを修正
> EPUBMaker::Producer: fix timing of making @params["cover"]

- .rubocop.yml
- lib/epubmaker/producer.rb
add `Metrics/MethodLength` rule and fix long Array in EPUBMaker::Producer.
> rubocop: add more rules

- lib/review/topbuilder.rb
- test/test_topbuilder.rb
2.0.0 で出力結果が変わっていたので。
expected
```
◆→DTP連絡:コメントだよ！←◆
```
actual
```
@<comment>{コメントだよ！}
```
> add inline_comment to TOPBuilder

- doc/config.yml.sample-simple
`config.yml.sample` is a bit long to read.
We need simplified config.yml sample file for starter, I guess.
> config.yml: add simplified sample

- lib/review/i18n.rb
- test/test_i18n.rb
`format_number_header`で`%pJ`を正しく使えないようなので修正しました。
`percents.each_with_index`の中で、`args`をインデックスアクセスに使っているのに`args.delete`で破壊的に変更しているので、`%pXX`が複数あると正常に動かなかったようです。`args`の変更はループの外で行うようにしました。
> I18n.t: fix format_number_header

- test/test_topbuilder.rb
> TOPBuilder: add a test for `@<comment>{}` in draft mode

- lib/review/idgxmlbuilder.rb
IDGXMLBuilderで//emlist[][highlight-lang]としたときに、「空文字の」captionができてしまっていました。HTMLBuilderと同様に、unless nil?をやめてif present?で有効な文字列があることを調査するようにします。
> check caption by using present? instead of nil? on IDGXMLBuilder.

- lib/review/idgxmlbuilder.rb
- test/test_idgxmlbuilder.rb
IDGXMLにおいてコラムの埋め込み目次情報を入れていなかったので、ほかのheadlineと同じくXMLインストラクションを入れるようにしました。
> add instruction to column headline for toc on IDGXMLBuilder.

- lib/epubmaker/producer.rb
- lib/review/configure.rb
「ReVIEW::Configure側で上書き」するため、urnidがUUIDではなくnilになってしまっていました。
config.ymlで明示的な設定をしていない場合に壊れたEPUBを作ってしまうことになります。
Configure側にUUID作成の設定を移動しました（設定が別々にあるのがそもそもいかん、ちゅー話ですね）。
> fix missing default dc:identifier value.

- lib/review/pdfmaker.rb
- templates/latex/layout.tex.erb
- test/assets/test_template.tex
- test/test_pdfmaker.rb
`locale.yml`で`chapter`や`image`を再設定してもLATEXBuilderに反映されなかったのを修正します。
* `locale.yml`で設定した文字列を、`\reviewfigurename`などのコントロールシーケンスで参照できるようにします
* chapter, part, appendixは、`%XXX`で２分割した前後をそれぞれ`\reviewprepartname`,`\reviewpostpartname`等で参照できるようにします。
* jsbook、utbookの場合は`\prepartname`、`\figurename`等を`\renewcommand`するので何もしなくても反映されます。`\prepartname`を使っていないスタイルファイルを使っている場合は、自力で`\reviewprepartname`等を使って再設定してください。
> LATEXBuilder: fix to use keywords in locale.yml

- .rubocop.yml
- .travis.yml
- ChangeLog
- README.md
- appveyor.yml
- doc/config.yml.sample-simple
- doc/preproc.ja.md
- doc/preproc.md
- lib/epubmaker/producer.rb
- lib/review/configure.rb
- lib/review/i18n.rb
- lib/review/idgxmlbuilder.rb
- lib/review/pdfmaker.rb
- lib/review/topbuilder.rb
- templates/latex/layout.tex.erb
- test/assets/test_template.tex
- test/sample-book/src/Rakefile
- test/test_i18n.rb
- test/test_idgxmlbuilder.rb
- test/test_location.rb
- test/test_pdfmaker.rb
- test/test_topbuilder.rb
* review-pdfmaker は、（汎用なクラスファイルを使う前提で）(u)platex + dvipdfmx を実行するので、documentclassオプションに global で `dvipdfmx` を入れておいてよいと思います。
* T1, TS1 エンコーディングを有効にしました。
* colorパッケージからxcolorパッケージに変更しました。これにより、colortbl (upto array) が読み込まれ、tabular の出力を改善します。
* hyperref パッケージ周りの設定を整理しました。
* その他、「fixes to LaTeX2e」や「Latin Modern」などをコメントアウトで追加しました。これらは、標準で有効にしておいてもよいと思いますよ！
> Enhanced implementation of `layout.tex.erb`

- .rubocop_todo.yml
- lib/review/book/compilable.rb
- lib/review/book/index.rb
- lib/review/configure.rb
- lib/review/htmlbuilder.rb
- lib/review/markdownbuilder.rb
- lib/review/preprocessor.rb
- test/test_index.rb
* Style/PreferredHashMethods: Use Hash#key? instead of Hash#has_key?
* Style/SpaceInsidePercentLiteralDelimiters: Do not use spaces inside percent literal delimiters
> fix: surpress rubocop 0.41.0

- .rubocop.yml
- lib/review/book/index.rb
* add config option
* remove ReVIEW::Book::FormatRef class; this class seems to be never called
> supress rubocop warning

- lib/review/pdfmaker.rb
File.dirname(yamlfile)だけだと「.」になってしまい、フックの場所が見つけられなくなる。
absolute_pathを使うように変更。
> hookに相対パスで指定したときにうまく動かない問題の解決

- lib/review/htmlbuilder.rb
- test/test_htmlbuilder.rb
https://highlightjs.org/ で簡単にコードハイライトしたかった。
ついでに、listに第三引数書くのはめんどくさかった。
そんな思いをpull requestにしました。
以下のようなコード片を入れるとsyntax highlightできるようになります。
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.6.0/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.6.0/highlight.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.6.0/languages/typescript.min.js"></script>
<script>document.querySelectorAll("pre.list").forEach(function(b) { hljs.highlightBlock(b); });</script>
```
今、`%Q[<pre class="list">]` なのは何か理由があるのでしょうか？(`<code>`にしたい
> HTMLBuilderのlist記法の出力にlanguage-*クラスを追加する

- lib/review/markdownbuilder.rb
- lib/review/md2inaobuilder.rb
- test/test_markdownbuilder.rb
- test/test_md2inaobuilder.rb
https://github.com/naoya/md2inao 用Markdown出力を行うビルダです。
技評さんのWEB+DB用原稿書きに使っていて、2回分くらい回してみて @murashitas さんからフォーマットについて注文が来なかったので多分よかろ！と思ってPRにしました。
> md2inaobuilderの追加とrubyのサポート

- lib/review/pdfmaker.rb
#672 対応。
@basedir で絶対パスとしてしまうと、imageの値に影響が出てextractbbが（現在ディレクトリ外への実行となり）動かなくなってしまうため。
> フルパスを取るのに@basehookdirを別途用意

- bin/review-validate
- lib/lineinput.rb
- start_with?を使用
- #前の2つ以上の空スペースを削除
> AppVeyorさんの警告に対処

- lib/review/makerhelper.rb
- lib/review/pdfmaker.rb
.ai, .eps, .tifのファイルについてコピーなどがうまくできていなかったのを修正。
フックでbasehookdir（絶対パス）を渡すように修正。
> support AI, EPS, and TIFF on pdfmaker correctly

- .rubocop.yml
> suppress warnings of rubocop

- lib/review/latexbuilder.rb
- templates/latex/layout.tex.erb
- test/assets/test_template.tex
- test/test_latexbuilder.rb
add new macro `reviewsource` and `reviewsourcecaption` for `//source` command.
cf. #651
> LATEXBuilder: fix //source

- lib/review/htmlbuilder.rb
- test/test_htmlbuilder.rb
> img, table, listの参照を<span>で囲む

- lib/epubmaker/epubcommon.rb
- lib/review/pdfmaker.rb
- test/test_epubmaker.rb
- test/test_pdfmaker.rb
`@config["history"]` allowed `YYYY-MM-DD` and `YYYY-MM-DD some_comments`.
With this fix, when history does not match this pattern, use the value as is.
> allow free format in history of config.yml

- lib/review/htmlbuilder.rb
- test/test_htmlbuilder.rb
> HTMLBuilder: chapterlinkがtrueのときに@<list>のハイパーリンクを有効にする

- lib/review/topbuilder.rb
It seems that TOPBuilder never use this method (Furthermore, `error_messages()` and  `warning_messages()` are not defined in TOPBuilder... )
> TOPBuilder: remove an unused method: messages()

- test/test_makerhelper.rb
ref #712
とりあえずconvertの有無で実行可否を考えるようにした。
pure RubyのためにはRMagick化したほうがいいけど、EPSを触るとなるとRMagickだけでなくGhostscriptも必要になるので厄介め。
> convertコマンドがなければtest_copy_images_to_dir_convertを飛ばす

- lib/review/builder.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/topbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
```
//tsize[2,3,5]
//tsize[|idgxml|2,3,5]
//tsize[|latex,idgxml|2,3,5]
//tsize[|latex||p{5mm}|cr|]
```
こんな感じで。既存成果物には影響ないはず。
> //tsizeでビルダ指定できるようにする

- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/markdownbuilder.rb
- lib/review/md2inaobuilder.rb
- lib/review/topbuilder.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_markdownbuilder.rb
- test/test_md2inaobuilder.rb
- test/test_topbuilder.rb
cf #360 
どのビルダでも、
- --draft有効時にcommentタグの内容を表現する。
- 無効時に無視する。
> ドラフトコメントのサポート

- lib/review/htmlbuilder.rb
- test/test_htmlbuilder.rb
> HTML: listのidをdivの属性に入れていなかった

- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/markdownbuilder.rb
> remove ul_item() of html, idgxml, and markdown.

- lib/review/book/image_finder.rb
- test/test_image_finder.rb
imagesディレクトリの下のディレクトリとしてシンボリックリンクを使えるようにするためのパッチです。
image_finder.rbの`Dir.glob(File.join(@basedir, "**/*.*"))`は、ファイルのシンボリックリンクは辿ってくれるようですが、ディレクトリについては辿ってくれないようです。
以下のURLによると、`Dir.glob("**{,/*/**}/*.*")`で解決しそうだったので、コードを変更しテストを追加しました。
http://stackoverflow.com/questions/357754/can-i-traverse-symlinked-directories-in-ruby-with-a-glob
> image_finder.rb: support symlinked directory

- lib/epubmaker/epubcommon.rb
- lib/review/epubmaker.rb
EPUBmakerも奥付でしか使ってなかったので、画像なし版の表紙と大扉にも設定。
（そういえば大扉や奥付はデフォルトのstyle.cssだとCSSスタイルがちゃんとついてないですね…）
> support subtitle on EPUBmaker

- doc/format.md
- lib/review/builder.rb
- lib/review/compiler.rb
- test/test_htmlbuilder.rb
cf. #730 
試しに`//embed{...//}`と`@<embed>{...}`を実装しました。
`//embed{...//}`はあらゆるエスケープを無視してそのまま埋め込みます。ついでに`#@...`形式のコメントも無視せずそのまま埋め込みます。
`//}`の行はどうやっても埋め込めません（エスケープルールがないので）が、それは仕様ということにしておいた方が良さそう。先頭を空白にした` //}`なら埋め込めます。
`@<embed>{...}`はそのインライン版ですが、こちらはエスケープルールがあります。
* `}`は`\}`と書く
* `\`は`\\`と書く
* それ以外の文字はそのまま書く
というルールで任意の文字を埋め込めるはずです。
> add `//embed{...//}` and `@<embed>{...}`

- lib/review/book/compilable.rb
- lib/review/book/index.rb
- lib/review/epubmaker.rb
- lib/review/pdfmaker.rb
- lib/review/webmaker.rb
- templates/latex/layout.tex.erb
#453 の修正を試みます。
手元のテストではimagedirの変更あり/なし、debugのあり/なし、EPUBMaker・PDFMaker・WebMakerで動作を確認。
なお、
- imagedirは作業フォルダ直下のフォルダであり、空白を含まない普通のファイル名規則に則っているものと前提する(これは今のimagesと同じなのでさほど問題ないはず)。
- EPUB、Web、PDF等の変換の際には、これまでのように「images」という名前に変更されることなく、imagedirで指定のフォルダ名がそのまま使われる。
テストケースを書きづらい…
> fix imagedir handling

- bin/review-init
Windows環境でreview-initを実行する際，config.yml.sampleの読み込みでエンコーディングエラーにならないよう，読み込みファイルのエンコーディングを'utf-8'として指定する。
> Specify source file encoding on generating config.

- README.md
- bin/review-init
- templates/latex/layout.tex.erb
- test/assets/test_template.tex
- test/sample-book/src/vendor/jumoline/lppl.txt
* サンプルのjumoline.styをreview-initでコピーするように
* lppl.txtを設置。README.mdにも追記
* templates/layout.tex.erbでjumoline.styを有効化
layout.tex.erbのカスタマイズをしていない既存の環境だと、この変更によりjumoline.styが見つからないのでエラーになるという痛い副作用があります。
usepackageの代わりに「なければスキップ」という命令はないんだっけ…
> jumolineの有効化

- lib/review/topbuilder.rb
- test/test_topbuilder.rb
- `@<list>`で他章に飛べなかった（これはバグ）
- `@<bib>`と`//bibpaper`を実装
- [notoc], [nodisp]を実装
> topbuilderが追従していなかった機能を追加

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
get_chapでフォーマット済みのものを使うようにする。
テストコードを書いたらマージしたいと思います。
> LaTeXにおいてAPPENDIX内でlist, table, imageを使ったときに1-1のようになることの修正

- doc/config.yml.sample
#765
backcover, titlefile, originaltitlefile, creditfile, profile, advfileはPDFMakerだとTeX断片ソースが必要。
EPUBMakerだとヘッダ/フッタも含んだHTMLファイルなのでちょっと整合性がいまいちではある。
> backcoverが画像ではなくファイル断片をとるのでYAMLコメントを修正

- debian/control
- doc/quickstart.ja.md
- doc/quickstart.md
https://help.github.com/articles/which-remote-url-should-i-use/ で https: が推奨になっていて、今は選択肢に git: が出てこないということもあって、 https: を使うのが良いのではないでしょうか。
それから、元が git: になっていたということは read only を想定していると思うので、ssh にする必要もないのかなと思いました。
> Use https: instead of git:

- lib/review/builder.rb
- lib/review/sec_counter.rb
部のreファイル内で節見出しおよびimg, list, tableを使ったときに、locale.ymlでローマ数字などを設定していても「1.1」のようになってしまう。
部かどうかを判断し、返却結果を変えるようにした。
> 部ファイル内の見出しや図表リストの接頭字に部番号を使用

- .rubocop.yml
`Style/MultipleComparison` and `Style/YodaCondition` are not useful :-(
> suppress rubocop

- lib/review/book/index.rb
- test/test_htmlbuilder.rb
`//imgtable` should not be counted as ImageIndex, but can be refered as images.
> fix counting of //imgtable

- lib/review/latexbuilder.rb
.aiは（あくまでPDF互換データとして）扱えるけど.psdはダメなので、ビルダで上書き定義する。
> LaTeXで扱える画像形式を調整

- lib/review/builder.rb
- lib/review/compiler.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/markdownbuilder.rb
- lib/review/rstbuilder.rb
- lib/review/topbuilder.rb
- templates/latex/layout.tex.erb
- test/assets/test_template.tex
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_rstbuilder.rb
- test/test_topbuilder.rb
#255 の対応。
書式としてはidなしのtableで、
```
//emtable[caption]{
//emtable{
```
latexではreviewtablecaption*にしたかったので、caption.styとsuffix.styを取り込んでいます。
Builder#tableを各個ビルダで結局似たりよったりのオーバライドが必要になっているのはイケてない気がするので、取り込んだあとにその対処に乗り出したいところです。
> //emtableの導入

- lib/review/compiler.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_topbuilder.rb
#794 の修正。
ddの処理で通常段落か「:」かしか判断していなかったので、*や1.がddに含まれてしまっていた。
> dlistの終了条件に箇条書きも含める

- README.md
当方普段Texを使わないのですがMarkdownを手軽にPDF化出来ると本ツールを知人から勧められました。
インストールし`Quick Start`の通り`rake pdf`コマンドを実行しましたが、以下エラーにより停止してしまいました。
```
ryota.murakami@localhost ~/r/hello>rake pdf
review-pdfmaker config.yml
compiling hello.tex
/Users/ryota.murakami/repository/hello/gems/ruby/2.4.0/gems/review-2.3.0/lib/review/pdfmaker.rb:42:in `system_or_raise': failed to run command: ebb cover.jpg (RuntimeError)
from /Users/ryota.murakami/repository/hello/gems/ruby/2.4.0/gems/review-2.3.0/lib/review/pdfmaker.rb:275:in `block in copy_images'
from /Users/ryota.murakami/repository/hello/gems/ruby/2.4.0/gems/review-2.3.0/lib/review/pdfmaker.rb:268:in `chdir'
from /Users/ryota.murakami/repository/hello/gems/ruby/2.4.0/gems/review-2.3.0/lib/review/pdfmaker.rb:268:in `copy_images'
from …
```
> [README] Quick Startの`rake pdf`コマンドにTexが必要な旨を明記

- lib/review/topbuilder.rb
- test/test_topbuilder.rb
topbuilderで
* imageにmetricパラメータを渡してもまったく無視されて何も残らない
* indepimageにmetricパラメータを渡さないとnil.joinが発生してエラー
となるのを修正する。
とはいえtopbuilder自体がパラメータで何かできるわけではないので、結果文字列にパラメータ文字列を埋め込むだけの挙動とした。
```
◆→画像 images/cover.jpg a=1,b=1←◆
```
> topbuilderでのmetricパラメータが無視かエラーになるのを修正

- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/topbuilder.rb
cf #803 
image, icon, indepimageにおいて、画像が見つからないときは無言ではなく必ずwarnで警告するようにした。
また、メッセージがno such image: ID だと挙動として変なので、元のに合わせて image not bound: ID で揃えた。
> 画像が見つからないときは常に警告する

- README.md
`README.md` の quickstart へのリンクが間違っていたようなので修正しました。
> README.md の quickstart へのリンクを修正

- lib/review/configure.rb
ref #824 
epubmakerのほうでは付けてたけど、ちゃんと効いてなかった模様。またTeXのほうにも必要だったので、共通のconfigureのほうの初期値でdate=今日とした。
> dateが空なら今日の日付を設定

- lib/review/webmaker.rb
- templates/web/html/layout-html5.html.erb
```
booktitle: {name: "Re:VIEW文法変換リファレンス", file-as: "リビューブンポウヘンカンリファレンス"}
```
みたいなものをwebmakerにかけるとエラーやハッシュ文字列がHTMLに入ってしまうことの修正です。
> hash型のbooktitle等パラメータへの対応

- .rubocop.yml
- review.gemspec
- test/test_makerhelper.rb
新規2つはどちらも都合が悪い。
- warnはcompileは置き換えをしているので対処しづらい
- commentはたくさんあり、対処する必然性もない
> rubocop 0.51対応

- templates/latex/layout.tex.erb
- test/assets/test_template.tex
#843 の対処として、lmodernを有効にします。
見た目は実質変わらないはずです。
> lmodernの有効化

- lib/review/latexbuilder.rb
latexbuilderで//sourceのキャプション省略を許します。
（ほかのビルダと同じにする）
> LaTeXBuilderで//sourceのキャプション省略を許可

- lib/epubmaker/content.rb
- lib/epubmaker/epubv3.rb
Kindle版などでtoc: trueとしたときに配置される静的目次を、書籍の冒頭ではなく、一般的な書籍同様に前付の最後に置くようにします。
これ以上変えたいときは自己責任でフックでopfファイルを調整いただくということで。
> EPUB3でspine内の静的目次の位置をPREDEFの後/CHAPSの前にする

- lib/review/book/part.rb
#852 
ファイルが見つからないときは「そのまま」の文字列を使って部を構成するというロジックになっているが、先にFile.basenameで代入していたことで「I/O」の「I/」が消えるといった問題が生じていた。
（ほかにも.reという文字列で終わっていたら同様に消えてしまうはず）
ファイルが見つかったときだけbasename代入をするように修正。
> catalogでリテラル定義での部名はいじらずにそのままにする

- lib/review/builder.rb
- lib/review/compiler.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/rstbuilder.rb
- lib/review/topbuilder.rb
- test/test_latexbuilder.rb
#836 の対応
主にLATEXBuilder向け。
参照用のIDは見出しの{}または//labelで指定する。
（これに伴い、見出しの{}の内容も\labelで書き出すようにしている）
IDの危険文字の判断はしないものとする（エスケープしようにもうまくいかなかったので、ユーザーの責任での対処にしたい）。
HTMLでは利用できないことを警告する。対応しようとすると他ファイルの参照のためにimageなどと同様に一度パースが必要になり、大掛かりになってしまう。
> @<pageref>の導入

- templates/latex/layout.tex.erb
#846 
TeXのtocdepth値はtoclevelよりも-1する必要があった。
> tocdepth値をtoclevel - 1にする

- lib/review/builder.rb
- lib/review/compiler.rb
#860 の解決
builder.rb#errorが例外チェーンで2回呼び出されることがある模様。locationをすでに付けているようだったら付けないようにする。
> error行の多重表示を防ぐ

- lib/review/book/index.rb
- lib/review/compiler.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
#121 の修正。
hdタグを使ったときにHeadlineIndexで再パースが行われるが、普通の見出し確認に比べて不十分な実装になっており、特定の状況下において異常なエラーが発生していた。
- 空見出しがあるときにnil.warnが生じていた。空見出しの場合はHeadlineIndexで飛ばすとともに、compiler#compile_headlineでheadline is empty.の警告を出すようにした。
- ブロック内はHeadlineIndexで解析しないようにした。
> 空見出しやブロック内見出し誤認によるHeadlineIndexの奇妙なエラー挙動の修正

- lib/review/compiler.rb
- test/test_htmlbuilder.rb
- test/test_latexbuilder.rb
#876 の対応。
latexを含め各ビルダのエスケーピングにも安全な文字として、`!!!atmark!!!` に一度エスケープしてから戻す。
> フェンス記法内で@をエスケープ

- lib/review/textutils.rb
- test/test_textutils.rb
- test/test_topbuilder.rb
> 段落ブロックの末尾空行を取ってから段落生成

- lib/review/book/index.rb
- test/test_index.rb
ドキュメントには `column` と同レベル以上の見出しか `[/column]` が来たら終了するとありますが、
動作していないようなので修正しました。
特に `[/column]` は 2.4.0 から動作しなくなったように思います。
> column の終了が意図しない動作だったのを修正

- lib/review/book/index.rb
#896の修正
`@logger`を定義し忘れていたので、警告を出そうとしたときにnil.warnになってしまう。
> HeaderIndexで@loggerの定義漏れ

- lib/review/book/index.rb
#891の修正。
単純なロジックミスで、`@index.fetch(id)`までrescueで包んでいたのがまずかっただけ。
実行されて失敗したときには上位の例外捕捉でkey not foundと示されるようになる。
> chap, chaprefでIDが見つからないときにはundefined methodではなくID不明の旨のエラーを出す

- review.gemspec
rubocopの `Lint/RescueWithoutErrorClass` -> `Style/RescueStandardError` への対応です
> define rubocop version to avoid version-sensitive errors

- lib/review/builder.rb
- lib/review/htmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/markdownbuilder.rb
- lib/review/md2inaobuilder.rb
- lib/review/rstbuilder.rb
- lib/review/topbuilder.rb
revert some changes of b2f2aa5a in `lib/review/*builder.rb`
rubocop対応用に突っ込んだ（そして結局不要になった）修正が`*builder.rb`に衝突しまくって辛いので、一部元の形に戻してみます。`do...end`を`{...}`に変更したり、ifやunlessを後置の修飾子にしたりしてるやつです。
ちなみにbuilder.rbの`Dir.mkdir(dir) unless File.exist?(dir)`は単にunless修飾子をやめるだけではなく、`FileUtils.mkdir_p(dir) `にしてunlessを不要にしています。
> allow `do..end`, `if ...end`, or `unless...end` for single-line blocks

- test/test_compiler.rb
エスケープ(`\`)の可読性が私の限界を超えていたので、ヒアドキュメントを使うようにしてみました。
今日のRuby豆知識: `'...'`つきのヒアドキュメントを使うと完全に書いたままの文字列を表現できて便利です。 https://docs.ruby-lang.org/ja/latest/doc/spec=2fliteral.html#here
> use here document for readability

- test/run_test.rb
ex. `ruby test/run_test.rb TEST=test/test_htmlutils.rb`
> fix to use ARGV in test

- templates/latex/layout.tex.erb
config.ymlにおいて、texstyleオプションはスタイルファイル名を1つしか指定できない。
```
texstyle: reviewmacro
```
これを、複数のスタイルファイルをサポートするように変更する。
```
texstyle: [reviewmacro, mystyle]
```
こうすることで、sty/reviewmacro.styを変更するかわりに、新しいスタイルファイルsty/mystyle.styを追加してそこにカスタムのマクロを定義できるようになる。
これにより、sty/reviewmacro.styに変更を加えなくて済むので、Re:VIEWのバージョンアップがとてもしやすくなる。
> 複数のTeXスタイルファイルをサポート

- lib/review/builder.rb
#888 の対応。
動的読み込みは何かとトラブルのもとなので本当はどちらも除去したい（preproc推奨）が…
- `//include`は読み込める形式が限定され、ユーザーがいたづらに混乱する可能性が高いので除去。
- `@<include>`の最終末尾改行を削除。
- `@<include>`の読み込みの改行コードをLF揃えにする。
エンコーディングはUTF-8想定として読み込めないときにはただエラーでよいのだろうか。
inline→includeのまちがい
> //includeの破棄、@<include>の修正

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
#913 については、`//emlist[]`と空にしておいても（空の）キャプションができてしまうことが原因。
（emlistの基本的書式は`//emlist{`なので発覚しづらかった）
`caption.present?`の判定によりnilおよびemptyをスキップするようにする。
ほかにもいくつかcaptionのnil判定しかしていなかった箇所があったので同様にpresent判定にする。
> 空キャプションを無視する

- lib/review/epubmaker.rb
- lib/review/webmaker.rb
#654 に関連してる変更です。
titlepageのpublisherが印刷所だったので出版社に変更したほうがよさそうというIssueです
#546 で後方互換は廃止されてますが、この変更で出力が変わってしまうので注意したほうがよさそう。
> epubmakerとwebmakerの大扉で出版社を表示すべきところが印刷所のままっぽい

- lib/review/builder.rb
gnuplotを用いたグラフ描画を行う際に`invalid command`エラーが発生する。これに対応する。
#827 にてRubocop向けにリファクタを行った際に、`"`で囲まれた文字列を`%Q()`に修正していたが、片方の`"`が残っていたため。
不要な`"`を削除する。
```
//graph[gnuplot_test][gnuplot]{
plot sin(x)
//}
```
のようなgnuplotを用いたグラフ描画を含むコードをビルドした際にエラーが発生しないことを確認した。
テストが通ることを確認した。
> graphメソッドでgnuplotのinvalid commandエラーを修正した

- lib/review/plaintextbuilder.rb
- lib/review/topbuilder.rb
- test/test_plaintextbuilder.rb
下準備として装飾をつけないプレインテキストビルダを用意する。
TOPBuilderはPLAINTEXTBuilderを継承して拡張する。
> PLAINTEXTBuilderの導入

- bin/review
- bin/review-textmaker
- lib/review/plaintextbuilder.rb
- lib/review/textmaker.rb
- lib/review/topbuilder.rb
- test/sample-book/src/Rakefile
- test/syntax-book/Rakefile
- test/test_plaintextbuilder.rb
#926 review-textmakerを作成しました。
生成先は`<bookname>-text`フォルダです。
デフォルトはtopbuilder(装飾あり)、`-n`オプションを付けたときはplaintextbuilder(装飾なし)になります。
sample-book/Rakefileにも`rake text`、`rake plaintext`ルールを入れました。
> review-textmakerの導入

- doc/format.ja.md
- doc/format.md
`image_types`に基づく順序をformatドキュメントに明記する。
> 画像の拡張子探索順を文書化

- doc/config.yml.sample
- lib/review/pdfmaker.rb
https://qiita.com/zr_tex8r/items/a0516f211831a3fc2c0e の影響
Illustrator CCで作成したAIファイルを取り込むと、boundingboxが意図したものより一回り大きなものとなり、結果として左下にずれたものになる。
- TeX graphicsxのincludegraphics、およびbboxを作るextractbb, ebbはcropboxをデフォルトで取る
- 本来cropbox=mediaboxのはずだが、Illustrator CCで作ったものはcropboxがmediaboxよりも一回り大きいものが生成されることがある（新規のでも100％そうなった）
- 結果としてずれる。
修正方法は2種類。
- 修正パターン1： extractbb/ebbでPDFとAIにはかけないようにする。かつbuilder側のincludegraphicsを作るところで[pagebox=mediabox]や[pagebox=artbox]のようにすれば直る。ただし、毎回bboxの解析に入ってコンパイル速度が著しく遅くなる。
- 修正パターン2： extractbb/ebbで-B パラメータにより、指定のbboxを使うようにする。
後者のほうがシンプルかつコンパイル速度が速いため、後者で実装してみた。config.ymlでの指定は次のようになる。bboxを指定しなければ、extractbb/ebbのデフォルト（たぶんcropbox）になる。
```
pdfmaker:
bbox: mediabox
```
> boundingboxの取り方を変えるパラメータ pdfmaker/bbox

- lib/review/epubmaker.rb
#941の対応
Windowsネイティブ実装RubyのバグなのかWindowsの問題なのか、remove_entry_secureにせよ、rm_rfにせよ、一時フォルダが残ってしまうことがある。
フォルダが残っているときにもう一度実行するようにする。
> epubmakerで一時フォルダが残っているときに2回目のremove_entry_secureを実行するようにする

- bin/review-compile
- bin/review-epubmaker
- lib/review/book/base.rb
- lib/review/epubmaker.rb
- lib/review/pdfmaker.rb
- lib/review/textmaker.rb
- lib/review/webmaker.rb
- yamlファイル指定で存在しなかったときはnot foundエラーで即終了させる
- deep_merge時にエラーが発生したらyaml errorで終了させる。エラーの種類からより妥当なメッセージへと判断するのはyamlライブラリ側にそういうのはなくて難しそう。
_mainが長くなりすぎるようだ…
> check yaml existence and parse error. Closes #958

- lib/review/builder.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/markdownbuilder.rb
- lib/review/plaintextbuilder.rb
- lib/review/topbuilder.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_plaintextbuilder.rb
- test/test_topbuilder.rb
#954 の対応。
メッセージは`unknown <ID>`で統一した。
> インライン参照系で、見つからないIDが示されたときのメッセージを妥当なものにする

- bin/review-compile
- lib/review/book/base.rb
- lib/review/catalog.rb
- lib/review/epubmaker.rb
- lib/review/pdfmaker.rb
- lib/review/textmaker.rb
- lib/review/webmaker.rb
- test/book_test_helper.rb
- test/test_catalog.rb
raise FileNotFound error when `*.re` file in catalog.yml does not exist
> add Catalog#validate!

- lib/review/webmaker.rb
webmakerでテストしていたところ、copy_file_with_paramメソッド内でbasetmpdirが渡されずnilになっていました。
呼び出し側が複雑になっているのですが、結局basetmpdirはいらなくて`@path`があればいいのでは…？というロジックだったので無理に引数を増やすよりは`@path`を使うようにしています。
> ローカルbasetmpdirが未設定

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
TeXでimage/tableのフロートを場所によって抑制したいといったケースで、フックで処理しなければならないことがありますが、その判断が容易なようにtableやreviewimageのbegin行に%%コメントでIDを記載します。
（reviewlistblockを追加したら同様に指定を入れる予定です）
> フック処理に備え、table/imageにコメントでIDを記載しておく

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
> インライン数式前後のスペースを削除

- lib/review/book/base.rb
ディレクトリが空文字になるのは違和感があったので、@basedirと合わせてパスを返すようにしてみました。
> refactor(Book::Base): Book#contentdir should not be ""

- lib/review/book/compilable.rb
- test/test_book_chapter.rb
Now we don't use `chatpter#open` or `part#open` anyway.
> fix: Compilable#open was deprecated; use Compilable#content

- doc/config.yml.sample
- lib/review/pdfmaker.rb
- templates/latex/layout.tex.erb
#848, #839 
PDFMakerのcover, titlepageの挙動をEPUBMakerに合わせます。
互換性が破壊される状況としては、「titlepage: null だけで表紙が入らないことも期待していた」という場合、coverimage: nullもおそらく指定する必要があります。
> 表紙と大扉を個別挙動にする

- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- test/test_htmlbuilder.rb
remove `@no_error`, `@error_messages` and `@warning_messages`
`@ol_num` and `@noindent` are moved into builder_init_file, because they are initialized per files.
Builder#builder_init is now empty...
> remove unused variables in Builder#builder_init

- lib/review/book/base.rb
- lib/review/book/compilable.rb
- lib/review/builder.rb
都度basedirとimagedirをconfigから取り出してjoinする必要をなくするものです
> add Book::Base#imagedir

- lib/review/pdfmaker.rb
#962 のシンプルな対応
ただ、copy_imagesで
```
system('extractbb', '-B', @config['pdfmaker']['bbox'], *images)
system_or_raise('ebb', '-B', @config['pdfmaker']['bbox'], *images) unless system('extractbb', '-B', @config['pdfmaker']['bbox'], '-m', *images)
```
とsystemを使ってるところがあって、そこはまだ入れていない。system_or_raiseと似た、raiseしないメソッドを作る必要がある?
> pdfmakerでの実行コマンドをinfoレべルで表示する

- lib/review/book/chapter.rb
- lib/review/preprocessor.rb
- lib/review/tocparser.rb
We usually have no need to use Strip class.  review-preproc's --strip option is special case.
In other cases, we should remove comment line `#@...`  without Strip class.
In addition, both Strip#each and Preprocessor.strip are not used.
> Preprocessor::Strip should be used only in review-preproc

- test/test_helper.rb
> make it simple with FileUtils

- lib/review/builder.rb
builder.rbのgraphロジックを扱いやすいように変更してみるのと、platnuml記法のサポート。
- Windowsでも実行可能なようにできるだけ一時ファイルを作成（拡張する人がやりたければ標準入力で行うことも可能）
- `graph_描画エンジン` の任意の名前のメシッドを呼び出すように。id、保存先ファイルパス、//{〜//}内のアンエスケープ済み文字列、一時ファイルパス を引数とする。idは単にエラー時の参照用。メソッドは「保存先ファイルパス」を返す（.pdfじゃなくて.epsで返したいときなどのため）
- plantumlはカレントまたはCLASSPATH環境変数範囲にplantuml.jarがあることを前提、呼び出しコマンドも「java」であること前提
`system()`を使う限りエラー時にstderr内容が取れないのが辛いところ。systemuが標準に入ってくれないものか…（gemはいやだ）。
コマンドパスや引数などをyml指定するというのも考えたのだが、引数パースや、Windowsを考えると厄介そうなので、そこまでこだわる人はreview-ext.rbで適当に上書きしてくれるほうがよさそうと判断した。
> graphロジックの分離とplantumlのサポート

- lib/review/pdfmaker.rb
a54217 で入れていただいた削除変更ですが、カスタムのlayout.tex.erbを使い続けていた場合にusepackageパラメータが空になってしまってまずいことになります。
後方互換性のために戻したい（ただし新しいレイアウトファイルからこのパラメータを使うことはない）と思います。
> @config['usepackage']の設定を戻す

- lib/review/htmlbuilder.rb
- lib/review/htmlutils.rb
- test/test_htmlbuilder.rb
#1016 の修正
- 識別子IDによるlexer自動判定をやめる（HTMLビルダのみ、かつ//list、//listnumしか使えない）。各リストタグのlangオプションを使うべき
- 上記に伴い自動判定テストを1つ削除
- rougeの処理でlexerおよびformatterの判定に失敗したときにraiseせず、pygmentsと同様にハイライト前のbodyをただ返すようにする（そもそも前のコードだとnilの内容を`#{}`で表示しようとしていて意味がない）
> rouge時の処理のエラー対応

- lib/review/configure.rb
- lib/review/latexbuilder.rb
- lib/review/latexutils.rb
`is_r2?`はさすがにバージョン番号を陽に書くのはいかがなものか…ということで、Configure#check_versionの例外を挙げないやつを作ってみました。
> rename version-depend method name

- lib/review/idgxmlbuilder.rb
> idgxmlビルダで=[notoc]および=[nodisp]をサポート

- doc/config.yml.sample
- lib/review/configure.rb
#919 の代わり。
デフォルトである `-z 9` を明記で入れた。
カスタマイズTipsはpdfmaker.ja.mdで書くことなのか、どこかに書いたのをWikiからポインティングする程度にすべきか…。
> -zオプションをconfig.ymlのサンプルに記載

- test/test_htmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_topbuilder.rb
テストで警告が出るので、出力しない＆警告の中身をテストするように修正します
> suppress warning of `@<w>{}` in tests

- .rubocop.yml
- lib/review/htmlbuilder.rb
- test/test_htmlbuilder.rb
`@<m>{...}`や`//texequation{...//}`で数式画像を生成する際にLaTeXのログが出力されるのを抑制します。
エラーが出た場合にはその際にログをまとめて出力します。
> HTMLBuilder: hide latex log of `@<m>{...}` amd `//texequation{...//}`

- lib/review/compiler.rb
`definline :tcy` is duplicated in compile.rb
> remove duplicated tcy

- lib/review/latexbuilder.rb
- templates/latex/review-jsbook/review-basemacros.sty
related to: #655 
標準はグループルビにしています。
※現状のRe:VIEWではルビ文字列に`|`が突っ込めない（エスケープされる）のでグループルビ以外NGです
> support pxrubrica by default

- lib/review/pdfmaker.rb
`Open3.capture2e` ( https://docs.ruby-lang.org/ja/latest/method/Open3/m/capture2e.html ) を使って、コマンドを実行したときにエラーがでなければ標準出力・標準エラー出力へのアウトプットを行わないようにするものです。
なおエラーが出たときにはそれまでのログを全部まとめて吐き出します。
> hide (latex and other commands') log messages

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
* remove `\vspace{-1.5em}`
* remove caption if caption (and title) is empty
> LATEXBuilder: fix empty caption for listings

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
uplatexやlualatexの場合、`@<uchar>` で指定したUnicode文字を`\UTF`マクロなしでベタに出力するものです。
> LATEXBuilder: allow to use Unicode character without otf package if possible

- test/sample-book/src/Rakefile
RakefileのCONFIG_FILEやいくつかの変数をrake実行時に上書きできるようにしました。
たとえば通常の設定はconfig.ymlに書いているものの、体験版だけ生成するファイル名や表紙を変えたい場合に、以下のようなconfig-taiken.ymlを作っています。
```
inherit: ["config.yml"]
bookname: book-taiken
booktitle: Re:VIEWサンプル書籍【体験版】
coverimage: cover-taiken.png
```
このconfig-taiken.ymlを使いたいときに、lib/task/review.rakeを書き換えることなく以下のように実行できると嬉しいというのが、本変更の趣旨です。
```
$ rake CONFIG_FILE=config-taiken.yml all
```
一応BOOKやWEBROOTも変えられるようにはしています。BOOKが変えられるようになると、config.ymlのbooknameを変更していてもrake cleanできるというメリットもあります。
> RakefileのCONFIG_FILEをrake実行時に上書きしたい

- lib/review/pdfmaker.rb
- templates/latex/layout.tex.erb
#1035 のコメントをもとに。
- platex系以外のコンパイラではdvipdfmxドライバが不要なことがある。layout.tex.erbから`dvipdfmx,`を除去する。
- 既存文書の互換性維持として、dvicommandパラメータがデフォルトのままか、明示してもパラメータにdvipdfmxという文字列がある場合は`dvipdfmx,`をdocumentoptionに付与する。
- documentoptionにすでにdvipdfmxという文字列を含む場合は何もしない。
> dvipdfmxオプションはdvicommandパラメータの文字列で判定するように

- test/sample-book/src/Rakefile
catalog.ymlやimages/以下のファイルが更新されたときにも、
rake allでepubやpdfが再ビルドされると嬉しいです。
本修正では以下のファイルがビルド時の依存ファイルとなります。
* カレントディレクトリ以下のすべての.reファイル
* 注：これまではカレントディレクトリ直下のみ対象だった
* カレントディレクトリ直下の.rbファイル（``review-ext.rb``用）
* カレントディレクトリ直下の.cssファイル（epub taskのみ）
* sty/以下の.styファイルとlayouts/直下の.erbファイル（pdf taskのみ）
* images/以下のすべてのファイル
* 環境変数``REVIEW_DEPS``でカンマ区切りで指定したファイル
* ``credit.xhtml``のようなconfig.ymlの設定次第で必要になるファイルを想定しています
また、一応catalog.ymlも変数化して環境変数で上書きできるようにはしてあります。
実際にtouchとrakeを繰り返した例は以下のとおりです。
```
$ rake all
$ touch catalog.yml
$ rake all
review-pdfmaker config.yml
(snip)
review-epubmaker config.yml
(snip)
epub taskのみ影響するファイル
$ touch style.css
$ rake all
review-epubmaker config.yml
(snip)
pdftask のみ影響するファイル
$ touch sty/review-base.sty
$ rake all
review-pdfmaker config.yml
(snip)
REVIEW_DEPSを指定しなかったときと指定したとき …
```
> Rakefileの依存関係にcatalog.ymlなどを追加したい

- templates/latex/review-jsbook/review-style.sty
いったんレイアウト周りの設定を消します。とはいえこれだと壊れた感じなので、あとで対応策を考えておきます…。
あと、特にメリットはなさそうですが、`\ProvidesPackage`とかを追加しておきます。
> remove default style

- lib/epubmaker/producer.rb
- lib/review/epubmaker.rb
EPUBMakerで`puts`や`warn`を使っている部分が残っていたので、これをLoggerに置き換えるものです。
`EPUBMaker#log`は`debug: true`のときしか出力されないようになっていたので、log levelを設定して同様になるようにしています。
> Use logger in EPUBMaker

- lib/review/pdfmaker.rb
#1080 の対処。
とりあえず`__REVIEW_BOOK__`でどうだろうという提案。`pdfmaker#initialize`の`@mastertex`で定義しているので、変えること自体は簡単。
book.texという名前前提で何かしているようなフックには影響するけど、それはあまり気にしてもしかたなさそう。
> layout.tex.erbからの生成時、book.texの代わりに内部名っぽいファイルを使う

- lib/review/compiler.rb
- test/test_latexbuilder.rb
- test/test_latexbuilder_v2.rb
- test/test_topbuilder.rb
#1083 の修正。
テストを変更しましたが、この結果が希望に沿った動作です。
（latex側は別のエスケープでごちゃごちゃしているので、topbuilderのテストのほうで見るのがわかりやすいです）
各処理メソッドに渡す前にrevertするようにしました。
> フェンスrevertのタイミングを変更

- lib/epubmaker/producer.rb
modifiedの値は、Z後置子を付けていたらUTCであるべきなのに、Time.nowでlocaltimeのまま作ってしまっていました。Zの代わりに+09:00とする方法もあるようですが、ソフトが解析するパラメータなのでUTCのほうが都合がよさそうです。
https://www.w3.org/TR/NOTE-datetime
> OPFのmodifiedの時刻情報がlocaltimeで入っていたのをUTCに修正

- lib/review/latexbuilder.rb
- templates/latex/review-jlreq/review-style.sty
- templates/latex/review-jsbook/review-base.sty
- templates/latex/review-jsbook/review-style.sty
- test/test_latexbuilder.rb
latexbuilderおよびスタイルファイルで、tableはh（=htp）、imageはHというフロート配置になっていますが、そもそもfloat.styを組み込んでいるので決めうちよりも`\floatplacement`マクロで制御するほうが妥当そうです。
いちおうRe:VIEW 2系には後方互換でtableにhを残しています。
> pdfmaker: tableとfigureでのフロート設定をマクロで定義できるようにする

- doc/config.yml.sample
> config.yml.sampleに索引関連のフックとパラメータのコメントを追加

- bin/review-epub2html
- lib/review/epub2html.rb
CSS組版向けに、EPUBから単一HTMLを作成するツールです。
Re:VIEW以外のEPUBについては考慮外です。
1つめの引数にEPUBファイル、2つめの引数はオプションでHTMLの<body>前後文字列の元とするHTMLファイル名（EPUB内でのファイル名）をとり、spine情報に基づいて結合したHTMLを標準出力に吐き出します。
> review-epub2htmlの導入

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
Re:VIEW 3から入れたstyのロジックで、
coverパラメータ(カスタムなtex断片ファイル指定)を入れる→\review@coverfileにその内容が読み込まれて入るの後、
\review@coverfileがあればそれを使い、coverimageに優先する が正しい挙動のはずが、
間違って何も定義のない \review@cover で判定していた、coverimageがあると上書きしてしまっていた
のを修正します。
> TeX: coverパラメータでカスタムした効果の適用

- templates/latex/review-jsbook/review-jsbook.cls
* review-jsbook.cls: defined paper=<papersize>
* jsbook.clsへ渡すオプションを廃止：<papersize>j, <ptsize>pt options
* (cameraready=ebook): jsbook.clsに対する制御をミスっていたので修正
> review-jsbook.cls: paper=<papersize>に対応

- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/README.md
- templates/latex/review-jsbook/review-jsbook.cls
クラスオプション `tombopaper`, `paperwidth`, `paperheight` を gentombow パッケージ前提で実装しました。
> review-jsbook.cls (tombopaper,paperwidth,paperheight): supported

- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/review-base.sty
- templates/latex/review-jsbook/review-jsbook.cls
これは良くないので、除くべきです。
``` tex
\setlength{\footskip}{30pt}
```
なお、review-jsbook.cls では、クラスオプションとして footskip のほか、headheight, headsep も利用できるようにしています。
> review-jsbook/review-base.sty (\footskip): dropped

- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jlreq/reviewmacro.sty
- templates/latex/review-jsbook/review-jsbook.cls
- templates/latex/review-jsbook/reviewmacro.sty
`review-{jlreq,jsbook}.cls` + `reviewmacro.sty (review-{base,style,custom}.sty)` 中だけで利用可能な（通常のLaTeXの \AtBeginDocument と同等な挙動を持つ）フック `\AtEndOfReVIEWMacro` を実装しました。
このフックが嬉しいのは、例えば、cls ファイル内で tcolorbox が提供する \newtcbbox を cls で定義する節見出し \section で利用したいとします（展開するマクロ内ではなくて、スコープが浅いところで）。
すると、順番に cls -> sty を読んでいきますから、\newtcbbox をTeX側が知るためには、 早いところで \usepackage{tcolorbox}をしている必要があります。
しかしながら、各種パッケージの読み込み順の制御や読み込みパッケージをまとめておきたい場合に、これでは、cls 内の \section の場所で \newtcbbox が利用できないことになります（もちろん、マクロの定義を点在させれば、可能ですが分かりにくいですよね。もちろん、tcolorbox パッケージよりも後に 節見出し \section を再定義すればよいですが、 cls ファイルとしてデザインを提供している場合は、面倒ですよね。）。
そこで、必要な場所で \AtEndReVIEWMacro{  ... } を順に入れておくだけで、 reviewmacro.sty 読み込みの一番最後で、 \AtEndReVIEWMacro で入れたものを一気に実行します。（\AtBeginDocument などと同じ使い勝手！）
実際のところ、これを利用するユーザーは、かなり限られるとは思いますが、あっても悪くないと思います。
> supported \AtEndOfReVIEWMacro 

- doc/config.yml.sample
- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/README.md
- templates/latex/review-jsbook/review-base.sty
- templates/latex/review-jsbook/review-jsbook.cls
jlreqでひとまずそれっぽく動くようになったので、jsbookのほうにも入れます。
titlepageの挙動が違うのでcls側で書き換えているのと、startpageの持ち方が違います（jlreqでは-1する必要があったけどjsbookではそのままを使う）。
> TeX: cover,bleed_margin,serial_pagination,startpageのjsbookへの追加

- templates/latex/review-jsbook/review-jsbook.cls
#1131 review-jsbook.clsのクラスオプションhiddenfolioを実装しました。
* default: (none)
* available: default (それとなく), marusho-ink (丸正イ○キ), nikko-pc (日光○画)
とりあえず、隠しノンブルの実装の核となる部分は、実装できました。
> review-jsbook.cls (hiddenfolio): 隠しノンブルの実装

- lib/review/init.rb
#1102 の対応。
プロジェクトフォルダの作成後にzipアーカイブを単純に上書き展開するという仕掛けです。
- `-p ローカルファイルパス` または `-p https://〜`・`-p http://〜`  でzipファイルを指定します。
- ネットワークダウンロードは `Net::HTTP` なので301などには対応していません。パスワード制限のところにも対応していません。まぁこのあたりはダウンロードしてから指定してもらうのがよさそう。open-uriは今は使うべきではない、になっているんですね…
- 一応「`/`」から始まるパス、および「`/../`」が含まれるパスは発見次第展開を中止するという安全策は入れています。
- パスの日本語まわりなどはOSのロケール状態まで見るのもきついので対処していません。
> review-initへのアーカイブロード展開の機能の追加

- lib/review/configure.rb
- lib/review/pdfmaker.rb
せっかく互換ロジック入れていたのにタイプミスしていました。
3pre3に入れたいです。
> TeX: Re:VIEW2向け互換性サポートの修正

- lib/review/htmlbuilder.rb
- lib/review/makerhelper.rb
- test/test_htmlbuilder.rb
#1146 の対応
- fontsize設定を`\begin{equation*}`の中にも入れるようにしました。
- DPIを大きくしたときにデフォルトのA4だとすぐに描画エリアをはみ出すので、とりあえずA3横にしておきました。もっと大きくしたいときには各自で`\setlength\paperwidth{1000mm}`とかプリアンプル書いてもらう方向で。
> imgmathのtexequation内fontsizeの設定と一時紙面サイズの拡大

- templates/latex/review-jsbook/review-jsbook.cls
私のほうでebookに名前を変えたときに対処漏れしていました。すいません。
> TeX: review-jsbook.clsでpaperwidth,paperheightが効かないことの修正

- templates/latex/review-jsbook/review-jsbook.cls
#1158 の修正
tomboだとgentombow内部でバナーなしになってしまう。tombowにする必要があった。
> TeX: review-jsbookでhiddenfolio+tombopaperを使ったときにfolioが無効になることの修正

- templates/latex/review-jsbook/review-jsbook.cls
#1170 については結局本の作り方に依存してしまうので「こうである」という対処がないのですが、少なくとも「空ページを作る」のと「偶数ページまで改丁する」の命令は用意しておいたほうが、自力でreview-customでマクロ書き換えをしてもらうにしても説明が楽そうに思いました。
過去にmunepiさんが作って報告されていたものそのままですが。あと、縦書きはひとまず無視しています。
- `\oneblankpage`: 空の1ページを作成
- `\clearoddpage`: 次の偶数ページになるまで改丁（現在偶数なら何もせず、奇数なら改丁）
> TeX: oneblankpage, clearoddpageを追加

- doc/config.yml.sample
- lib/review/update.rb
- samples/sample-book/src/config.yml
- samples/syntax-book/config.yml
- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/README.md
- templates/latex/review-jsbook/review-jsbook.cls
- test/test_update.rb
#1181 の対応。
単純にcamerareadyと同じマクロを定義します。
両方を同時に設定することは現実的にはないはずですが、その場合でも別にエラーにはならず、documentclass内で後に定義したほうが有効になる、かな。
ドキュメントなどもmediaに寄せました。
> TeX: mediaオプションの追加

- lib/review/i18n.yml
- lib/review/update.rb
- test/test_update.rb
#1183 の対応
`@template` の扱いを修正し、新クラス名での更新が正しく働くようにしました。
新しいファイルを追加したときに黙ってではなくinfoレベルで出すようにしました。
> review-update: fix updater to update sty correctly. info about new file

- lib/review/latexbuilder.rb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
#1195 の対応
reviewpart環境で囲み、この中でsectionの番号をchapterではなくpartから拾うように変更します（採番したくないときには普通にnonumを使ってもらう）。
Re:VIEWバージョン2の場合はいちおう互換性のために以前どおり全部partにします。
cls側で対応することも考えましたが、reviewpart固有環境で囲むほうがクラスファイルを問わないので処理が簡易そうと判断しています。
> reviewpart環境で囲む

- lib/review/pdfmaker.rb
- templates/latex/config.erb
#1197 に関連して。
「部があるかどうか」の判断をTeX側でやるのは\partの上書きなど手間なので、pdfmakerロジック内で判定して、部があれば\reviewusepartを定義（値はtrue）するようにします。
このマクロを見てRe:VIEWのクラス/スタイル側で今どうするというのはないのですが、たとえば\appendixや\backmatter内でこれを見てしおりのtoclevelをデクリメントするといったケースを想定しています。
> TeX: 部が存在するときにはreviewusepartマクロを宣言する

- templates/latex/review-jsbook/review-jsbook.cls
QWLHオプションを廃止、jlreq.clsのオプション名に準じて、
fontsize,line_length,number_of_lines,baselineskip
を対応しました。
* fontsizeには、jsbook.clsが対応しているフォントサイズのみ対応しています。それ以外の値を入れたら、jsbook.clsが対応しているフォントサイズに近いフォントサイズとして、動作します。
* これに伴い、相対フォントコマンドの変更をすべて廃止し、jsbook.clsに丸投げしました。
* line_length,number_of_lines,baselineskipを与えた場合、jsbookで定まっている基本版面をベースに、部分的に調整できるかもしれません。
* カスタム用紙サイズ（paperwidth,paperheight）を与えたら、基本的には、基本版面をすべて設定することになります。
> reviewjsbook.cls: jsbook.cls丸投げに変えました。

- lib/review/update.rb
- templates/latex/review-jsbook/review-jsbook.cls
- test/test_update.rb
#1200 取り込み後の対応。
preview時代のreview-jsbookのQWLHを使った指定があるときに、review-updateで適切なパラメータに更新します。
- Q=n→fontsize=nQ
- W=n→line_length=nzw
- L=n→number_of_lines=n
- H=n→baselineskip=nH
- head=nunit→head_space=nunit
> review-update: QWLHで定義されている場合の移行

- doc/config.yml.sample
- lib/review/init.rb
- lib/review/update.rb
- templates/latex/review-jsbook/review-jsbook.cls
- test/test_update.rb
同様に #1200 に絡んで、
jsbookとの互換性を重視したことで、クラスファイル自体はデフォルトの紙サイズがA4に戻りました。
ただ、これから新規に制作しようという人にはこれでは困るので、review-initでプロジェクト作成時に、texdocumentclassのコメントを外し、明示的にpaper=a5のパラメータを指定するようにします。
これとあわせて、latex-templateオプション指定を付けたときには、そのクラスファイル名をtexdocumentclassに入れるようにもしました。
> review-initで明示的にtexdocumentclassを設定

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
clsファイルに入れるか悩んだけど、xcolorパッケージの読み込みをしているのがbase.styなので、そちらのほうに入れることにしてみました。
通常の表のセルにおける段落モード「`p{〜}`」は左寄せ均等割り付けなのですが、これでは不便なこともあります。以下を追加します。
- `L{〜}`: 左寄せ（均等割り付けなし）で段落モード
- `C{〜}`: センターで段落モード
- `R{〜}`: 右寄せで段落モード
上下はセンターになるんですが、pみたいに上合わせにしたほうがいいのかな（strutを使う？）
> TeX: L,C,Rのスタイルを追加

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
#1206 の対応
現在、表のセル内でbrを使用したときにはtsizeの値が何であろうともshortstackマクロを利用するが、これは見た目が悪い。
tsizeでpによるセル段落化指示があったときには、shortstackではなくnewlineにするようにする。
互換性のため、
バージョン2以前のプロジェクトの場合は何もしない。
幅指定がない（l,c,r）場合にはshortstackを使い続ける。（l,c,rの場合はnewlineは効かない）
> セルが段落モードのときはセル内改行をnewlineにする

- templates/latex/review-jsbook/review-jsbook.cls
jsbook.cls, gentombow.styをvendor/にコピーすることになったので、
* `gentombow09j.sty`対応を落とします。
* ついでに、古いTLのjsbook.cls対応のコメントも落とします。
> review-jsbook.cls: dropped gentombow09j support

- .travis.yml
* fix https://travis-ci.org/kmuto/review/jobs/471337080
```
$ gem update --system
Updating rubygems-update
ERROR:  Error installing rubygems-update:
rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
undefined method `version' for nil:NilClass
The command "gem update --system" failed and exited with 1 during .
```
* update ruby (rvm) versions: use latest stable
> TravisCI: do not update rubygems

- README.md
`README.md` のライセンスのところで、 `jsbook` の拡張子が間違っていたのでPRを送ります。
> README.md: s/jsbook.sty/jsbook.cls/

- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/review-jsbook.cls
ヘルパーマクロとして、review-jsbook, review-jlreq.clsに `\makelines` というマクロを追加します。
```
//embed[latex]{
\makelines{20}
//}
#@# 20行の■□■□…からなるダミー行を作成する
```
版面設計のときにはこういうマクロが何かと必要となります。
> TeX: \makelinesマクロの追加

- templates/latex/review-jlreq/review-jlreq.cls
あけましておめでとうございます。review-jlreqをいじっています。
- 先のコミットでpxjahyperまわりの判定を間違っていた（driverではなくengineで判定しないといけない）のを修正しました。
- tombo有効時に、pdfpagesパッケージで読み込んだPDFがずれる問題があります。根深い問題に思われるので、ひとまずパッチで対処します。
- なんとなく日付と年度を更新しました。
> review-jlreq: pxjahyperの判定の修正、pdfpagesトンボの修正

- lib/review/preprocessor.rb
#1247 の修正です。
ちょっと悩んだのですが、指定されたファイル名が.re拡張子のときには「ありのまま」使うようにしました。
（従来と同様に、mapfileしたものからさらにmapfileするといった再帰はできません）
> #@mapfile等でre拡張子時にはタブなどを含めて「ありのまま」取り込む

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jlreq/review-jlreq.cls
- `zw`はLuaLaTeXでは実装されていない単位のため、`\zw` を使うようにしました。upLaTeX用にはjlreq.clsが`\zw`→`zw`の面倒を見てくれるので問題ありません。
- コラムの場合に字下げがないのはたしかに気になるので、インデントを付けるようにしました。noteやmemoには入れていませんが、同じようにして付けることは簡単に可能ではあります。
> use \zw insead of zw for LuaLaTeX. add 1 indent space for column.

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/review-base.sty
#1252 の修正です。
折り返し対策でtabularのpを使ってみていましたがやはりどうしようもないので、tabularxを導入して、左列を「l」、右列を「X」（残りを使って折り返し）とすることにします。
-0.5emはなんとなくですが、こうしないとちょっとはみ出るっぽい。
> TeX: 奥付の左列が3文字以上の場合にあふれるのを回避

- lib/review/htmlbuilder.rb
#1231 の対応
HTMLBuilderのemlistnum, listnum でハイライト有効無効にかかわらずhighlightメソッドを経由するようにしました（ほかのcmd、list等はこうなっている）。
ハイライト無効の場合は改行結合文字列をまた改行でバラすという無駄なことにはなりますが、コードリストはまずhighlightを通るという形になるので、review-ext等で扱いやすくなります。
> HTMLBuilder: emlistnumとlistnumで常にhighlightメソッドを経由するように

- lib/review/preprocessor.rb
#1258 の対応
出力方法はちょっと悩むのですが、「わかっている」人が使うものであり、実際の用法を考えると単純に`#@warn(〜)`の中の「〜」部分をWARNとして表示したほうがよいのではと考えました。
```
#@warn(ほげ)
↓
WARN: test.re:2: ほげ
```
あえてカッコも含めた判定としたので、以下だとそのまま出ます。
```
#@warn ほげ)
↓
WARN: test.re:2: #@warn ほげ)
```
> #@warn の実装

- bin/review-preproc
#1257 の対応
`--strip` オプションの実用性は低く、開発陣は誰も使っていなくてバギーなので削除します。
> remove --strip option from review-preproc

- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/topbuilder.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_topbuilder.rb
#1264 の修正。
`//comment[]`と`//comment{`の両方で正しくエスケープされるように修正しました。
> //commentのエスケープの修正

- templates/latex/config.erb
- templates/latex/layout.tex.erb
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
#1267 の対応。
reviewimagecaptionのようにreview-updateしないと壊れるんだけど気付きにくい、というかなり限定した用途のみで後方互換性を保つロジックを記載し、\begin{document}前で呼び出します。
ユーザーが書き換えることは想定しておらず、config.erbでシステムで定義します。
現時点では以下の機能のみを中身に書いています。
- `\reviewimagecaption`が定義されていないようであれば定義する。すでに定義されているなら何もしない。
増えるたびにテストassetsも書き加えないといけないのがナンなので、今後はなるべく使わないで済むようにしたいですね…。
> \reviewbackcompatibilityhookの導入

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
newcommandで定義したものだと、展開が安全にならないことがあるため、とりあえずインライン書体変更命令を RobustCommand で定義する。
- https://twitter.com/wtsnjp/status/1095253908891394048
- https://github.com/TechBooster/ReVIEW-Template/issues/29
reviewttやreviewitは`[1]`や`{#1}`をなしにして展開をそっちに送ることができるみたいだけど、`reviewttb`みたいなのだとどうするんだろう…？そこでexpand系？
> 目次に入りそうなインライン命令をRobustCommandで定義する

- lib/review/builder.rb
- test/test_builder.rb
> 章付きキー参照で章がないときに内部例外ではなくKeyErrorを発生させるようにする

- templates/latex/review-jsbook/review-jsbook.cls
#1288 の修正。
renewcommandだと展開でPDF内の情報が変なものになるようなので、もともとのlatex.ltxの内容に基づいて定義し直します。
latex.ltxのもともとの内容は
```
macro:#1->\global \c@page \@ne \gdef \thepage {\csname @#1\endcsname \c@page }
```
このうち、最初のページリセット部分を除き、#1を取って展開するところはリテラルに@arabicとすることで通しノンブル化します。
> pagerenumberingの再実装

- lib/epubmaker/epubcommon.rb
- lib/epubmaker/epubv3.rb
- templates/opf/epubv3.opf.erb
#1292 の代替
- もともと epubv2 向けにcommonでopf_coverimageというのを用意していた
- EPUBv3では表紙のmetaは不要になったはずでopfからは除去していたが、AppleのiBooksではまだこれを参照してしまう模様
- metaがあること自体でvalidatorがエラーになることはないようなので、EPUBv3でも復活させる
> epubmaker: include cover image into metadata for iBooks

- lib/review/book/index.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/plaintextbuilder.rb
- test/test_index.rb
#1294 の対応
- notoc, nodispがあったときには採番カウンタを増やさない。numberで呼び出されるときには空文字列とする（nilでもよかったかもしれないけど、ちょっと互換性など怖いので）
- 各ビルダのほうはnumberが空だったらwithout_numberのほうのフォーマット文字列を利用する
- テストどう書くといいんでしょう…
notocの下位にnotocではない見出しを付けたときには、notoc前の採番ルールに従うことになる。これに対処するのはきついので仕様としたい。
```
ch01.re
== A
==[notoc] B
=== C
== D
```
とあるとき、Aは「1.1 A」、Bは「B」、Cは「1.1.1 C」、Dは「1.2 D」に展開される。このCのこと。
> headline解析でnotoc, nodispを飛ばす

- templates/latex/review-jlreq/review-base.sty
> jlreq.cls 0401版への対処

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
munepiさんに相談したところ、needspaceを使うのがよいのではということで実装してみました。
図表以外で独自キャプションを付けているリスト系（reviewlistblock）, 式系（reviewequationblock）では現状、キャプションと内容とは結合しておらず、ページの位置によっては泣き別れが発生する。
フロートにするにもなじまないので、needspaceを使ってキャプション+αの空き領域を確保するようにする。
- 空き確保はとりあえず2行ぶんにしておく。キャプションが2行以上になるとダメだが…
- review-jlreqのreviewlistblockの値が2や3だとだめで4くらいにしないといけない理由がよくわかってない。
> PDFMaker: needspaceを利用してキャプションとブロックの泣き別れを防ぐ

- bin/review-epubmaker
- lib/review/epubmaker.rb
#1281 の対応
`review-epubmaker --debug  (--no-debug)`オプションを追加します。
pdfmaker.rbで実装を示していただいていたおかげで、思ったよりも大変でなくできました。
性質上、特に後方互換性が失われるものはないはずです。
> add --debug flag to review-epubmaker

- .travis.yml
- appveyor.yml
- lib/epubmaker/epubv2.rb
"review-init hello2 --epub-version 2"で作成した初期ディレクトリでepubmakerを走らせると、
以下のエラーで落ちたため、テストの追加(travis / appveryorでのreview-init + epubcheckによる形式チェック)と共に修正をPRさせていただきます。
エラービルド：
https://travis-ci.org/mitsuo0114/review/builds/535126919
```
$ ruby bin/review-init hello2 --epub-version 2 && cd hello2 && ruby ../bin/review-epubmaker config.yml && epubcheck book.epub
WARN: hello2.re:1: headline is empty.
Traceback (most recent call last):
14: from ../bin/review-epubmaker:16:in `<main>'
13: from /Users/travis/build/mitsuo0114/review/lib/review/epubmaker.rb:70:in `execute'
12: from /Users/travis/build/mitsuo0114/review/lib/review/epubmaker.rb:105:in `execute'
11: from /Users/travis/build/mitsuo0114/review/lib/review/epubmaker.rb:199:in `produce'
10: from …
```
> Add Travius and appveryor test code and Fix epubv2

- lib/review/preprocessor.rb
- test/test_preprocessor.rb
related: #1257, #1261
上記のissue/PRの対応によりStripクラスの出番はなくなったようなので、クラスごと削除します。
> remove ReVIEW::Preprocessor::Strip; not used now

- lib/review/latexbuilder.rb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
- test/test_latexbuilder.rb
fix #1220 
pxrubrica を使っているので、そのまま `\kenten` にしてみました。
生成するのは `\reviewbou{...}`にしています。
> LATEXBuilder: support `@<bou>{...}`

- lib/review/compiler.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
#1313 の修正
`**`から始めたり、`*`の後に`***`を始めたり といった書き方を禁止します。
現状テストはエラーになるので修正しますが、どっちにしろこういう使い方はしないはず…。
> ulリストでレベルを1つより多く飛ばすのを禁止する

- templates/latex/review-jlreq/review-base.sty
Debian busterのjlreqはちょっと古いバージョンでマクロ整合性が合わないため、互換性をとるようにします。
> jlreq.clsの古いバージョンに対応

- lib/review/latexbuilder.rb
- templates/latex/config.erb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
- test/test_latexbuilder.rb
#1318 の対応提案です。
review_versionが2のときには普通にincludegraphicsになります。3の場合はconfig.erbで後方互換性をとるようにしています。
> 抽象名\reviewincludegraphicsの導入

- .rubocop.yml
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_latexbuilder_v2.rb
- test/test_markdownbuilder.rb
- test/test_md2inaobuilder.rb
- test/test_plaintextbuilder.rb
- test/test_rstbuilder.rb
- test/test_topbuilder.rb
#1327 の前段階として、expectedに複数行を含んでいてわかりにくそうな箇所をヒアドキュメント化することにします。
> テストコードで期待値が複数行でわかりにくい箇所にはヒアドキュメントを使う

- lib/review/builder.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/markdownbuilder.rb
- lib/review/plaintextbuilder.rb
- lib/review/topbuilder.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_plaintextbuilder.rb
- test/test_topbuilder.rb
#1325 の対応です。
`return if rows.empty?` を早期に実行して開始部に至らないようにします。
> 空のtableをエラーにする

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
> ul,ol,dd,bibpaperでjoinする前に末尾改行を取り除く

- NEWS.ja.md
- NEWS.md
- lib/review/markdownbuilder.rb
- test/test_markdownbuilder.rb
ぎりぎりのタイミングですが、``//listnum``のサンプルがコケたので追加しておきます。
> MARKDOWNBuilder: support listnum

- lib/review/book/base.rb
- lib/review/book/chapter.rb
- lib/review/book/part.rb
- lib/review/preprocessor.rb
- lib/review/tocparser.rb
#1341 の修正です。
書く環境と処理する環境がDocker利用などで異なるときに改行コードの違いが生じてしまうことがあるので、処理側でLFに統一させることにします。
> File.open時に「rt」フラグで改行コードをLFに統一する

- lib/review/idgxmlbuilder.rb
idgxmlbuilderにemとstrongがなくてidgxmlmakerのテストが面倒めなので、追加しておきます。
副作用はありません。
> add em and strong to idgxml

- doc/config.yml.sample
- doc/format.ja.md
- doc/format.md
- lib/review/configure.rb
- lib/review/htmlbuilder.rb
- lib/review/makerhelper.rb
- lib/review/textmaker.rb
- lib/review/textutils.rb
- lib/review/topbuilder.rb
- samples/sample-book/src/lib/tasks/review.rake
#1338 の対応
- 旧互換のためにtextmaker/imgmathはnullにしている…けどメーカ単位で分けずに親のimgmathパラメータをそのまま使うのでもいいかも(分けたいときはconfig.ymlレベルで分ける)
- pdfcrop_pixelize_cmdがpng固定だったので%tでフォーマット名が入るように
- defer_math_imageは共有のためhtmlbuilderからtextutilsへ
- とりあえず数式フォルダはEPUB側とわけるために `_review_math_text` とした
なお、PDFのまま保持したいときは
```
textmaker:
imgmath: true
imgmath_options:
format: pdf
extract_singlepage: true
pdfextract_cmd: "pdftk A=%i cat A%p output %o"
pdfcrop_pixelize_cmd: "mv %i %o"
```
というかんじです(pdfextract_cmdのデフォルトで使っているpdfjamだと、どうもghostscriptのバグで結果がおかしい？)。
> TextMakerでimgmathをサポートする

- lib/review/init.rb
#1340 の対応
空のlayoutsフォルダはいたづらに混乱させるだけで、Re:VIEW3でlayoutsをいじることは特にTeXでは不要になっているはずなので、initで作るのをやめたいと思います。
> layoutsフォルダを作るのを廃止

- templates/latex/review-jlreq/review-base.sty
#1363 の対応
review-jlreqのtcolorboxの前景文字色について、
\colorのかわりにcoltext=whiteを使います。
review-jsbookのほうはtcolorboxを使っていないので影響しません。
> use coltext=white instead of \color

- templates/latex/review-jsbook/README.md
jsbook.clsそのまま継承のオプションを知りたい、という声があったので追記してみました。
> review-jsbook/README.mdにjsbook.clsのオプション説明を追加

- lib/review/latexbuilder.rb
ハイライトを使用しない場合に、行番号なし版および行番号あり版それぞれRe:VIEW側で面倒を見ていますが、コード各行に対する処理(タブとりや行番号付け)をメソッドとして切り出しました。
挙動としては従来と変わりませんが、挙動overrideしたいときに個々のコードリストメソッドを書き換えなくてもcode_line, code_line_numの書き換えだけで済むようになります。
(冗長ながらtype,id,caption,langも渡しているのは書き換え前提としているためです。)
> PDFMaker: code_lineとcode_line_numにコードリストの各行の装飾を引き渡し

- lib/review/builder.rb
- lib/review/latexbuilder.rb
`Builder#highlight?` をHTMLBuilder以外でも使えるようにする修正です。
> add Builder#highlight? for all builders

- lib/review/builder.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/markdownbuilder.rb
- lib/review/plaintextbuilder.rb
- lib/review/topbuilder.rb
#1330 の準備の一環として、tableメソッドの整理をしました。
- sepidx解析部分はほとんどのビルダで共通なので、Builder#parse_table_rowsを導入
- その後のtrを各処理する部分もほぼ共通なので、Builder#table_trを導入
ただ、latexbuilderやidgxmlなどでどうしても渡したい固有の変数があり、仕方がないのでインスタンス変数を使って渡すようにしているところもあります。
> 各ビルダのtableメソッドのリファクタリング

- lib/review/builder.rb
- lib/review/compiler.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/rstbuilder.rb
- lib/review/topbuilder.rb
* arg `lines` should not have "\n", like other tags
* should not use `LATEXUtils::unescape`; `lines` should not be escaped in `//texeuqation` and `//embed` and `//graph`
>  refactor //texequation, //embed and //graph

- lib/review/compiler.rb
- lib/review/htmlutils.rb
- lib/review/latexbuilder.rb
* highlighting code block should not be escaped, but allowed to use inline markup in.
----
#1371 の続きです。これと合わせると、`unescape()`が廃止されます。
これは、エスケープが必要ないところではcompiler/builderの段階でエスケープされていないようになるものです。
> refactor: remove unescape() in all builders

- lib/review/compiler.rb
- lib/review/htmlutils.rb
- lib/review/latexbuilder.rb
#1376 の修正。
#1374 の修正です。
bindをしないと`@book`が初期化されないので、do_compileのほうにhighlightチェックのロジックを移動しました。
587d4cf76 が原因をアラートしていたのに隠してしまっていましたね…。とりあえずこれはrevertしました。
> @bookが空になっていることによるコンパイルエラーの修正

- doc/config.yml.sample
- doc/pdfmaker.ja.md
- doc/pdfmaker.md
- lib/review/configure.rb
- lib/review/update.rb
- test/test_update.rb
現状の`-interaction=nonstopmode -file-line-error`だと、エラーが出てもとりあえず進んで、でもエラーなので結局異常終了してしまい、原因がずっと上のほうでわからない ということになりがちです。
どうせTeXのエラーになったらRe:VIEWの場合はどうしようもないので、`-halt-on-error`を追加して、エラー即終了にしたいと思います。
```
28] [29] [30] [31] [32] [33] [34] [35] [36] [37] [38] [39] [40] [41] [42]
[43] [44] [45]
./domain.tex:647: LaTeX Error: Counter too large.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
...                                              
l.647 ...otetext[28]{\url{https://radix.website/}}
Output written on __REVIEW_BOOK__.dvi (45 pages, 152988 bytes).
Transcript written on __REVIEW_BOOK__.log.
rake aborted!
Command failed with status (1): [review-pdfmaker config.yml...]
lib/tasks/review.rake:96:in `block in <top (required)>'
Tasks: TOP => pdf => …
```
> PDFMaker: -halt-on-errorオプションをデフォルトに追加

- lib/review/init.rb
#1381 の修正
ついでにreview-initに`-t`ショートオプションも付けることにしました。
> gentombow.styとjsbook.clsはテンプレートがreview-jsbookのときだけコピー

- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/markdownbuilder.rb
- lib/review/md2inaobuilder.rb
- lib/review/plaintextbuilder.rb
- lib/review/topbuilder.rb
- test/test_md2inaobuilder.rb
ref #1330 
https://github.com/kmuto/review/wiki/%E3%83%98%E3%83%83%E3%83%80%E3%83%BB%E3%83%95%E3%83%83%E3%82%BF%E3%81%AE%E3%83%AA%E3%83%95%E3%82%A1%E3%82%AF%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0%E5%AF%BE%E8%B1%A1%E3%81%AE%E6%A4%9C%E8%A8%8E
のheader/bodyが分離できていない/しづらい ところをまとめてリファクタリングします。
- headerは「キャプションのみ」、bodyは「ボディのみ」を作り、それらを囲むものは親(listやtableなど)のほうに書くようにします。
- 表面上は結果に変わりはないはずですが、review-ext.rbで書き換えていた場合はそれなりに影響します。
- md2inaoのリストキャプションはテストのほうが間違っている気がするので修正しました。
> XXX_header, XXX_bodyのリファクタリング

- lib/review/book/base.rb
- lib/review/book/chapter.rb
- lib/review/book/part.rb
- test/test_book.rb
`Chapter`や`Part`のコンストラクタを`Book::Base`から各クラスに移動させるものです。
> refactor: move mkchap* and mkpart* into Chapter and Part

- lib/review/configure.rb
- lib/review/epubmaker.rb
- lib/review/yamlloader.rb
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
- test/test_yamlloader.rb
いくつかのイレギュラーパターンについて、ランタイム例外エラーを出す前に対処するようにしました。
- YAMLファイル異常は基本的にYAML.load時点の例外捕捉で対処できるのですが、「空」(YAMLエントリがないを含む)だったときにはYAML.loadでは捕捉できず、`deep_merge` の時点でFalseClassだったとしてランタイムエラーになります。FalseClassだった場合にはerrorメソッド経由でエラー終了させるようにしました。
- CSSをコピーしようとするときにファイルが存在しないとランタイムエラーになります。ファイルが存在しなかったときにはエラー終了させるようにしました。
デフォルト値の変更
- aut抜け：TeXコンパイル時にnilのエラーが発生するので、autのデフォルトを`["anonymous"]`としました。
- booknameのデフォルト: 通常のreview-initで作るconfig.ymlに合わせてexample→bookとしました。
- texstyleのデフォルト: 空だったのを`["reviewmacro"]`としました。
- ~stylesheetのデフォルト: 通常のreview-initで作るconfig.ymlに合わせてstylesheet.css→`["style.css"]` としました。~
- stylesheetのデフォルト: 上記はわかりづらいのでデフォルトは`[]`にしました。
> エラーチェックおよびデフォルト値設定

- templates/latex/review-jsbook/review-style.sty
#1385 の対応
後方互換性は若干失われますが、てくぶスタイルではもともとHを使っているし、影響範囲はかなり限定と思います。
> PDFMaker: review-jsbookでのtableの設置設定をhtpからHにする

- templates/latex/review-jlreq/review-base.sty
#1392 の修正。
specialマクロで定義すると異常なPDFを作ってしまうため、LuaLaTeXの場合はhyperrefの機能によるメタ情報記述を使うようにする。
副作用として、hyperrefはprintモードではdraftオプションが付記されるためメタ情報も記述されない。ebookモードのときのみメタ情報が付くことになる。(upLaTeXの場合は従来どおりどちらでもメタ情報が入る)
> PDFMaker: LuaLaTeX利用時にはPDFメタ情報をhypersetupで定義する

- templates/latex/review-jlreq/review-jlreq.cls
#1395 のワークアラウンドです。
なお、
ちゃんとやるにはjlreqtrimmarkssetupを呼び出して適切に位置設定すべきですが、review-jsbookのやり方と全然違うので、互換性や実装方法などが難しい。
とりあえず現時点で手をつけられる状況にはないです。
> 新しいjlreq.clsで偶数ページでのhiddenfolioが消えるのを修正

- lib/review/pdfmaker.rb
https://twitter.com/masarakki/status/1175918201936347137 の発端から
`pdfmaker#generate_pdf`を眺めていたらyamlfile依存なしにできました。
- `generate_pdf` がyamlfileを使っていた理由の1つは作業フォルダの位置ですが、これは`@basedir`ですでに格納済み。
- もう1つは `make_input_files` に渡していたもの。
- `make_input_files` は `output_chaps` に渡すために取っていた。
- が、`output_chaps` ではもうyamlfileは不要だった。
> generate_pdfのyaml依存を除く

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jlreq/review-style.sty
- templates/latex/review-jsbook/review-base.sty
- templates/latex/review-jsbook/review-style.sty
後方互換性を壊すんですが、
コードリスト内の和欧アキが1/4アキままなのは普通は意図しないはずなので、アキ0(`\z@`)にするのをデフォルトにしたいと思います。
設定はマクロ化しておいたので、review-style.styでreviewlistxkanjiskipの設定をコメントアウトすればデフォルトのアキに戻ります(必要なら別のskip値にすることも)。
> PDFMaker: set xkanjiskip zero in list environments.

- doc/config.yml.sample
- lib/review/configure.rb
- templates/latex/config.erb
- templates/latex/layout.tex.erb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/review-base.sty
- templates/latex/review-jsbook/review-jsbook.cls
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
デフォルトの状態だとノンブル文字列は
```
表紙 1
白 2
大扉 i
…
```
になるのですが、これを
```
表紙 cover
大扉 i
…
```
となるようにします。大扉は奇数でなければならない都合で、表紙は偶数(p.2)としています。
後方互換性を壊すことにはなります。
表紙込みで入稿するというやり方をしている場合だと問題になるかも。クラスパラメータで持ったほうがよい？
> 表紙のノンブルをcoverに変更し、利便性のために偶数ページにしておく

- lib/review/init-web/finish.html
- lib/review/init-web/index.html
- lib/review/init-web/review-layout-design.js
- lib/review/init.rb
review-initに`-w`(および変更用に`--bind`と`--port`)を付けることで、ブラウザ上でのレイアウトを可能にします(CreateJSを使っています)。
見た目を今風にしたりReactあたりを使ったツールチップとかもできるといいんですが、あまりそのあたりのセンスが自分にはないので、得意な方からのパッチを待ちたいと思います。
> Webブラウザ上での初期レイアウト作成

- test/test_htmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_markdownbuilder.rb
- test/test_md2inaobuilder.rb
suppress warnings running in tests:
```console
WARN run_test: :0: Definition list starting with `:` is deprecated. It should start with ` : `.
```
> fix syntax of dlist in testcases

- templates/latex/config.erb
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
#1414 の対応
`@ifundefined` の代わりに `\ifdefined\マクロ\else` でテストするようにします。
> use ifdefined-else for backward compatibility check

- samples/syntax-book/config-jlreq-lualatex.yml
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jlreq/review-jlreq.cls
#1416 の修正。
`\setxkanjiskip{値}`で抽象化します。とりあえず把握している範囲として、lualatexとそれ以外、としています。
> introduce setxkanjiskip Closes: #1416

- doc/config.yml.sample
- doc/config.yml.sample-simple
contactパラメータとか、colophon_orderとかをせっかく用意していたのに、ドキュメント化していませんでした。
YAMLコメントがいっぱいある中から拾うのがそろそろ苦痛になりそうですが、ひとまず追加しておきます。
> 奥付の「連絡先」および「順序」についてコメントを追加

- lib/review/idgxmlbuilder.rb
idgxmlbuilderの表まわりのリファクタリングをした際に、警告表示時に使うID情報の変数がなくなったので渡せていませんでした。
引数にするとほかのビルダのメソッド全部に影響してしまうので、別途変数を使って引き渡します。
> IDGXML: pass table id to table_rows to use for warning

- lib/review/idgxmlmaker.rb
IDGXMLの場合フィルタによってはめちゃくちゃ時間がかかって、多数のファイルがある状況だと大変なので、-y/--onlyオプションでファイル名かファイルIDを指定したら、そのファイルだけをビルドするようにします(,区切り可)。
> IDGXML: introduce -y/--only option to specify target re files.

- lib/review/idgxmlmaker.rb
IDGXMLMakerでフィルタにエラーがあったときにエラー表示する変数に誤りがありました
> IDGXML: fix handling filter error message in maker

- .rubocop.yml
- lib/review/template.rb
rubocopで警告が出てたので確認したところ、
> Ruby 2.6.0 から位置引数での safe_level, trim_mode, eoutvar の指定は非推奨です。 Ruby 2.5 が EOL になったときに削除される予定です。 trim_mode と eoutvar の指定はキーワード引数に移行してください。
https://docs.ruby-lang.org/ja/latest/class/ERB.html
とのことだったようです。
> fix rubocop warning (ERB.new)

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
#1432 の対応
\reviewbreakall のhyperref対応が現状すぐにできるか不明なため、段落間分割をあきらめて書体変更のみを行うようにします。
> PDFMaker: revert tt,code,tti, and ttb temporary.

- samples/sample-book/src/config-ebook.yml
- samples/sample-book/src/config-jlreq-ebook.yml
- samples/sample-book/src/config.yml
- samples/syntax-book/ch02.re
- samples/syntax-book/config-print.yml
- samples/syntax-book/config.yml
- test/test_epubmaker_cmd.rb
- test/test_helper.rb
- test/test_pdfmaker_cmd.rb
コンパイラがある環境では、rake test時にいろいろな設定でのPDFビルドを実際に行い、確かにビルドできることを確認するようにします。
また、見出しに等幅などのいくつかの命令を追加し、よりエラーを発見しやすいようにします。
で、実際 #1432 で手元でコケますね…
> compile PDF in test phase exactly

- lib/review/pdfmaker.rb
#1418 の修正です。
コンパイル回数を増やし、makeindexが有効なときに索引を目次に含めるようにします。
llmkがフツーに使えるようになるなら、それを使うようにビルドを変えられるかなぁ。ただフックとかを入れづらそう。latexmkはPerl必須なので、抵抗がある…。
> needs one more compile when makeindex is true

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
#1432  についていったん諦めていましたが、@munepi さんの解決方法
```
\g@addto@macro\pdfstringdefPreHook{%
\def\reviewbreakall#1{#1}}
```
の追加でうまくいきそうです。
> revival breakall tt

- doc/config.yml.sample
- lib/review/builder.rb
- lib/review/configure.rb
- lib/review/idgxmlbuilder.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_topbuilder.rb
#1420 の対処です。
正規表現でセル区切り文字を変えられるようにするパラメータ `table_split_regexp` を導入します。
> add table_split_regexp parameter to specify splitter of //table

- lib/review/idgxmlmaker.rb
フィルタ実行時、stderrに何らかの内容があるときには、最終的に成功でもエラーでもともかくWARN loggerに出力するようにします。
(としておかないと、フィルタのprintデバッグがしづらい)
> IDGXMLMaker: print stderr messages from filter program

- lib/review/latexbuilder.rb
mebabがいないときに`rake test`でコケるようです。
```
INFO review-pdfmaker: compiling pre01.tex
WARN review-pdfmaker: compile error in pre01.tex (ReVIEW::ApplicationError)
WARN review-pdfmaker: pre01.re:0: error: not found MeCab
INFO review-pdfmaker: compiling ch01.tex
WARN review-pdfmaker: compile error in ch01.tex (ReVIEW::ApplicationError)
WARN review-pdfmaker: ch01.re:0: error: not found MeCab
INFO review-pdfmaker: compiling part2.tex
WARN review-pdfmaker: compile error in part2.tex (ReVIEW::ApplicationError)
WARN review-pdfmaker: part2.re:0: error: not found MeCab
INFO review-pdfmaker: compiling ch02.tex
WARN review-pdfmaker: compile error in ch02.tex (ReVIEW::ApplicationError)
WARN review-pdfmaker: ch02.re:0: error: not found MeCab
INFO review-pdfmaker: compiling ch03.tex
WARN review-pdfmaker: …
```
> enable to build without mecab

- doc/config.yml.sample
- lib/review/builder.rb
- lib/review/configure.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_topbuilder.rb
@takahashim 
`table_splitter_regexp`を廃棄し、定義済み名のみをとる`table_splitter`を導入します。パターンはこの4つあればよかろうという判断です。
- tabs : デフォルト。\t+に展開
- singletab: \tに展開。「tab」だとtabsと区別しづらいので…
- spaces: \s+に展開
- verticalbar: \s*\|\s*に展開
> introduce table_splitter to choose predefined splitter regexp

- doc/config.yml.sample
- lib/review/builder.rb
- lib/review/configure.rb
- lib/review/idgxmlbuilder.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_topbuilder.rb
まだリリースしてないし、@takahashim さんアドバイスに基づいてパラメータ名を変更します。
> rename parameter from table_splitter to table_rows_splitter

- lib/review/init.rb
何か機能追加の試行錯誤のためにreview-initでconfig.ymlを作るとき、コメントがちょっと邪魔なことがあるので、#と空行を取るオプションをreview-initに追加します。
> add --without-config-comment option to review-init

- lib/review/book/base.rb
- lib/review/book/index.rb
現状のChapterIndexの中身はItemではなくChapterオブジェクトだったため、他のIndexと挙動を揃えるとエラーが発生してしまうのを修正するものです。
> items of ChapterIndex should be Index::Item

- lib/review/extentions/string.rb
- test/test_index.rb
`src` in `FooIndex.parse(src)` should be `Enumerable` in compilable.rb.
> remove String#each

- doc/config.yml.sample
- lib/review/compiler.rb
- lib/review/configure.rb
- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
#1461 の対応
`pdfmaker/use_original_image_size` がtrueのとき、かつmetricsに何も指定がないときに、reviewincludegraphicsには空白文字1つが渡るようになる。デフォルトはnil。
(完全に空だとimageメソッド内などで`present?`判定でfalseになってしまうので、TeX側には意味はないがRubyロジック側には意味がある文字として空白文字を採用した。ロジック側を直すのは副作用がいろいろありそうなので…)
> PDFMaker: introduce pdfmaker/use_original_image_size parameter to disable an automatic image scaling

- lib/review/configure.rb
- lib/review/latexbuilder.rb
- lib/review/pdfmaker.rb
- test/test_latexbuilder.rb
- test/test_latexbuilder_v2.rb
#1462 の対応
古い直下image_scale2width パラメータがあればWARNを出しつつそれを採用するようにしています。
> move image_scale2width parameter to under pdfmaker section

- samples/syntax-book/ch02.re
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
#1432 のヒントをもとに、さらに見出しで使われるとPDFしおりが変になるかビルド失敗するインラインマークアップについて、引数ママの文字になるようにしました。
reviewami, reviewballoon, reviewbou, reviewstrike, reviewunderline。
> PDFMaker: strip some inline markups in PDF bookmark

- lib/review/pdfmaker.rb
索引作成を有効にした設定で実際に索引タームの登録がないと、makeindexに失敗してエラー終了してしまいます。
存在(`exist?`)チェックで見ていましたが、実際には0バイトファイルができてしまってやはり失敗していたので、`size?`で見るように変更します。
> PDFMaker: check idx isn't empty before calling makeindex

- lib/review/epubmaker.rb
- lib/review/pdfmaker.rb
- lib/review/textmaker.rb
- lib/review/webmaker.rb
- samples/sample-book/src/lib/tasks/review.rake
- samples/syntax-book/lib/tasks/review.rake
- test/test_pdfmaker_cmd.rb
idgxmlmakerでは`-y ch1,ch3,..` のようにして実際に生成するXMLファイルを選択できるようになっていますが、ある特定の章だけをビルドしたいという需要はそれなりにあるので、同様にEPUBMaker、WEBMaker、PDFMaker、TEXTMakerにも-yオプションを導入します。
-y(または--only)オプションは,区切りで、〜.reまたは〜 の箇所を指定し、指定ファイルだけをビルドします。大扉や目次、奥付などのreによらない自動生成物はそのまま生成されます。
rakeを使うときには`REVIEW_PDF_OPTIONS`, `REVIEW_EPUB_OPTIONS`, `REVIEW_WEB_OPTIONS`、 `REVIEW_TEXT_OPTIONS` という環境変数からコマンドラインオプションを取るようにして、
```
REVIEW_PDF_OPTIONS="-y ch01" rake pdf
```
のような呼び出しができます。
> 章を選択してビルド実行できるようにする

- .github/workflows/ruby.yml
#1444 の代わりに https://github.com/eregon/use-ruby-action を使って2.7に対応するものです。
> use eregon/use-ruby-action instead of actions/setup-ruby

- lib/review/pdfmaker.rb
#1464 で`image_scale2width`が直下にあるかどうかを調べていたつもりだけれど、@configは単なるHashじゃなくてConfigureクラスオブジェクトで、聞かれたら直下にあるかのように答えるよう細工しているので意味がなかった。
> revert image_scale2width warning, part of #1464

- lib/review/epubmaker.rb
#1474 の修正
EPUBmakerにおいて、見出しが1つもなくてドロップされる場合は`=[notoc]`か`=[nodisp]`を使うよう警告します。
> warn when there is no heading

- lib/review/compiler.rb
- lib/review/latexbuilder.rb
- samples/syntax-book/ch01.re
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_topbuilder.rb
#1476 の対処
`: foo@<fn>{bar}`をPDFMakerで入れると、`\item[foo\footnote{bar}]` に展開されてしまい、脚注内容が消えてしまう。
そのため、
- コンパイラでLATEXBuilderのときのみ、dtのtext囲みをしない(`compile_inline`を遅らせる)。コンパイラにビルダ固有判定が入るのは業腹だが、LATEXBuilder固有なのに全ビルダのdtに手を入れるというのも本末転倒という判断です。
- LATEXBuilderのdt内では、captionモードにしてから`compile_inline`を実施する。こうすることで、dt内のfootnoteはfootnotemarkになります。
- `[`と`]`のlbrackとrbrackへの置き換えがなぜかこれまではsubで1回しか実行していなかったので、gsubにして全部に適用するように。数式内で`[]`が使われた場合…を考えたんですが、箇条書き見出しでリテラルにそう表示する以外にはフツーはなさそうなので、かまわず同じように置換するようにしました。本当にまじめにやろうとするとパーサが必要そうです。
> support footnote in description title

- lib/review/compiler.rb
#1499  の修正です
- `do_compile` で重複定義していた `@non_parsed_commands` を削除し、`initialize`側のみを有効に
- `do_compile` で定義していた `@non_escaped_commands`(ハイライト有効時にエスケープしないもの) は、highlight判定の前にbindされないとダメなので、`initialize`には置けない。highlight判定および非エスケープ対象タグシンボルの配列を返すメソッド `non_escaped_commands` を用意し、これを呼び出すように変更。これで、もし書き換えたいときには `do_compile` 全体ではなくこのメソッドだけをオーバライドすればよい
> remove duplicated @non_parsed_commands definition

- lib/review/textmaker.rb
- lib/review/webmaker.rb
#1489 で、数式の効率化をしたはいいが、判定ファイル名を変えたのをEPUBMakerしか修正反映していなかった。
textmaker, webmakerにも反映。
> webmaker,textmakerが数式画像を作り忘れているのを修正

- test/test_helper.rb
テストユニットのprepare_samplebookではsamplesのフォルダを丸ごとtmpdirにコピーしますが、samples内で手作業でdebugモードなどで作成したbook-pdf・book-epub・book-text・webrootもコピーされてしまい、特にPDFMakerではテストに失敗します。
丸ごとコピー前に、明確にデバッグフォルダとわかっている上記のものをコピー対象から除くようにします。
> テストユニットでsamplesをコピーする際にビルド成果物をスキップ

- .rubocop.yml
`rubocop-performance 1.6.1` で警告が出るので抑制します。
> fix rubocop settings

- lib/review/configure.rb
- templates/latex/config.erb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
- test/test_pdfmaker.rb
#1517 への対応
対処していたはずなのにおかしいな、と思っていたのですが、autを空にするといった特定条件だとmetachars定義が初期化されず、escapeメソッドで使おうとしてエラーになっていました。config.erbでまず初期化するように変更しました。
また、autのデフォルトをanonymousではなく空(null)にしました。
PDFプロパティを空autに対処するため、review-base.styも更新しています。
> aut値が空のときにPDFMakerがエラーになることの対処

- bin/review-compile
- lib/review/compiler.rb
ReVIEW::Compiler にある `@strategy` が実はBuilder、という混乱の元を解決します。
`Compiler#strategy` は現状ではerrorにしてますが（不具合の早期検出のため）、リリース時にはwarnにしても良いかもです。
> refactor: rename strategy to builder

- templates/latex/review-jlreq/review-jlreq.cls
#1397 の対応
review-jsbookとはちょっと見た目が違いますが、もともと隠しノンブルだし、目的の解決としては同じなのでよしとします。以下右ページだとして、
- hiddenfolio=default: review-jsbookだとノド側トンボの左上、横書き。review-jlreqにおいてはノド側トンボの右上、横書き。
- hiddenfolio=nikko-pcほか: review-jsbookだとノド側中央・版面内、縦並べ。review-jlreqにおいてはノド側中央・版面内、倒した形で横並べ。
> use jlreqtrimmarkssetup instead of own logic

- lib/review/pdfmaker.rb
- templates/latex/config.erb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
#1483  の対応
LaTeXで画像のバウンディングボックスを取るのに使っているextractbbですが、TeXLive2015以降では内部で呼び出されるので不要そうなのと、#1483 のとおり拡張子以外同名のときにおかしなことになるので呼び出しコードを削除します。
これに伴い、pdfmaker/bboxの設定は、config.erb経由でreview-base.styに渡し、graphicx.styのデフォルト値を変えることで対処するようにしています。
> extractbb明示呼び出しの廃止と、bbox設定の引き渡し

- test/test_makerhelper.rb
最近のDebian ImageMagickの更新で、ghostscriptの呼び出しはデフォルトのポリシーでdenyに変更されていました(セキュリティ上の理由)。そのため、テストに必ず失敗します。
ポリシーファイルを変更すれば継続して利用はできるのでMakerHelperのコードは残しますが、テストからは除外しようと思います。
> test_copy_images_to_dir_convertテストを削除

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
//indepimageで画像がないときに
```
//indepimage[sample_img#&]
↓
\\begin{reviewdummyimage}
--[[path = sample_img#& (not exist)]]--
\\reviewindepimagecaption{図: sample photo}
\\end{reviewdummyimage}
```
という展開をしますが、IDをそのまま渡していたので`_`などのリテラルに使えない文字がID内にあるとコンパイルエラーが発生していました。
単純に出力前にエスケープすることにします。
> escape indepimage warning string

- doc/config.yml.sample
- lib/review/configure.rb
- lib/review/htmlbuilder.rb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_latexbuilder_v2.rb
#1529 #1530 の対応です。
- chapterlinkをデフォルトでtrueにしました。
- config.yml.sampleにドキュメント追加しました。
- chapterlink on/off時のテストを追加しました。
- hdインライン命令をLaTeX展開したときのreviewsecrefで、hyperrefを有効にしました。
- 厳密にはchapterlinkとは別の話なんですが、columnインライン命令で別ファイルを参照してもちゃんと動いていなかったので、chapter/idをちゃんと分解してchapterのhtmlを参照するようにしました。
- pdfmakerにおいては、media=printの場合はhyperrefパッケージのオプションでハイパーリンク機能を殺しているので変化はなし。media=ebookの場合はhdインライン命令の箇所がリンクになります。図表・リスト・式のほうはリンクにはしていません(やろうとするとちょっと面倒くさそう)。
LaTeXのreviewcolumnrefのほうは、hyperrefを入れてもうまく動いてくれませんでした。どうもreviewcolumnheadに渡しているhypertargetのほうが無視されてラベルとして見つからないっぽい？ とりあえず今は必須というほどではないので対処から見送っています。
> chapterlinkをデフォルトで有効にする

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
#1533 の対応。
media=ebook (hyperref有効)のときにはhypersetupでPDFメタ情報を記載するようにしました。
media=print + upLaTeXのときはエスケープが変に出るのは諦めてpdf:docinfoへの生記述を使い続けます(media=print+LuaLaTeXのときは何も入らない)。
> prefer hypersetup for pdf information

- templates/latex/review-jlreq/README.md
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/README.md
- templates/latex/review-jsbook/review-base.sty
- templates/latex/review-jsbook/review-jsbook.cls
#1534 の対処。
config.ymlパラメータでやるのはやっぱりちょっと嫌なので、review-jsbook/review-jlreqのクラスファイルオプションにしました。
`cover_fit_page=true`のときに縦横比無視で仕上がりサイズに拡縮貼り付けします。
> cover_fit_pageクラスオプションの追加

- test/test_idgxmlmaker_cmd.rb
- test/test_latexbuilder.rb
- test/test_textmaker_cmd.rb
テストで標準エラーにWARNを出してしまうものがあり、取り込む or 捨てる で対処しました。
> mute some stderr outputs in tests

- test/test_idgxmlmaker_cmd.rb
- test/test_textmaker_cmd.rb
テストのSTDERR挙動をいくぶん戻してみました。
idgxmlmaker_cmd, textmaker_cmdはstderrが空であることを期待。
pdfmaker_cmdは今のところ必ずINFO等が出てしまうので前のとおりs.success以外のときにSTDERR.putsするだけ。
idgxmlmaker,textmakerもpdfmaker同様にしたほうがいいかなぁ。
> check stderr output from textmaker/idgxmlmaker is empty

- lib/review/book/book_unit.rb
- lib/review/book/chapter.rb
- lib/review/book/part.rb
`BookUnit` is (abstract) superclass of `Chapter` and `Part`.
> add BookUnit class instead of Compilable module

- lib/review/webmaker.rb
- templates/web/html/layout-html5.html.erb
#1545 の修正
普通のページはHTMLBuilderの働きで `@title` が入るのだけど、
- WebMaker固有で作っているindex, titlepage, part(文字列のみしかない部)については`@title`を定義していなかった。これにより、最初のindexのところでnilをエスケープしようとしてエラーになっていた。
- HTMLBuilderが作る `@title`はエスケープ済みだが、templates側でエスケープして二重になっていた
> set title to auto built page

- lib/review/book/chapter.rb
- lib/review/tocprinter.rb
- lib/review/volumeprinter.rb
- test/test_book_chapter.rb
#1544 の対処です。
UTF-8以外のエンコーディングファイルを読み込もうとした時点でArgumentErrorが発生するので、その発生箇所でReVIEW::CompileErrorを出し、ツール側ではそれを捕捉するようにしました。
> handle invalid encoding

- bin/review-compile
- lib/review/book.rb
- lib/review/book/base.rb
- lib/review/epubmaker.rb
- lib/review/idgxmlmaker.rb
- lib/review/pdfmaker.rb
- lib/review/textmaker.rb
- lib/review/tocprinter.rb
- lib/review/volumeprinter.rb
- lib/review/webmaker.rb
- test/book_test_helper.rb
* `ReVIEW::Book.load` is deprecated, use `ReVIEW::Book::Base.load` or `ReVIEW::Book::Base.new`
* add new option `:config` for `ReVIEW::Book::Base.load`
> remove ReVIEW::Book.load, modify ReVIEW::Book::Base.load

- lib/review/book/base.rb
- lib/review/catalog.rb
- test/book_test_helper.rb
- test/test_book.rb
* add `Base#parse_catalog_file()` and use it in `ReVIEW::Book::Base.new()`.
`Base#catalog` is just getter now.
* fix some tests because timing of parse config.yml and catalog.yml are changed.
> parsing catalog.yml is not lazy

- lib/review/book/base.rb
- lib/review/book/bib.rb
- lib/review/book/book_unit.rb
- lib/review/book/chapter.rb
- lib/review/book/index.rb
- lib/review/book/part.rb
- lib/review/index_builder.rb
- lib/review/latexbuilder.rb
- lib/review/sec_counter.rb
- test/test_helper.rb
`ReVIEW::Book::Index.parse`を全面的に置き換えるものです。
インデックス専用のbuilderを作って何とかする作戦です。
> use IndexBuilder instead of *Index.parse()

- bin/review-compile
- lib/review/converter.rb
- lib/review/init.rb
- test/test_book.rb
- test/test_epub3maker.rb
- test/test_htmlbuilder.rb
- test/test_i18n.rb
- test/test_pdfmaker.rb
> use File.write

- lib/review/builder.rb
- lib/review/compiler.rb
- lib/review/index_builder.rb
minicolumnの定義にはblockの定義とは別のメソッドを使うようにして、後から追加しやすくするものです。
> add defminicolumn

- bin/review-check
- bin/review-compile
- lib/review/book.rb
- lib/review/epubmaker.rb
- lib/review/idgxmlmaker.rb
- lib/review/pdfmaker.rb
- lib/review/textmaker.rb
- lib/review/tocprinter.rb
- lib/review/volumeprinter.rb
- lib/review/webmaker.rb
- test/book_test_helper.rb
- test/test_book.rb
- test/test_builder.rb
- test/test_htmlbuilder.rb
- test/test_webtocprinter.rb
> use Book::Base.new (with :config) instead of Book::Base.load

- lib/review/builder.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- test/test_review_ext.rb
When you want to do something in `*Builder.new`, define the method `initialize` and use `super` in it.
> remove a method `Builder#builder_init()`

- lib/review/book/index/item.rb
- test/test_htmlbuilder.rb
path characters: `A-Z` + `a-z` + `0-9` + `_:=+-()|`
> do not allow tricky id used as path; fix #1393

- lib/review/markdownbuilder.rb
- test/test_markdownbuilder.rb
Markdownのcaptionblock内で、paragraphを（改行区切りではなく）空行区切りに修正します。
> markdown: paragraph separator should be empty line

- lib/epubmaker/content.rb
- test/test_epubmaker.rb
#1574 の対応
EPUBのほうでのitem IDまわりでの文字についてはCGI.escapeを使ったエスケープをするようにします。
> escape unsafe character in EPUB ID

- lib/review/compiler.rb
fix #1591
見出しレベルの上限を6にして、それより大きい場合はparserでエラーにするようにしてみました。
> define MAX_HEADLINE_LEVEL as 6

- lib/review/book/chapter.rb
- lib/review/compiler.rb
- lib/review/lineinput.rb
- test/test_lineinput.rb
#1596 の対処です。
TAB, LF, CR以外のASCII制御コード文字はUTF-8ドキュメント内で登場することはないはずなので、読み込み時に発見したらエラーにします。
例外はSyntaxErrorを使うことにしました。
> 意図しない制御コード文字をエラーにする

- lib/review/pdfmaker.rb
PDFMakerのafter_makeindexフックは、mendex実行のあとにind書き換えをするために呼び出すものなのに、コンパイルが走ってしまってから呼び出す形になってしまっていました(これでは修正が効かない)。
mendex実行後すぐに呼び出すように変更します。
> call after_makeindex hook just after running mendex

- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/review-jsbook.cls
#1607 の対応
おおむねこの設定で脚注が別れることはないはず。たくさんあったりすると挙動が変になるかもしれないが、それはかなり特殊な文章ということで自分で設定を直してもらう…。
> 脚注が泣き別れしないようにする

- lib/review/volumeprinter.rb
#1604 の対応
ApplicationErrorをreview-volで回収するようにします。
> rescue Application Error in review-vol

- test/test_htmlbuilder.rb
pygments.rbは中でPythonを呼び出す都合で、CIでのビルドタイミングによって奇妙なエラーが発生しやすい模様。
CI実行時だけ動かさないという方法がわからないが、このままだとともかく困るのでとりあえず実行スキップで実装。
> pygmentsのテストをスキップ

- bin/review-compile
- lib/review/configure.rb
and apply this migration to command line options
`--mathml` オプションなどもあったので、`migrate_parameters` は最後に行うのが正しいようでした。
> migrate_parameters should be an instance method

- lib/epubmaker.rb
- lib/epubmaker/content.rb
- lib/epubmaker/producer.rb
- lib/review/epubmaker.rb
- test/test_epub3maker.rb
- test/test_epubmaker.rb
- test/test_htmlbuilder.rb
initializeの引数を、パラメータ列挙から名前付きに変更する。
> EPUBMaker.Contentのリファクタリング

- lib/review/webmaker.rb
#1623 の対応
pdfmaker.rbなどと同様に`@converter`の定義位置を変更して期待の動作になりました。
> fix to find html/ directory correctly in webmaker

- lib/review/latexbuilder.rb
- samples/syntax-book/ch02.re
- templates/latex/config.erb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
#1619 の対応です。
[]があるとエスケープされちゃうので、chap, title, chaprefに`\reviewchapref`を使うようにしました。
互換性のためにconfig.erbで未定義(review-base.styが古い)のときには暗黙に定義するようにもしています。
> introduce reviewchapref to avoid escaping in dt

- doc/format.ja.md
- doc/format.md
画像探索の際に各Makerで使うビルダ名フォルダについてドキュメントに追加します。
ref #1623
> add note about maker's builder name folder

- lib/review/configure.rb
- lib/review/tocprinter.rb
- lib/review/volumeprinter.rb
#1633 の修正。
`ReVIEW::Configure.create`で設定を作り、それをBookに渡すというやり方に統一しました。
これでcontentdirなどでエラーになる問題は修正できています。
> webmaker, review-vol, review-indexのパラメータ値取り込み方法を修正

- lib/epubmaker/producer.rb
- lib/review/configure.rb
- lib/review/epubmaker.rb
- test/test_epub3maker.rb
- test/test_epubmaker.rb
EPUBMaker::ProducerだけconfigがほかのMakerと持ち方が違っている件をまずは修正します。
- EPUBMaker::Producer固有で持っていたパラメータをReVIEW::Configureに移動しました
- YAMLロードもReVIEW::Configureに任せるようにしました。
- EPUBMakerに入れていたdeprecatedチェックは意味がないので削除しました。
> move EPUB config to ReVIEW::Configure

- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/review-jsbook.cls
#1644 の対応です
クラスの最初で読み込むようにしました。
> add plautopatch

- lib/epubmaker/epubcommon.rb
- lib/epubmaker/epubv2.rb
- lib/epubmaker/epubv3.rb
- lib/review/epubmaker.rb
- lib/review/pdfmaker.rb
- lib/review/template.rb
- lib/review/webmaker.rb
- test/test_template.rb
Template関連を`ReVIEW::Template.generate`というメソッドで統一してみました。
> add ReVIEW::Template.generate

- lib/epubmaker/epubcommon.rb
- lib/epubmaker/epubv2.rb
- lib/epubmaker/epubv3.rb
- lib/epubmaker/producer.rb
- lib/review/call_hook.rb
- lib/review/epubmaker.rb
- lib/review/pdfmaker.rb
`call_hook`の実装が分散していた（そしてちょっとずつ異なっていた）ので、まとめてみます。
EPUBMakerに元々のコンテンツのディレクトリを渡すしくみがなかったので、そこを追加しています（`base_dir`）。
> Unify call_hook

- lib/review/epubmaker/epubv3.rb
`Metrics/CyclomaticComplexity`を減らすためのリファクタリングで、メソッドを分解しています。
> refactor: extract opf_metainfo

- .rubocop.yml
- lib/review/idgxmlbuilder.rb
- test/test_idgxmlbuilder.rb
`</sect>`タグを出力する部分をメソッドに分解してシンプルにしてみました。ついでにテストも追加しています。
これで `Metrics/CyclomaticComplexity`が減らせました。
> refactor: extract headline in IDGXMLBuilder

- lib/review/epubmaker.rb
- templates/html/_part_body.html.erb
- test/test_epub3maker.rb
partのHTMLファイルをテンプレート化します。
テストも追加しておきました（実装はだいぶマズいというか、APIが足りてない…）
> EPUBMaker: use template in build_part

- doc/config.yml.sample
- doc/config.yml.sample-simple
- lib/review/configure.rb
- samples/sample-book/src/config-epub2.yml
- samples/sample-book/src/config.yml
`uid`は別のところで使われるもので、このURNでは普通に`uuid`で良いようでした
> urn:uid -> urn:uuid

- lib/review/epubmaker.rb
- lib/review/idgxmlmaker.rb
- lib/review/logger.rb
- lib/review/pdfmaker.rb
- lib/review/textmaker.rb
- lib/review/webmaker.rb
- review.gemspec
- test/test_idgxmlmaker_cmd.rb
- test/test_textmaker_cmd.rb
#1660 の対応
tty-loggerは基本的にラベル部分しかカラーリングは付かないのかな。
リダイレクトすると普通に黒くなります。
寂しいので成功したときにはSUCCESSを出すようにしました。
外部gemはあくまでおまけというポリシーなので、tty-color gemが見つからないときにはこれまでどおり普通のLoggerを使うようにしています。
> tty-loggerによるログの色付け

- README.md
- doc/quickstart.ja.md
- doc/quickstart.md
- samples/sample-book/src/lib/tasks/review.rake
vivliostyle-cli https://github.com/vivliostyle/vivliostyle-cli がインストールされている環境において、
- rake vivliostyle:build (または rake vivliostyle) →PDFを作成
- rake vivliostyle:preview →プレビューを開く
のルールを実行できるようにしました。
具体的にはEPUBを普通に作ったあと、vivliostyleに食わせてPDFかプレビューを作ります。
環境変数は以下のとおりです。
- `REVIEW_VSBIN`: vivliostyleコマンドのパス(PATHが通ってない場合用)
- `REVIEW_VSBIN_USESANDBOX`: とりあえずLinuxだと`--no-sandbox`付けないと変なクラッシュになるので、デフォルトでそれを使います。この変数に値が何か入ってるときには`--no-sandbox`付けをやめます。
- `REVIEW_VSBIN_OPTIONS`: それ以外に何かオプションを付けたいとき用
- `REVIEW_VSBIN_PDF`: 出力ファイル名。デフォルトはpdfmakerと同じくBOOK+`.pdf`。
> Vivliostyleビルドルール

- lib/review/latexbuilder.rb
- test/test_htmlbuilder.rb
- test/test_latexbuilder.rb
#1666 の修正
`//image[ID][]{` のように指定されたときにエラーになるのを防ぎます。
キャプションなしにしてしまうことも考えましたがそういう用途にはindepimageがあること、「図X.Xだけで説明なし」というケースは手元だとけっこう多いことから、空文字列をそのまま使うことにしました。
なお、これでとりあえず#1666を直しますが、ビルダ間や表/リスト/図でキャプションなしのときの出力が若干違うのは迷うので、そのあたりは別PR立てて直したいところではあります。
> PDFMaker: キャプション文字列が空のときには採番あり・説明なし のキャプションにする

- lib/review/epubmaker.rb
- lib/review/epubmaker/epubcommon.rb
- test/test_epubmaker.rb
EPUBでauthorなど外部ファイルをコピーする前にファイルが存在するかどうかのチェックに甘いところがありました(例外が発生してしまっているものがあった)。
頻出するのでメソッドにまとめています。
テストコードを書くつもりです。
> EPUBの差し込み静的ファイルの存在チェック

- NEWS.ja.md
- NEWS.md
- lib/review/version.rb
- review.gemspec
@takahashim 
あとは27か28あたりにリリースよろしくお願いします、でよいでしょうか。
(今月は29がないですね)
news510ブランチから継承させています。
debian.orgアドレスはもう使えないのでpandoc2reviewと同じくkmuto.jpアドレスにしました。
> Release 5.1.0

- lib/review/pdfmaker.rb
This reverts commit 6044bda84f9b84c9c423c06d5308333524a9b8b2.
エラーが出たので戻します。
> Revert "fix to avoid useless Error"

- lib/review/template.rb
Re:VIEWありがたく使わせていただいております。
いつもはプロジェクト直下で npm run pdfしているのですが、たまたま articles 以下で rake pdf したところ warningが出ていることに気がつきました。
```Shell
% rake pdf
review-pdfmaker  config.yml
ℹ INFO    compiling preface.tex    
ℹ INFO    compiling introduction.tex
ℹ INFO    compiling hardware.tex   
ℹ INFO    compiling firmware.tex   
ℹ INFO    compiling software.tex   
ℹ INFO    compiling bib.tex        
ℹ INFO    compiling contributors.tex
/opt/homebrew/lib/ruby/gems/3.0.0/gems/review-5.1.1/lib/review/template.rb:22: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/opt/homebrew/lib/ruby/gems/3.0.0/gems/review-5.1.1/lib/review/template.rb:22: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use …
```
> Suppress warning about ERB.new

- lib/review/epubmaker.rb
- test/test_epubmaker_cmd.rb
#1686 の対応。
Docker内でRuby 2.5のFileUtils.cpでtmpフォルダ内にコピーしたときに、preserveオプションを付けないと空ファイルになってしまうようです。
> FileUtils.cpにpreserveオプションをセット

- doc/writing_vertical.ja.md
本文を@<tcy>{～}で囲むだけでは縦中横にならず、このCSSを追加する必要がありました。
少なくともKinoppyでの閲覧においてはベンダープレフィックスも必要でした。
ご確認ください。
> 縦中横が指定された範囲をそのように表示するためのCSSを追加

- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/review-jsbook.cls
最近のTeXLIveのplautopatchとの組み合わせで、review-jsbook.cls,review-jlreq.clsで
```
\RequirePackage[dvipdfmx]{pxjahyper}
```
としていると `LaTeX Error: Option clash for package pxjahyper.` というエラーになります。plautopatchの事前処理と`[dvipdfmx]`が衝突するようです。
リファレンスバージョンとなるDebian 10 BusterのTeXLive 2018の時点でもplautopatchに関係なくdvipdfmxを明示する必要なく動作する(bookmarkが化けない)ことを確認したので、`[dvipdfmx]` を外します。
> remove unnecessary [dvipdfmx] option of pxjahyper

- .github/workflows/ruby-tex.yml
- .github/workflows/ruby-win.yml
- .github/workflows/ruby.yml
本リポジトリ内でのpull requestのときにGitHub Actionsが2回実行されていたのを1回にします
> GA: ignore push to non-master

- lib/review/builder.rb
- lib/review/compiler.rb
Builderが構文解析の状態を持つのはよろしくない（Builderを追加修正するごとに気をつけないといけなくなるし、そもそも構文解析器はあくまでCompilerになるべき）ので、Compiler側に寄せるよう修正します。
> refactor: previous_list_type should be in Compiler, not Builder

- .rubocop.yml
- lib/review/idgxmlbuilder.rb
rubocopルールの適用を追加します。
誤検出があったのでコメントで抑制します。
> rubocop: enabled Naming/MemoizedInstanceVariableName

- lib/review/pdfmaker.rb
昔の名残りでpdfmakerで `include FileUtils` をしていますが、ほかではpdfmaker.rb内含めすべてFileUtils.method形式になっており、1箇所だけ `remove_entry_secure` のところでの省略がありました。
includeをやめ、`FileUtils.remove_entry_secure` とします。
> remove FileUtils including

- lib/review/makerhelper.rb
- lib/review/pdfmaker.rb
#1696 の対応
`@config["pdfmaker"]["use_symlink"] = true` のときに、styとimagesのコピーをsymlinkで実行します。
OS非互換になりそうなので隠し機能扱いにしたいですが、仕事で使う(2GBオーバのimagesがある)ときに現状必須で内容的にextで対応もしづらいので、コードを入れさせていただきたいです。
> PDFMaker: コピーの代わりにシンボリックリンクを使う機能の提供

- lib/review/latexbuilder.rb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
- test/test_latexbuilder.rb
#1706 の修正
表示文字のエスケープを行い、等幅表示はやめます。
> PDFMaker: 画像が見つからないときのコンパイルエラーの回避

- lib/review/htmlbuilder.rb
- test/test_htmlbuilder.rb
CSS組版との親和性を上げるため、
HTMLビルダにおいて、headlineレベルに基づき `<section>` 要素で囲んで構造化する機能を追加しようと思います。通常の見出しのみが対象で、コラムについてはこれまでどおりdivです。
Makerに応じて `epubmaker/use_section: true` か `webmaker/use_section: true` で有効になります。
> <section>のサポート

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jlreq/review-jlreq.cls
- `serial_pagination=true, openany` (アラビア数字ノンブル通し + 右改丁強制しない)が指定されているときには、前付の偶数改ページではなく単なる改ページにします。(`serial_pagination`を指定していない場合はローマ数字前付で、これは偶数改ページしないと左右がおかしくなるのでそのまま。電子版などでこの挙動も無視したいんだという人は適宜`\jlreqsetup`で設定していただく)
- 欄外ノンブルのhiddenfolioの記述指定がまちがっていたので修正
- 目次だけページスタイルが違っているのが気持ち悪いので、章と同じheadingsページスタイルに。
jlreq.clsの改訂がけっこうドラスティックなのですが、TeXLive 2018・2019・2020・2021 HEADでコンパイル確認済みです。
> review-jlreq: serial_pagination + openanyの挙動に対処

- templates/latex/review-jlreq/review-jlreq.cls
#1718 の修正
jlreq.cls側で今後読み込まなくなるため、ifthenパッケージを明示で読み込むようにします。
> add ifthen package for newer jlreq.cls

- templates/latex/review-jsbook/review-jsbook.cls
#1720 の対応。
カーネルバージョンを見るかわりに、単純にeverypage-1x.styがあれば(あえて古い環境にそれを入れることは考えにくいので)それを使うようにしました。
いずれ使えなくなる可能性がある前提に立っておいたほうがよさそうですね…
> check and use everypage-1x for TL20 or higher

- test/test_pdfmaker.rb
#1727 の `config-local.tex.erb` にエラーがあった場合のテストです。
> Add test against `template_content`

- lib/review/epubmaker/epubcommon.rb
- lib/review/pdfmaker.rb
- test/test_pdfmaker.rb
#1726 のEPUB coverimage対応と、PDFMakerの外部ファイル取り込み部のチェック強化です。
- EPUBMaker: coverimage指定時に実ファイルがないときにバックトレースではなくエラーメッセージで終了させる(ApplicationErrorを明示raiseするようにしました)。
- PDFMaker: coverimage指定時に実ファイルがないときにコンパイル前に即エラーするようにしました。
- PDFMaker: titlefile, creditfile, profileなどで外部ファイルをインポートするよう設定しているときにファイルの存在チェックをするようにしました(`pdfmaker.rb#make_custom_page` 内)。
実ファイルが絡むのでテストを作りづらい…。
> ファイル存在チェックの強化

- lib/review/pdfmaker.rb
昔の実装の名残りで拡張子が.htmlなどだったら.texにするというのが残っていて、#1727 のコードで入れたエラーにすると手元の業務のもの大半が怒られるようになってしまいました。
メジャーアップデート時にでもこの置換は切ったほうがよさそうではありますが、当面はWARNにします。
> custompageが存在しないときにエラーではなく警告にする

- lib/review/latexbuilder.rb
- templates/latex/config.erb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
#1733 の修正
- `@<tcy>` を `\rensuji` にlatexbuilderから直接変換していたのを、抽象化として`\reviewtcy` 置換に変更
- review-jsbook/review-base.sty: デフォルトの`\reviewtcy`は横書きモードでは動作しないエラーにする。plextがロードされたら `\rensuji` に展開する。(ただしplextロードするのはclassnameがutbookなどのときだけというロジックに今はなっているので、現状では結局来ることはない…)
- review-jlreq/review-base.sty: jlreqで`\tatechuyoko` を提供してくれているので単にこれに任せる。yoko modeでのエラーについてもjlreq側でやってくれる。
- (そもそもtcyはreview-jsbook, review-jlreqはこれまで動いていなかったはずではあるが、)styを更新していないRe:VIEWプロジェクトにおいて `\reviewtcy` が定義のないときに一応後方互換に `\rensuji` に展開するように
> 縦中横マクロ抽象化の追加

- lib/review/index_builder.rb
- test/test_book_chapter.rb
- test/test_index.rb
#1725 の対応
footnote/endnoteの参照漏れチェック用に、IndexBuilderに実装を入れてみました。
キャプションや内容に含まれていることがあるので、軽量だったIndexBuilder内で `compile_inline` を各所で使わざるを得なくなっています。
> check unreferred footnote/endnote

- templates/latex/review-jlreq/review-jlreq.cls
`\jlreq@rensuji` が未定義扱いになる(jlreq.clsでクリアしてる？)ので、おもての命令として提供されている `\tatechuyoko` のほうを使うように変更します。
> use tatechuyoko instead of jlreq@rensuji

- lib/review/tocprinter.rb
- lib/review/volumeprinter.rb
review-vol, review-indexで
- 無効なyamlファイル名の指定
- catalog.yml内で無効なファイル名の指定
があるときにbacktraceエラーになっていました(IndexBuilderで評価順序が変わったのに追従できてなかった)。
より広めに例外捕捉するようにして対処します。
> review-vol, review-indexのエラー捕捉が不十分な状態の修正

- .github/workflows/ruby-win.yml
特にコード本体は追加・変更を加えておりませんが、WindowsにおけるRuby 2.7のチェックを追加しました。
なお、GitHub ActionsでWindowsにおけるRuby 3.0のチェックでエラーが出ている件ですが、私がWindowsにおけるRuby 2.7のチェックを加えた際に全てのテストをパスしており、再実行してみればRuby 3.0のチェックもパスすると思います。
> Windows における Ruby 2.7 チェックの追加

- lib/review/index_builder.rb
#1744 の対応
IndexBuilderでgraphの処理が漏れていました。
> implement graph on IndexBuilder

- lib/review/img_math.rb
数式画像化の遅延ビルドにおいてエラーが発生したときに `__IMGMATH_.tex` と `__IMGMATH__.log`  をコピーしていましたが、肝心の中身である `__IMGMATH_BODY__.tex` をコピーし忘れていました。
> copy __IMGMATH_BODY__.tex also to analyse

- doc/format.ja.md
- doc/format.md
SVG数式の作成のコマンドラインに間違いがありました。
- `-singlefile` は pdftocairoでSVGを作るときには逆に入れてはだめ
- `-svg` は `-%t` のままでもOKなのでそのように
> fix instruction to build svg math

- lib/review/index_builder.rb
footnote/endnoteのcrossrefチェックからheadlineが漏れていたので、compile_inline実行対象に。
> compile headline in IndexBuilder to check crossref

- templates/opf/opf_manifest_epubv2.opf.erb
- templates/opf/opf_manifest_epubv3.opf.erb
- test/test_epub3maker.rb
- test/test_epubmaker.rb
EPUB用の内部アイテム情報格納時に画像類がどの順序で入るかは実行時のファイルシステムに依存していました。書き出すたびに順序が微妙に違ったりして不便なので、ID文字列でソートするようにしてみます。
> manifest/itemをitem idでソートする

- .github/workflows/ruby-tex.yml
- .github/workflows/ruby-win.yml
- .github/workflows/ruby.yml
- .rubocop.yml
- lib/review/book/base.rb
- lib/review/catalog.rb
- lib/review/extentions/string.rb
- lib/review/i18n.rb
- lib/review/update.rb
- lib/review/yamlloader.rb
- review.gemspec
Psych should be >= 3.3.2 (see ttps://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/ )
#1766 の対応です。
* Pyschを3.3.2に固定(4.xだと古い環境のツールが動かなくなるようなので。具体的には`gem`コマンドでエラーが出るようになった)
* `YAML.load_file(path)`を`YAML.safe_load_file(path, aliases: true, permitted_classes: [Date])`に変更
* Rubocopでエラーが出るところがあったので一部修正したりRubocopのルールを変更したりした
> Support Ruby 3.1; use YAML.safe_load(_file)

- lib/review/book/base.rb
- lib/review/extentions/string.rb
- lib/review/init.rb
- lib/review/pdfmaker.rb
- review.gemspec
- test/test_htmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_topbuilder.rb
- test/test_yamlloader.rb
> follow Rubocop 1.13.1

- lib/review/epubmaker/epubcommon.rb
- lib/review/epubmaker/epubv3.rb
- test/test_epub3maker.rb
#1776 の修正です。
- cover内でepub:typeを設定し終えたら変数をnilに戻してほかで使われないようにする
- nav系目次に`epub:type="toc"` を指定
> correct epub:type

- samples/sample-book/src/config.yml
sample-bookのconfig.ymlで無用なurnidを設定しているため、EPUBcheckで警告が出ます。
sample-bookをユーザーが使う可能性は低そうですがリファレンスとなるサンプルが間違っているのは気持ちが悪いのでurnid定義を消します(これでランダム割り当てが行われるようになります)。
> remove invalid urnid from sample config.yml

- lib/review/epubmaker.rb
- lib/review/epubmaker/epubcommon.rb
- lib/review/webmaker.rb
- templates/html/_titlepage.html.erb
- test/test_epubmaker.rb
#1777 の修正第二弾です。
```
_colophon.html.erb
_colophon_history.html.erb
_cover.html.erb
_part_body.html.erb
_titlepage.html.erb
```
をlayoutsで上書きできるようにします。
epubmaker, webmakerでそれぞれに持っていたpartとtitlepageの書き換えはどちらもテンプレート側を使うように変更しました。
> HTMLパーツのlayoutsでの上書きの許可

- .rubocop.yml
`.rubocop.yml`の項目が多いため、`Enabled: true`になっているcopsは`.rubocop.yml`から削除しました。
> rubocop: remove enabled cops in .rubocop.yml

- doc/config.yml.sample
- lib/review/configure.rb
- lib/review/topbuilder.rb
- test/test_topbuilder.rb
#1789 の修正
textmakerにおいて、th/td行の間に`------------` を引くようにします。
`textmaker/th_bold` パラメータをtrueにすると従来の挙動(thに★〜☆を付け、区切り線を入れない)に戻ります。
> textmaker: 表見出し行と通常行の間に線を引く。後方互換にtextmaker/th_boldパラメータを追加

- lib/review/topbuilder.rb
- test/test_topbuilder.rb
#1790 の修正です。
//indepimageについて◆→開始:図←◆〜◆→終了:図←◆で囲み、画像がないときにはコメント部を出力します。
キャプションについては上書きしやすいようにメソッド`indepimage_header`に切り出しました。
> textmaker: //indepimageの出力の仕方を//imageに合わせる

- lib/review/topbuilder.rb
- test/test_topbuilder.rb
#1791 の修正
textmakerにおいて、//imgtableで図版が存在すればそのファイル名、なければコメント部を出力するようにします(//image同様の挙動にする)。
> textmaker: //imgtableの出力に画像ファイル名やコメントが含まれるようにする

- lib/review/epubmaker.rb
- lib/review/idgxmlmaker.rb
- lib/review/pdfmaker.rb
- lib/review/textmaker.rb
- lib/review/webmaker.rb
#1797 の修正
YAMLのcreateで例外(パーサエラー)が発生したときにConfigErrorを各makerで捕捉し、error!で終了させます。
> handle YAML parse error in makers

- lib/review/idgxmlbuilder.rb
IDGXMLのsecttagsモードを有効にしている(この時点でレアケース…)において、かつ前付後付の採番なしのものがあるとエラーになるのを修正します。
本質的には`<chapter>`を使ったかどうかでcloseするか決めたほうがいい気はしますが、もともとレアケースなので怠惰に対処します。
> IDGXML: force closing chapter for preface/postface

- lib/review/yamlloader.rb
YAMLLoaderで使っている`Date`でエラーになることがあったので、YAMLLoader自体にrequireをつけておきます（具体的にはreview-updateでした…）。
> Add `require 'date'` to yamlloader

- lib/review/idgxmlbuilder.rb
- lib/review/idgxmlmaker.rb
- test/test_idgxmlbuilder.rb
fix #1820 
- `lib/review/idgxmlbuilder.rb` : `texequation()` と `inline_m()` に、画像化した数式を出力する動作を追加
- `lib/review/idgxmlmaker.rb` : `'review/img_math'` を使えるようにコード追加
- `test/test_idgxmlbuilder.rb` : 追加した部分についてテストコードを書きました（`texequation()` キャプションあり・なし、`inline_m()`）
> Implement imgmath for IDGXML maker 

- lib/review/latexbuilder.rb
- templates/latex/config.erb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
#1836 の対応。
文字高にするのはヒントを与えるのみとした(が、これを見てくれるのかという問題はある)。
> PDFMaker: `@<icon>` の展開をreviewincludegraphicsではなくreviewiconに抽象化する

- lib/review/i18n.yml
- templates/latex/config.erb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
#1843 の対応です。
- i18n.ymlで、memo_headだけでなく、note_head,tip_head,info_head,warning_head,important_head,caution_head,notice_head, memo_head と個別に定義するようにした。
- review-jsbookにおける見出しの■はreview-baseスタイル側で入れるようにした。
- 各ヘッド文字に適切な日本語というのを決めにくいので英語大文字にした。
古い環境への影響
- i18n.ymlのmemo_headラベルで「■」を入れなくなっているのと「メモ」ではなく「MEMO」にしたので、locale.ymlを使ってmemo_headを昔のものに再定義(`memo_head: ■メモ`)する必要がある。
- review-jlreqにおいてreviewnoteなどで直に「NOTE」のように書いていたのをやめたり全大文字にしたりしているため、昔のものと完全一致させるにはlocale.ymlで再定義する必要がある。
- この機能を使っているのはLaTeX PDFMakerのみであり、EPUB等には影響しない。
> 囲み記事のラベルをMEMO,NOTE等妥当なものにする

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
- test/test_latexbuilder_v2.rb
#1872 の修正です。
//blankline手前で改ページになったときに0になるよう、vspace*ではなくvspaceにします。
```
//blankline
//noindent
あ
```
のようなケースでつながってしまうことがあったため、`\par`で確実に改段するようにしました。
> use \par\vspace\par instead of vspace* for //blankline

- README.md
- lib/review/epubmaker/epubcommon.rb
- lib/review/epubmaker/epubv3.rb
- templates/opf/epubv2.opf.erb
- templates/opf/epubv3.opf.erb
- templates/opf/opf_manifest_epubv2.opf.erb
- templates/opf/opf_manifest_epubv3.opf.erb
- templates/opf/opf_tocx_epubv3.opf.erb
- test/test_epub3maker.rb
#1874 の対応です。
- EPUBcheckで明示リンク参照されないnon-linearコンテンツがエラーとされるようになったため、EPUB3において、表紙へのリンクを目次の最初に入れるようにします。
- coverパラメータをnilにしたときに諸々エラーになるので手当てしました。
- EPUB2については何もしません。
(EPUB2まわりをやめて作り直したほうがいいのではという気もありますが…)
> add the link to cover as first item in toc.html

- lib/review/htmlbuilder.rb
- test/test_htmlbuilder.rb
MathJaxで`<`と`>`はHTMLで困るので、`\lt`, `\gt`という代替名にする必要がありました。
> escape < and > in MathJax

- lib/review/htmlbuilder.rb
- test/test_htmlbuilder.rb
> escape & also for MathJax

- lib/review/init.rb
#1824 の対応です
WEBrickで`0`でのIPバインドはWindowsのみダメだったので、どっちにしろデフォルトはIPv4でよかろう前提で`0.0.0.0`とします。
> use '0.0.0.0' as default for Windows on review-init wizard mode

- .github/workflows/rubocop.yml
- lib/review/epubmaker/epubv2.rb
- lib/review/idgxmlbuilder.rb
- lib/review/yamlloader.rb
- review.gemspec
RuboCopをアップデートしておきます。
`Style/RedundantInitialize`と`Lint/RedundantCopDisableDirective`の警告が出ていたため、それの対応も追加しました。
> Update rubocop 1.27.0

- lib/review/epubmaker.rb
reファイルがないときに生成する部HTMLファイルにおいて、`<title>`の値が空になることに気付きました。
(epubcheckで怒られた)
> EPUBMaker: fix missing `<title>` in autobuilt part

- lib/review/book/base.rb
- lib/review/book/image_finder.rb
- lib/review/book/index.rb
- test/test_image_finder.rb
#1896 の手当てです。
#1895 もこれで直るかと思います( #1895 自体は入れてよさそうな気はします)。
- base.rb: imagedirメソッドがプロジェクトフォルダ+`config['imagedir']`(つまりimages)を返していたのをやめて、`config['imagedir']`の結果だけを返すようにしました
- image_finder.rb:
- imagesフォルダを収集したときに、従来の完全なパス(path)のほか、拡張子を除いたもの(basename)、拡張子を小文字にしたもの(downcase)をハッシュで格納するようにしました
- initializeをChapterオブジェクトをとるだけにしました。Chapterオブジェクトがあれば組み立てられるのと、拡張子候補のextsはinitialize時点ではビルド固有(`builder_init_file`)設定が呼び出されていなくて適切化されていないためです
- イメージパスの先頭の「./」を除くようにしました。比較のときにここで厄介なことになっていたので…(そのため、厳密には結果互換性は失われます)
- 発見ロジックで、まず拡張子を除いたパスターゲット(target)に一致するものをまずエントリ一覧から収集し、そもそも存在しなければその瞬間に次のパスターゲット試行にいく、存在したら拡張子試行をしてみる、というようにしました。これにより無駄な試行が大幅に削減されて高速化します。また、これまでinitializeで行っていた拡張子候補取得をここでやる(`@book.image_types`)ようにしたので、ビルダ固有のものが使われるようになりました
- index.rb: image_finder.rbのinitialize変更との同期
#1896 …
> improve image_finder speed by skipping mismatch label

- samples/syntax-book/config-jlreq.yml
- templates/latex/review-jlreq/README.md
- test/test_img_graph.rb
jlreq.clsではb5だとISOサイズになる。b5jを使うようにガイドなどを変更する。
(jsbookではb5のままでOK)
> use b5j instead of b5 for JIS size

- .github/workflows/rubocop.yml
- .github/workflows/ruby-tex.yml
- .github/workflows/ruby-win.yml
- .github/workflows/ruby.yml
- .rubocop.yml
- README.md
- lib/review/builder.rb
- lib/review/compiler.rb
- lib/review/htmltoc.rb
- lib/review/idgxmlbuilder.rb
- lib/review/logger.rb
- lib/review/markdownbuilder.rb
- lib/review/textutils.rb
- lib/review/yamlloader.rb
- review.gemspec
Rubocop 1.59.0を適用しました。
bundlerがもうだめっぽいので2.7をやめて、3.3を追加しました。
> apply rubocop 1.59.0. Drop Ruby 2.7 and add 3.3

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
本PRの変更内容は、3点です。
1. インラインコード`@<code>`類における https://github.com/kmuto/review/issues/1906 の（とりあえずの）対処
* 詳細は、Noteのとおり。
2. インラインコード`@<code>{コード}`類がPDF栞に入ったときに、`コード`（単なる文字列）が入るように対応
* 1に間接的に影響する。
3. インライン画像`@<icon>`がPDF栞に入ったときに、何も入らないように対応
----------
ref. #1906 
latexビルダに対するインラインなコード要素（等幅） `@<code>`, `@<tt>`, `@<tti>`, `@<ttb>` において、「. (period+space)」直後の“余計な”（に見える）空白アキをひとまず除きます。
現状のRe:VIEW標準の`\reviewcode{...}`（`@<code>{...}`）は、ある種の`\texttt{...}`の**通常の入力された文字列**としてLaTeXに組版してもらっています（`\texttt`は`\verb/verbatim`ではない）。
> [!NOTE] 
> lmtt10の標準なTeX font metric（T1 encodingなら、`rm-lmtt10`）がそうなっているからですね。
> 「. (period+space)」は、「.」のあとにSPACE 0.525+EXTRASPACE 0.525が入るので、空白2つ分となります。
> 逆に、（必要であれば別名にして）EXTRASPACE 0.0としたfont metricを作ると、「. (period+space)」は空白1つ分となります。
> review-base.sty (\reviewtt, \reviewcode, \reviewtti, \reviewttb): inserted \frenchspacing inside

- doc/config.yml.sample
- samples/sample-book/src/config-epub2.yml
config.yml.sampleのrename_for_legacyの説明のファイル名にchap02lと不要な「l」が入っていたため削除しました。
> config.yml.sampleのコメントの誤記を修正

- NEWS.ja.md
- NEWS.md
- lib/review/version.rb
> Bump up 5.9.0

- review.gemspec
Re:VIEWをRuby 3.3.1で実行すると、以下のようなwarningが発生します。(csvとnkfは3.4以降default gemでなくなる予定)
本PRはgemの依存先にcsvとnkfを追加するもので、それによってwarningの発生を抑止し、(おそらく今年の年末にリリースされる)3.4以降のRubyのアップデートに対応できるようにします。
```
$HOME/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/review-5.9.0/lib/review/textutils.rb:9: warning: nkf was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add nkf to your Gemfile or gemspec. Also contact author of review-5.9.0 to add nkf into its gemspec.
$HOME/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/review-5.9.0/lib/review/builder.rb:19: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of review-5.9.0 to add csv into its …
```
> Add csv and nkf to gem's dependency

- lib/review/epubmaker.rb
- lib/review/epubmaker/epubcommon.rb
- lib/review/pdfmaker.rb
- review.gemspec
- test/test_epubmaker.rb
- test/test_img_math.rb
> support to load static files from subdir

- lib/review/book/base.rb
- lib/review/book/cache.rb
- lib/review/book/image_finder.rb
- test/test_helper.rb
#1916 の対応のため、Dir.glob等でファイルシステムを読み込んだ結果をキャッシュするようにします。
そのためにクラスとして`ReVIEW::Book::Cache`を追加してます。
- キャッシュは`@book`単位で行っているので、`@book`を作り直している場合には使われません
- 反対に、テスト等の際に`@book`を使いまわしているような場合、キャッシュされた結果が使われるので誤動作する危険性があります
- その場合は`@book.cache.reset`すれば再初期化されます
- `ReVIEW::Book::Cache`のインターフェースはRailsの`Rails.cache.fetch`を真似ていますが、expires等は不要そうなのでありません
- #1916
> Add `ReVIEW::Book::Cache` and use it in `ReVIEW::Book::ImageFinder`

- lib/review/epubmaker.rb
- test/test_epubmaker.rb
#1918 で言及した、verify_target_imagesが有効なときにcoverimageの画像ファイルも暗黙に取り込むものです。
imagedirで設定されたフォルダ(通常はimages)直下にあるcoverimageの画像ファイルを探す決めうちとしています。
> EPUBMaker: verify_target_imagesが有効なときに、coverimageを暗黙に取り込む

- .github/workflows/ruby-tex.yml
- review.gemspec
- test/test_img_math.rb
#1917 の対応で、ImageMagickのcopmareのmetricとしてSSIMを使うようにしてみます。
https://qiita.com/yoya/items/510043d836c9f2f0fe2f
しきい値は0.9で、それ以上なら一致・それ未満なら不一致ということにしています。
なお`-fuzz`はあってもなくても変わらなかったので落としています。
> mini_magick: use `SSIM` instead of `AE` for compare

- lib/review/builder.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/logger.rb
- lib/review/plaintextbuilder.rb
- lib/review/tocprinter.rb
- review.gemspec
RuboCopを1.65.1に更新します。
`Style/SuperArguments`を適用してsuperの引数を省略しています。
> update rubocop 1.65.1

- NEWS.ja.md
- NEWS.md
- doc/config.yml.sample
- doc/config.yml.sample-simple
- doc/format.md
- doc/makeindex.md
- doc/pdfmaker.md
- doc/preproc.md
- doc/quickstart.md
- doc/writing_vertical.md
- lib/review/builder.rb
- lib/review/epubmaker.rb
- samples/sample-book/src/config.yml
- test/test_epub3maker.rb
Intentionally omitted changing for `doc/ChangeLog-*` and ruby module names.
> Fix some typos

- review.gemspec
- test/image_comparator.rb
- test/test_img_math.rb
MiniMagickでの画像比較がどうにもうまくいかない（imagemagick 6とimagemagick 7の両対応も面倒くさそう）ので、SSIMをRubyで実装して（ChatGPTとClaude Codeに実装させて）みました。
* （当然ながら）あまり速くはないですが大した画像でもないので許容できそう
* PNGのみ対応ですが、それ以外のフォーマットの対応は不要なはず
* 画像比較アルゴリズムは素直に書いただけなので、継続的に手を入れる必要もないはず
ということで、この程度ならまあいいか…というところです。
> feat: use pure Ruby library instead of `MiniMagick` in test

- .rubocop.yml
- lib/review/book/book_unit.rb
- lib/review/compiler.rb
- lib/review/epubmaker/reviewheaderlistener.rb
- lib/review/latexbuilder.rb
- lib/review/sec_counter.rb
- review.gemspec
- test/test_book.rb
rubocopを更新します。メソッド名を変えさせるようなcopsはdisableにしています。
> update rubocop 1.80.1
