- doc/format.md
format.ja.md も翻訳してみました（だいぶ英語が怪しい）。
> Re:VIEW Format Guide (EN)

- lib/epubmaker/epubcommon.rb
> Escape pathname to prevent epubmaker from making files in different path

- lib/review/htmlutils.rb
- lib/review/latexbuilder.rb
- test/test_htmlbuilder.rb
- test/test_latexbuilder.rb
> Set default highlight lang

- lib/review/epubmaker.rb
ReVIEW::EPUBMaker のリファクタリングです。
* `@params["debug"]`を2回チェックしているところをまとめました
* call_hookの中でlog()を呼ぶようにしました
* `@epub` を `@producer` に変更しました(EPUBMaker::Producerのインスタンスなので)
* mkdir_pやrm_f / rm_rfをする際に存在チェックしていたのを削除しました（不要なはずなので）
* `!foo.nil?` となっているのを `foo.present?` にしました(unless foo.nil? も if foo.present? に変更)
特に問題なければmergeします
> Refactor ReVIEW::EPUBMaker

- lib/review/pdfmaker.rb
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
- test/test_helper.rb
- test/test_pdfmaker.rb
suppored files (attributes):
* originaltitlefile
* creditfile
* profile
* advfile
* colophon
* backcover
cf. #386
> PDFMaker: support additional file insertion (same as EPUBMaker)

- lib/epubmaker/producer.rb
fix #433 
htmlversion should be 5 when epubversion == 3
> fix htmlversion when epubversion==3

- doc/NEWS.ja.md
- doc/NEWS.md
NEWSファイルを本体に入れておくのはどうでしょうか。
ついでに1.5に向けて追記してあります（全部ではないです）。
> add NEWS and NEWS.ja files in doc/

- .travis.yml
> travis: add test

- bin/review-check
- bin/review-compile
- bin/review-index
- bin/review-preproc
- bin/review-vol
- lib/review/book/compilable.rb
- lib/review/builder.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/pdfmaker.rb
- lib/review/preprocessor.rb
- lib/review/textutils.rb
- lib/review/tocprinter.rb
- lib/review/topbuilder.rb
- test/test.re
- test/test_book_chapter.rb
- test/test_builder.rb
- test/test_htmlbuilder.rb
- test/test_i18n.rb
- test/test_idgxmlbuilder.rb
- test/test_inaobuilder.rb
- test/test_latexbuilder.rb
- test/test_lineinput.rb
- test/test_markdownbuilder.rb
- test/test_topbuilder.rb
ソースファイルをUTF-8に統一するために、inencoding/outencodingの指定を廃止しました。
> Remove inencoding and outencoding

- lib/review/pdfmaker.rb
- test/test_pdfmaker.rb
* check_book -> remove_old_file
* `config` and `basedir` are instance variables
* change signature of some methods; remove `config`
> refactor PDFMaker

- lib/review/latexbuilder.rb
> do not use super in node_*

- lib/review/latexbuilder.rb
> do not escape content of footnote

- ChangeLog
- doc/NEWS.ja.md
- doc/NEWS.md
- lib/review/version.rb
cf. https://github.com/kmuto/review/issues/465#issuecomment-166112922
> for release v1.7.2

- lib/review/builder.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- test/test_htmlbuilder.rb
> Refer to column in another chapter

- bin/review-compile
> review-compile: use config.yml as default

- lib/review/book/chapter.rb
- lib/review/book/index.rb
- lib/review/i18n.rb
- test/test_htmlbuilder.rb
- test/test_i18n.rb
> Add custom i18n formats

- lib/epubmaker/epubcommon.rb
- review.gemspec
> remove zip command and use PureRuby Zip library

- test/test_htmlbuilder.rb
> add a test of reference to Part

- doc/sample.yml
- lib/epubmaker/producer.rb
- test/test_epub3maker.rb
> add direction in default setting

- bin/review-compile
- lib/epubmaker/producer.rb
- lib/review/epubmaker.rb
- lib/review/makerhelper.rb
- lib/review/pdfmaker.rb
#503 の実装方針を変更し、includeを実装してみました。
ただ、includeは誤解を招く可能性があるため、inherit:という名前にしています。
> accept multiple YAML configurations using inherit parameter.

- lib/review/extentions/hash.rb
- test/test_extentions_hash.rb
https://github.com/kmuto/review/issues/503#issuecomment-206656955
Rails has similar API, but more complex:  http://apidock.com/rails/Hash/deep_merge
> add Hash#deep_merge

- doc/sample.yml
sample.ymlが読みにくいので、インデントと空行を入れてみました。
> sample.yml: add indent and line separator

- doc/sample.yml
37a05cb7acad1a9ed2a57cb837790611c5a71271 で修正した件です。doc/sample.ymlにも反映させておきます。
> `prt` should be printer, not publisher (`pbl`)

- lib/review/builder.rb
- lib/review/i18n.rb
- lib/review/inaobuilder.rb
- test/test_book_chapter.rb
- test/test_lineinput.rb
surpress warnings in Travis-CI
> surpress warning

- lib/review/extentions.rb
- lib/review/yamlloader.rb
- test/test_yamlloader.rb
ref. https://github.com/kmuto/review/pull/511#issuecomment-205386807
> add ReVIEW::YAMLLoader

- lib/epubmaker/epubv3.rb
- templates/opf/epubv3.opf.erb
- test/test_epub3maker.rb
cf. #502, https://github.com/kmuto/review/pull/512#issuecomment-205107415
> add custom prefix and `<meta>` element in OPF

- bin/review-compile
- lib/epubmaker/producer.rb
- lib/review/epubmaker.rb
- lib/review/makerhelper.rb
- lib/review/pdfmaker.rb
- lib/review/yamlloader.rb
- test/test_yamlloader.rb
$REVIEW_PATH も入れてあります。
設定を細分化する可能性があるとなるとinheritはArrayのほうがいいかなと思い始めましたが、YAMLLoaderで再帰ではなくloopの実装になったのでちょっと悩みます。
> YAMLLoaderへの置き換え

- lib/review/yamlloader.rb
- test/test_yamlloader.rb
https://github.com/kmuto/review/issues/503#issuecomment-207193172
> YAMLLoader: support Array for inherit

- lib/review/idgxmlbuilder.rb
自作自演PRですが、idgxmlでのimgtableサポート追加
> support imgtable in idgxml

- bin/review-compile
- test/sample-book/src/Rakefile
> Remove all option from review compile

- bin/review-compile
- lib/review/configure.rb
- lib/review/epubmaker.rb
- lib/review/pdfmaker.rb
- test/test_configure.rb
`@config.check_version(ReVIEW::VERSION)` raises error when different major version or newer minor version
> do check_versio for config.yml

- lib/review/epubmaker.rb
> fix epub build_path on debug

- appveyor.yml
- test/test_book.rb
- test/test_epubmaker_cmd.rb
- test/test_makerhelper.rb
- test/test_pdfmaker_cmd.rb
> fix tests for windows

- lib/review/makerhelper.rb
should be included by *Maker classes
> MakerHelper: class -> module

- lib/epubmaker/epubcommon.rb
- lib/epubmaker/producer.rb
- lib/review/book/chapter.rb
- lib/review/htmlutils.rb
- lib/review/template.rb
- test/test_htmltoc.rb
> require libraries

- bin/review-webmaker
- lib/review/configure.rb
- lib/review/htmlbuilder.rb
- lib/review/htmlutils.rb
- lib/review/webmaker.rb
- lib/review/webtocprinter.rb
- templates/web/html/layout-html5.html.erb
- templates/web/html/layout-xhtml1.html.erb
- test/test_htmlbuilder.rb
- test/test_i18n.rb
`review-webmaker` コマンドを追加します。epubmakerとは違って、webサイト用のHTMLファイルを"webroot/"以下に生成します。
> add webmaker

- Rakefile
> Set warning to false in test

- lib/review/pdfmaker.rb
- templates/latex/layout.tex.erb
テンプレートの中ではローカル変数ではなくインスタンス変数を使うようにする修正です。
> use instance variable in templates

- lib/review/pdfmaker.rb
これがないとreview-pdfmakerが動かなかったので追加しておきます
> fix pdfmaker: require some files

- lib/review/converter.rb
> ReVIEW::Converter: set config["builder"]

- test/sample-book/src/Rakefile
- test/sample-book/src/config.yml
- test/sample-book/src/style-web.css
`review-init`で作られる方には反映されないんですが、サンプルとして追加しておきます :bow:
> add stylesheet for web of sample book

- doc/NEWS.ja.md
- doc/NEWS.md
> fix NEWS.md and NEWS.ja.md

- doc/preproc.ja.md
- doc/preproc.md
`review-preproc`の使い方です。
cf. #215
> add preproc(.ja).md

- test/sample-book/src/Rakefile
`rake preproc`で全*.reファイルに対して`review-preproc --replace`を実行するものです。
> Rakefile: add task `preproc`

- lib/review/book/base.rb
- lib/review/book/part.rb
- lib/review/i18n.yml
- lib/review/webtocprinter.rb
- test/book_test_helper.rb
- test/test_book.rb
- test/test_review_ext.rb
- test/test_webtocprinter.rb
> Fix WEBTOCPrinter when Part has no "*.re" file

- lib/review/pdfmaker.rb
- templates/latex/layout.tex.erb
- test/assets/test_template.tex
> LATEXBuilder: escaping values from config.yml and locale.yml

- lib/review/htmlbuilder.rb
- lib/review/htmlutils.rb
- templates/latex/layout.tex.erb
- test/test_epub3maker.rb
- test/test_yamlloader.rb
cf. https://github.com/kmuto/review/pull/617#issuecomment-217673533
> use pxjahyper package even in platex

- templates/web/html/layout-html5.html.erb
> webmaker: fix broken link

- lib/review/topbuilder.rb
とりあえずこのタグがなくて困ったのでマージします…。ほかにもいろいろありそう。
> support @<hd> in TextBuilder.

- bin/review-init
> generate Gemfile

- templates/LICENSE
- templates/README.md
> template fils are MIT license

- doc/NEWS.ja.md
- doc/NEWS.md
> add news of 2.1.0

- lib/review/pdfmaker.rb
> PDFMaker: refactor generate_pdf

- lib/review/htmlbuilder.rb
> HTMLBuilder: refactor HTMLBuilder#result

- .rubocop.yml
- lib/review/builder.rb
- lib/review/compiler.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
It defines first line number in lists of `//listnum` and `//emlistnum`
cf #685
> suppot //firstlinenum

- test/test_zip_exporter.rb
cf. https://github.com/kmuto/review/issues/713
> without rubyzip, skip zip test

- lib/review/htmlutils.rb
- test/test_htmlbuilder.rb
cf. https://github.com/kmuto/review/issues/710
> HTMLBuilder: use Rouge only when highlighting with Rouge

- lib/review/htmlbuilder.rb
メソッド名のほうをlayout_file→layoutfileにして対処
> fix a bug of loading layouts/layout.html.erb (closes #721)

- .rubocop.yml
> surpress rubocop: allow rescue modifier

- lib/review/topbuilder.rb
> TOPBuilderのheadlineをほかに合わせる

- .travis.yml
see: https://github.com/bundler/bundler/issues/5357
> fix test in travis

- .rubocop_todo.yml
> suppress rubocop

- templates/latex/layout.tex.erb
> support subtitle on PDFmaker (closes #745)

- lib/review/htmlbuilder.rb
> HTMLBuilder: generate images for math notations

- lib/review/version.rb
> bump up: v2.3.0

- lib/review/extentions/string.rb
> ruby 1.8 was not supported

- bin/review-catalog-converter
- bin/review-check
- bin/review-compile
- bin/review-epubmaker
- bin/review-index
- bin/review-init
- bin/review-preproc
- bin/review-vol
- lib/review/book/base.rb
- lib/review/book/index.rb
- lib/review/builder.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/logger.rb
- lib/review/pdfmaker.rb
- lib/review/preprocessor.rb
- lib/review/rstbuilder.rb
- lib/review/topbuilder.rb
- lib/review/webmaker.rb
* add class `ReVIEW::Logger`, sub class of `::Logger`
* add methods `ReVIEW.logger()` and `ReVIEW.logger=(logger)`
* use `@logger` for `error()` and `warn()`
> fix #705; use ReVIEW::Logger

- lib/review/compiler.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/latexbuilder.rb
- lib/review/markdownbuilder.rb
- lib/review/rstbuilder.rb
- lib/review/topbuilder.rb
> allow block for //indepimage

- .rubocop.yml
> update rubocop and fix error

- bin/review-validate
- lib/review/epubmaker.rb
- test/test_epub3maker.rb
image_sizeブランチ込みなので、まずはそれをマージしてからだけど。
ひとまずlib/review/epubmaker.rbから。
> Loggerにまだしていないものを対応させていく

- lib/review/htmlbuilder.rb
- lib/review/latexbuilder.rb
format...headerじゃなくてformat..chapter
> listref, imgref, tablerefのi18n展開のキー文字列間違い

- lib/review/i18n.yml
- test/test_i18n.rb
#837 
部番号に%pR (I, II, ...)を適用します。part_shortでもともとそうしていたので統一します。
> i18nのpartに%pRを設定

- lib/epubmaker.rb
- lib/epubmaker/epubcommon.rb
- lib/epubmaker/epubv2.rb
- lib/epubmaker/epubv3.rb
- lib/epubmaker/producer.rb
- lib/epubmaker/zip_exporter.rb
- lib/review/epubmaker.rb
- templates/opf/epubv2.opf.erb
- templates/opf/epubv3.opf.erb
- test/test_epub3maker.rb
- test/test_epubmaker.rb
- test/test_zip_exporter.rb
#867 の対応。
epubmakerにモンキーパッチをする可能性はないので、ユーザへの影響はないと思います。opfを上書きする可能性もないだろうし。
> 設定情報の内部変数名をparamsからほかのMakerに合わせてconfigに変更

- doc/format.md
> footnotetextの説明修正

- lib/review/textutils.rb
pull requestに対するpull requestでアレですが、こんな感じでどうでしょうか。
* linesは壊さない
* メソッドは適宜分割したい
* if修飾子やwhile修飾子は複雑な場合は使わない方が読みやすそう
* `lines[lines.size - 1]`は`lines[-1]`で良さそう
> do not break argument `lines`

- .rubocop.yml
- lib/review/configure.rb
- review.gemspec
while/untilの1ライナー記述勧告を無視するように。
if 1ライナーを求めるIfUnlessModifierも無視したほうがいいかなぁ。
> rubocop: Style/WhileUntilModifierチェックをfalseに

- .travis.yml
> ruby 2.0ビルドを停止

- lib/review/book/base.rb
> catalog.ymlのBOMをスキップする

- .travis.yml
Travisに入ったっぽいのでRuby 2.5.0ビルドを入れてみる。
> Ruby 2.5.0のテスト

- lib/review/compiler.rb
> use blocks like #903 in lib/review/compiler.rb

- templates/html/layout-xhtml1.html.erb
- templates/web/html/layout-xhtml1.html.erb
> removes errors and warnings in published document

- README.md
> README.md年更新

- bin/review
#933 の対応。
特例のversion、helpも追加した。
> reviewコマンドのヘルプメッセージ

- doc/quickstart.ja.md
- doc/quickstart.md
> review-textmakerについてquickstartに記述

- bin/review
> reviewコマンドのWindows環境向け修正

- bin/review-compile
長すぎて怒られるので、分離し、パラメータ渡しのために`@`変数に変更。
> review-compilleの_mainからコマンド引数解析を分離

- lib/review/book/base.rb
`"#{A}/#{B}"`的なものをFile.join化する。
nilがダメ ＆ あちこちで必要とする ので、Fileオブジェクトにメソッド追加したいなという気持ちになっています。
> [WIP] File.join化

- bin/review
> fix help message (ReVIEW -> Re:VIEW)

- lib/review/version.rb
next Re:VIEW release should be 3.0.0...
分かりやすいようにバージョン番号をあげておきます
> for 3.0.0-preview1

- lib/review/logger.rb
> Fix to work on Ruby 2.3

- lib/review/logger.rb
- test/test_logger.rb
> add test for logger

- lib/review/book.rb
use `ReVIEW::Book.load` or `ReVIEW::Book::Base.load`
> remove ReVIEW.book

- lib/review/book/base.rb
- lib/review/builder.rb
- lib/review/configure.rb
maybe typo. should use `imagedir`.
cf. #983
> remove image_dir

- lib/review/book.rb
- lib/review/book/base.rb
It was obsoleted since Re:VIEW 1.5
> remove Book::Base.load_default

- lib/review/book/base.rb
- test/test_book.rb
- test/test_review_ext.rb
`update_rubyenv` is invoked in `Base#new`
> `Base.update_rubyenv` -> `Base#update_rubyenv`

- lib/review/book/base.rb
initialize内で初期化しているので、def config内で再初期化する必要はなさそう
> refactor: Base#config is just reader

- lib/review/htmlbuilder.rb
- test/book_test_helper.rb
- test/test_htmlbuilder.rb
imgmath 指定時に `<div class="equation">`が入れ子になっていたのを修正します
> `<div class="equation">` duplicated

- Rakefile
- review.gemspec
- test/run_test.rb
rcov is obsoleted.
cf. https://github.com/relevance/rcov
> use simplecov instead of rcov

- bin/review-catalog-converter
> part files are "partNN.re"

- bin/review-catalog-converter
手元にpatchがあったので投げておきます。
`[y/n]`を効いているところを`ask_yes?`というメソッドにするのと、File.read / File.writeを使うようにするrefactorです。
> refactor: use File.read and File.write, add ask_yes?

- doc/format.ja.md
- doc/format.md
> add instructions of //graph

- bin/review-init
- doc/config.yml.sample-simple
見た目の修正で、修正不要なところをもとに戻すものです（diffをきれいにするため）
> revert cosmetic change

- doc/config.yml.sample
- doc/pdfmaker.ja.md
- doc/pdfmaker.md
- lib/review/configure.rb
config["texoptions"]のデフォルトが抜けていたのでnonstopmodeで追加します。止まってうれしいことはないはず…
> config: texoptions is "-interaction=nonstopmode -file-line-error"

- templates/latex/config.erb
- templates/latex/review-jsbook/review-basemacros.sty
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
条件次第でのいろいろ暗黙のNG事項が多くてややこしい…
とりあえずどの状況でもトラブらないように_は使わないようにしてみます。
> texパラメータから_を取る

- doc/config.yml.sample
#919 への対応も兼ねて、コメントとして記載しておきます。
> config.yml: add comment for dvioptions

- lib/review/latexbuilder.rb
- templates/latex/config.erb
- templates/latex/review-jlreq/review-jlreq-basemacros.sty
- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jlreq/reviewmacro.sty
- templates/latex/review-jsbook/review-basemacros.sty
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
- test/test_latexbuilder.rb
> refactor jlreq-exp branch

- lib/review/book.rb
use `Book::Base#update_rubyenv`.
> remove unused `Book.update_rubyenv`

- lib/review/latexbuilder.rb
- test/test_latexbuilder.rb
> `@<m>` has specers in 2, not in 3

- lib/review/latexbuilder.rb
- templates/latex/review-jsbook/review-basemacros.sty
- test/test_latexbuilder.rb
> add `\begin{reviewlistblock}...\end{reviewlistblock}` for lists

- lib/review/latexbuilder.rb
- test/test_latexbuilder_v2.rb
`review_version: 2.0`のときのテストです。
2.5.0のtest_latexbuiler.rbのコピーですが、このままでは通らなさそう。
> add test of latexbuilder for v2

- lib/review/pdfmaker.rb
> fix template_content

- lib/review/makerhelper.rb
挙動にはmunepi版graphicx拡張styファイルも必要なので、それを入れてからマージしたい。
> pdfmaker用にpsdファイルもコピーする

- templates/latex/review-jsbook/review-base.sty
> support old pxrubrica

- templates/latex/review-jsbook/review-base.sty
- templates/latex/review-jsbook/review-style.sty
- templates/latex/review-jsbook/reviewmacro.sty
> RequirePackage is better than usepackage in *.sty

- lib/review/latexbuilder.rb
#1062 の修正を試みます。
MeCabで見つからなかったときにさらにmecabを探します。
> MeCab→mecabで探す

- lib/review/pdfmaker.rb
- templates/latex/layout.tex.erb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jlreq/review-jlreq.cls
#1035 できえださんから指摘いただいたものをそのまま。
手元だとlualatexの新しいのが動く環境をまだ揃えてないのですが、uplatexのほうには副作用はないです。
> jlreqをlualatexでビルドするための修正

- test/sample-book/src/Rakefile
use https://github.com/kmuto/review/pull/1060#issuecomment-401036998
> fix Rakefile

- lib/review/version.rb
- review.gemspec
> Fix prerelease

- lib/review/configure.rb
- templates/latex/review-jsbook/review-base.sty
- templates/latex/review-jsbook/review-style.sty
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
- test/sample-book/src/config.yml
- test/syntax-book/config.yml
* geometryを読み込まないようにします ( #912 関連)
* ページ番号を見開きの左右に振ります ( #1032 関連)
> LATEXBuilder: remove geometry, add twoside option

- lib/review/book/volume.rb
- lib/review/extentions/string.rb
> remove `String#charsize`

- test/sample-book/src/style.css
- test/syntax-book/style.css
A litle little fixing :dog2:
I fount this when I executed `review-init`.
> Fix strange hard tabs

- NEWS.ja.md
- NEWS.md
> add NEWS of 3.0.0preview2

- templates/latex/config.erb
- test/assets/test_template.tex
- test/assets/test_template_backmatter.tex
bannerに渡すためにbooknameがほしいなと思って見ていくと、ほかのメタ情報もいろいろ渡しておいても損はないなということで、あらかたの情報を渡すことにします。
> TeXにerb経由で渡すconfig.ymlパラメータ追加

- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/README.md
- templates/latex/review-jsbook/review-jsbook.cls
review-jsbook.clsのドキュメントをざっと書きました！
配置場所の変更なり、もしくは、Wikiなりどこかに転記していただいてもよいです。
> added: review-jsbook.cls User's Guide

- templates/latex/review-jsbook/review-jsbook.cls
#1133
*   review-jsbook.cls (\frontmatter): changed: use \g@addto@macro
*   review-jsbook.cls (titlepage): changed: use \patchcmd of etoolbox
以下のは review-jlreq.cls で使えます。
```tex
% \patchcmd\titlepage
%   {\setcounter{page}{1}}{\relax}%
%   {}{\recls@warning{titlepage}}
% \patchcmd\endtitlepage
%   {\setcounter{page}{1}}{\relax}%
%   {}{\recls@warning{endtitlepage}}
```
> proposed-update #1133

- test/test_pdfmaker.rb
patchバージョンを書き換えてもテストが死なないようにします。
> test should be success when using different version

- lib/review/init.rb
こういう場合は `Tempfile.create` を使って自動削除させるのが良さそうです。
> use Tempfile.create to use automatic-remover

- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jlreq/review-style.sty
> review-jlreqにもhiddenfolioを実装

- NEWS.ja.md
- NEWS.md
* #1151 is not merged yet.
* this version is 3.0.0 preview 4
> update NEWS files

- templates/latex/review-jlreq/review-jlreq.cls
review-jsbookと同様にカスタムスタイル作成向けの支援マクロです。
> TeX: review-jlreqにoneblankpageとclearoddpageマクロを追加

- doc/quickstart.ja.md
- doc/quickstart.md
クイックスタートにreview-updateについての説明を簡単に追加しました。
> review-updateについてのドキュメント記載とマイナーな修正

- doc/config.yml.sample
- doc/config.yml.sample-simple
コメントばかりなので機能には影響しないですが。
- 日付をなんとなく11/11にしてみた
- imgmathの設定をコメントで追加
- epub,htmlのバージョンを3と5に
- 未実装のパラメータは書いても意味がないので除去
- page_metricがTeXではなくてreview-vol用であることを記載
- directionがEPUB向けであることを記載
> config.yml.sampleの更新

- doc/pdfmaker.ja.md
- doc/pdfmaker.md
> pdfmakerドキュメントの更新

- templates/latex/review-jsbook/review-jsbook.cls
おおむね行送りはこれで合いはするけど、一貫したルールが見えない…
> jsbookの行送り合わせ

- templates/latex/review-jlreq/README.md
- templates/latex/review-jlreq/review-jlreq.cls
- README.mdのオプションまわりおよびバージョン注意を記載
- serial_paginationとstartpageが最近のjlreq.cls変更で動かなくなっていたので修正
> review-jlreqの更新

- templates/latex/review-jsbook/README.md
- templates/latex/review-jsbook/review-jsbook.cls
QWLHが除去された影響に追従します。
`### 基本版面設計` の項はこれで正しそうでしょうか。@munepi
> review-jsbook README更新

- README.md
> 些末なドキュメント更新

- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/review-base.sty
#1224 の対応
amsmathの周辺パッケージもrequireする。
> TeX: amssymb,amsthm, bmパッケージを追加

- templates/latex/review-jlreq/review-jlreq.cls
> review-jlreqのLuaLaTeX対応修正

- .travis.yml
https://travis-ci.org/kmuto/review/jobs/475921721
```console
$ gem update bundler
Updating installed gems
Nothing to update
$ bundle install --jobs=3 --retry=3
The program 'bundle' is currently not installed. To run 'bundle' please ask your administrator to install the package 'bundler'
```
> need to install bundler, not update (???)

- lib/review/latexbuilder.rb
- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
- test/test_latexbuilder.rb
#1254 の対応です。
2系は互換性を保持しますが、3系にはbreaking change(review-updateでreview-base.styの更新が必要)です。
> \reviewimagecaptionの導入

- lib/epubmaker/epubcommon.rb
- lib/review/epubmaker.rb
#1262 の対応です。
いろいろ場当たりになっているきらいはありますが…。
> EPUBMaker: 部付きの場合の階層目次生成の改良

- lib/review/catalog.rb
> CHAPS:が空のときにエラーが出ることの退避

- test/test_catalog.rb
> add a test for `parts_with_chaps`

- bin/review-compile
`@config`にするところを`config`としていた箇所を修正
> エラーメッセージ内の変数名誤りを修正

- lib/review/epub2html.rb
CSS組版で本来の脚注を実現するために、review-epub2htmlに`--inline-footnote`オプションを追加します。div要素の脚注ブロックの内容は、参照元のところにspan要素となって埋め込まれます。
実際の脚注表現については、ユーザーが以下のような作業をすることが前提です。
- CSS側では、Vivliostyle Formatter, VersaType Converter, AHFormatterそれぞれ固有の脚注表現になるように定義します。たとえばVivliostyle/VersaTypeの場合…
```
section {
...
counter-reset: footnote 0;
}
span.footnote {
float: footnote;
counter-increment: footnote;
...
}
.footnote::footnote-call {
content: "[*" counter(footnote,decimal) "]";
vertical-align: super;
...
}
.footnote::footnote-marker {
content: "[*" counter(footnote,decimal) "]";
...
}
```
- locale.ymlで脚注番号が入らないようにします。
```
locale: ja
html_footnote_textmark: ""
```
> EPUB2HTML: 脚注のdiv要素をspanにしてインラインに入れる機能の追加

- bin/review-catalog-converter
- bin/review-check
- bin/review-compile
- bin/review-epubmaker
- bin/review-index
- bin/review-preproc
- bin/review-vol
- lib/review/book/base.rb
- lib/review/compiler.rb
- lib/review/init.rb
- lib/review/preprocessor.rb
- lib/review/update.rb
- test/test_book.rb
> rubocop 0.67.2対応

- lib/epubmaker/epubv2.rb
> fix handling date metadata in EPUBv2

- lib/epubmaker/producer.rb
> workaround for Windows path resolution

- .travis.yml
use newer rubies in each minor versions.
http://rubies.travis-ci.org/
> travis: update ruby versions

- lib/review/yamlloader.rb
> YAMLLoader: extract parse_inherit from load_file

- .travis.yml
do not overwrite default `script`...
> travis: exec rake

- .rubocop.yml
- lib/review/idgxmlbuilder.rb
related to #1311 
この行だけなんとかしたい、という場合はこうするそうです。
> disable rubocop warning on a single line

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
#1348の対応
reviewbreakallロジックにより、インラインtt系のスペース保持&適当に改行を実現します。
> introduce reviewbreakall

- bin/review-idgxmlmaker
- lib/review/idgxmlmaker.rb
- samples/sample-book/src/lib/tasks/review.rake
- samples/syntax-book/review-ext.rb
#1337 
IDGXMLの一括作成(およびフィルタ適用)を行うメーカーを追加します。
> review-idgxmlmakerの導入

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jsbook/review-base.sty
> reviewcolumnref内でコラムラベルまで入れてしまって重複しているのを修正

- lib/review/book/base.rb
- lib/review/book/chapter.rb
- lib/review/catalog.rb
- test/test_book.rb
- test/test_catalog.rb
* `Catalog#{chaps,parts,predef,postdef,appendix}` should return Array, not String
* fix `read_*`, remove cache `@read_part`
> refactor Catalog

- samples/sample-book/src/config-jlreq.yml
- samples/sample-book/src/lib/tasks/z01_copy_sty.rake
- samples/syntax-book/ch03.re
- samples/syntax-book/config-jlreq.yml
- samples/syntax-book/lib/tasks/z01_copy_sty.rake
スタイル/clsカスタマイズ時の実験がしやすいよう、sample-bookとsyntax-bookでjlreq版もテストできるようにルールを調整しました。
```
REVIEW_TEMPLATE=review-jlreq REVIEW_CONFIG_FILE=config-jlreq.yml rake pdf
```
> samplesの中でreview-jlreqを使ったパターンを利用できるようにする

- bin/review-compile
- bin/review-index
- bin/review-vol
- lib/review/epubmaker.rb
- lib/review/logger.rb
- lib/review/pdfmaker.rb
- lib/review/textmaker.rb
- lib/review/webmaker.rb
- test/test_htmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_logger.rb
- test/test_topbuilder.rb
Logger標準のprognameを使わずに頑張っていたのを、prognameを使うようにする修正です。
昔書いたのが発掘されたのでPRしておきます。
> Logger: progname should be add in logger, not in message arguments.

- templates/latex/review-jlreq/review-base.sty
- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jlreq/review-style.sty
- templates/latex/review-jsbook/review-base.sty
- templates/latex/review-jsbook/review-jsbook.cls
- templates/latex/review-jsbook/review-style.sty
> add version to *.cls and *.sty

- .rubocop.yml
- bin/review-compile
- bin/review-validate
- lib/review/book/base.rb
- lib/review/book/index.rb
- lib/review/compiler.rb
- lib/review/init.rb
- lib/review/tocparser.rb
- review.gemspec
> follow RuboCop 0.77.0

- .github/workflows/ruby.yml
TravisCIの代わりにGitHub Actionを使うものです。
> use GitHub Actions

- .github/workflows/ruby.yml
- README.md
> use GitHub Actions instead of TravisCI

- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
htmlbuilder,idgxmlbuilderにおいて、list,source内でsuperを使えば済むところをそのように修正します。
> htmlbuilder,idgxmlのリファクタリング

- lib/review/idgxmlbuilder.rb
もう1つsuperでリファクタリングできるところがありました
> refacotring idgxmlbuilder

- lib/review/idgxmlbuilder.rb
- samples/sample-book/src/.gitignore
- samples/syntax-book/ch02.re
- samples/syntax-book/lib/tasks/review.rake
- test/test_idgxmlmaker_cmd.rb
- test/test_pdfmaker_cmd.rb
- test/test_textmaker_cmd.rb
ちょっといくつも混ぜていますが、
- idgxmlmakerの実行テスト
- textmakerの実行テスト
- idgxmlbuilder#imgtableのメソッド変更追従もれの修正
- syntax-bookの変更 (`@<u>`はhyperrefで問題が出るので見出しに使用しない)
- .gitignoreに-idgxmlを追加
> IDGXMLMaker, TextMakerのテスト追加

- doc/quickstart.ja.md
- doc/quickstart.md
> update quickstart to follow v4

- doc/config.yml.sample
- lib/review/builder.rb
- lib/review/configure.rb
- lib/review/idgxmlbuilder.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_topbuilder.rb
ということで`table_row_separator`にします。
> rename to table_row_separator

- README.md
makerまわりはもう2つじゃなくなったのと、review-initが入ってなかったので。
> update README.md about commands

- README.md
> happy new year

- lib/review/builder.rb
> Allow a setting of multiple words_file

- .rubocop.yml
- lib/review/epubmaker.rb
- lib/review/makerhelper.rb
- lib/review/textutils.rb
#1488 の対応
いったん式ごとのファイルを書き出し、それをソート・uniq化して使うようにしました。
> avoid duplication of creating same math

- doc/pdfmaker.ja.md
- doc/pdfmaker.md
- lib/review/pdfmaker.rb
- test/test_pdfmaker.rb
#1505 の実装です。
layouts/config-local.tex.erb があるときにそれを取り込みます。
> config-local.tex.erbの導入

- lib/review/tocprinter.rb
- lib/review/webtocprinter.rb
- test/test_webtocprinter.rb
#1508 の修正です。
tocparserの作り替えでバグを作ってしまっていました。webtocprinterのテストで拾えそうなのがわかったのでテストを追加しています。
> fix an error when any headline doesn't exist

- NEWS.ja.md
- NEWS.md
> 4.2.0リリースノート

- samples/syntax-book/Gemfile
> update Gemfile in syntax-book

- lib/review/book/index.rb
どのアイテムがエラーになってるのか不明だったのでinspectするようにしました。
> fix warning message to output more detailed information of item

- lib/review/book/index.rb
> suppress warning with same @<icon>s

- lib/review/configure.rb
- lib/review/epubmaker.rb
- lib/review/idgxmlmaker.rb
- lib/review/pdfmaker.rb
- lib/review/textmaker.rb
- lib/review/webmaker.rb
It's general purpose constructor of `ReVIEW::Configure`.
> add ReVIEW::Configure.create

- lib/review/webmaker.rb
use `cleanup_mathimg` in makerhelper.rb.
> remove unused clean_mathdir

- .github/workflows/ruby-win.yml
EPUBCheckでwarningが出ていたやつを消すものです。
> fix ruby-win.yml

- lib/review/pdfmaker.rb
> values in @locale_latex should be String

- .rubocop.yml
- lib/epubmaker/epubv2.rb
- lib/epubmaker/epubv3.rb
- lib/review/book/base.rb
- lib/review/book/volume.rb
- lib/review/epubmaker.rb
- lib/review/htmlbuilder.rb
- lib/review/init.rb
- lib/review/latexbuilder.rb
- lib/review/logger.rb
- lib/review/plaintextbuilder.rb
- lib/review/rstbuilder.rb
- lib/review/update.rb
- lib/review/webmaker.rb
- review.gemspec
- test/test_logger.rb
- test/test_pdfmaker_cmd.rb
> Fix rubocop

- lib/review/index_builder.rb
> nodisp, notocにおいてもlevel 2未満をスキップ

- lib/review/book/part.rb
#1567 の対応です。
generate_indexesをchapterからコピーしました。
> part.rbでもgenerate_indexesで画像類のインデックスを作成する

- NEWS.ja.md
- NEWS.md
> add note about #1584

- lib/review/lineinput.rb
* extract lookup method
* define invalid character pattern as constant
> refactor: extract lookup_invalid_char()

- lib/review/webtocprinter.rb
テストで失敗しているようなので要求ライブラリをとりこんでみます。
> fix GitAction test error

- test/test_htmlbuilder.rb
どうにもCIでのpygments環境が安定しないですね。
pygments.rbがPython環境をうまく引き込めてない？
> suppress pygments test.

- .github/workflows/ruby-win.yml
- .github/workflows/ruby.yml
https://github.com/ruby/setup-ruby で3.0.0対応したよらしいので試してみます。
> add build test for Ruby 3.0.0

- lib/review/markdownbuilder.rb
- test/test_markdownbuilder.rb
> MARKDOWNBuilder: support @<hd>

- lib/review/compiler.rb
- lib/review/lineinput.rb
- test/test_lineinput.rb
（ほぼ）使われていないメソッドを整理 && 外部から呼ばれないメソッドをprivateにしました。
> Refactor ReVIEW::LineInput

- bin/review
- bin/review-catalog-converter
- bin/review-check
- bin/review-checkdep
- bin/review-compile
- bin/review-epub2html
- bin/review-epubmaker
- bin/review-idgxmlmaker
- bin/review-index
- bin/review-init
- bin/review-pdfmaker
- bin/review-preproc
- bin/review-textmaker
- bin/review-update
- bin/review-validate
- bin/review-vol
- bin/review-webmaker
- lib/review.rb
- lib/review/makerhelper.rb
- test/run_test.rb
- test/test_catalog_converter_cmd.rb
- test/test_epubmaker_cmd.rb
- test/test_helper.rb
- test/test_idgxmlmaker_cmd.rb
- test/test_pdfmaker_cmd.rb
- test/test_template.rb
`$LOAD_PATH` の扱いを整理して、`__dir__`を積極的に使うようにしました。
> Refactor: Simplify path handling

- lib/epubmaker/content.rb
- lib/epubmaker/epubcommon.rb
- lib/epubmaker/epubv2.rb
- lib/epubmaker/epubv3.rb
- templates/html/_colophon.html.erb
- templates/html/_colophon_history.html.erb
- templates/html/_cover.html.erb
- templates/html/_titlepage.html.erb
- templates/opf/opf_manifest_epubv2.opf.erb
- templates/opf/opf_manifest_epubv3.opf.erb
- templates/opf/opf_metainfo_epubv2.opf.erb
- templates/opf/opf_metainfo_epubv3.opf.erb
- templates/opf/opf_tocx_epubv2.opf.erb
- templates/opf/opf_tocx_epubv3.opf.erb
#1640 の続きで、RubyのコードからHTML/XMLを組み立てているところをテンプレート化したものです。
Ruby側ではテンプレートで使うArray/Hashを用意して、タグはテンプレート側でのみ使うようにしています。
> use more templates

- .github/workflows/ruby-tex.yml
GitHub ActionsでTeXLive込みのテストを実行させるものです。
> GitHub Actions: add TeXLive tests on Ubuntu 20.04

- lib/review/makerhelper.rb
> MakerHelper: remove unused method

- lib/review/builder.rb
bindのタイミングで`@img_math`がない場合は初期化するようにします（`review-compile`でエラーが出た）
> fix initialize ImgMath

- lib/review/epubmaker.rb
- lib/review/epubmaker/reviewheaderlistener.rb
- test/assets/header_listener.html
- test/test_reviewheaderlistener.rb
> Extract EPUBMaker#parse_headlines to add a test

- lib/review/pdfmaker.rb
> fix to avoid useless Error

- test/test_img_math.rb
#1662 の修正
パラメータにfuzz 10%を付けるようにしてみました。
> use fuzzy comparation

- lib/review/tocprinter.rb
- lib/review/volumeprinter.rb
#1671の修正です
例外を出力する際に.messageを付けるのを忘れていただけでした。
> avoid internal error of review-vol and review-index

- NEWS.ja.md
- NEWS.md
> NEWS 5.1.0

- .github/workflows/ruby-tex.yml
- .github/workflows/ruby-win.yml
- .github/workflows/ruby.yml
> GA: Fix trigger

- .rubocop.yml
- samples/sample-book/src/lib/tasks/review.rake
- samples/sample-book/src/lib/tasks/z01_copy_sty.rake
- samples/syntax-book/lib/tasks/z01_copy_sty.rake
rubocop-rakeが通ってなかったので修正します（だいたい`desc`関連）。
> fix rubocop-rake

- .rubocop.yml
- bin/review-compile
- lib/review/builder.rb
- lib/review/compiler.rb
- lib/review/epubmaker.rb
- lib/review/epubmaker/producer.rb
- lib/review/exception.rb
- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/idgxmlmaker.rb
- lib/review/img_math.rb
- lib/review/index_builder.rb
- lib/review/latexbuilder.rb
- lib/review/loggable.rb
- lib/review/logger.rb
- lib/review/markdownbuilder.rb
- lib/review/pdfmaker.rb
- lib/review/plaintextbuilder.rb
- lib/review/textmaker.rb
- lib/review/tocprinter.rb
- lib/review/topbuilder.rb
- lib/review/webmaker.rb
- test/test_builder.rb
- test/test_epubmaker.rb
- test/test_htmlbuilder.rb
- test/test_idgxmlbuilder.rb
- test/test_latexbuilder.rb
- test/test_latexbuilder_v2.rb
- test/test_plaintextbuilder.rb
- test/test_topbuilder.rb
* add `error!` and `app_error` method
* do not terminate when syntax errors are found
* do not raise errors in IndexBuilder
* handle `location:`
resolves #1674 .
> `warn` and `error` have been completely replaced.

- .rubocop.yml
- lib/review/latexbuilder.rb
> rubocop: enabled Style/IfInsideElse

- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/index_builder.rb
- lib/review/latexbuilder.rb
- lib/review/markdownbuilder.rb
- lib/review/plaintextbuilder.rb
- lib/review/rstbuilder.rb
#1701 に関連して、superをつけておいた方がいいかもです。
> add `super` in builer_inti_file

- bin/review-preproc
- lib/review/preprocessor.rb
- lib/review/preprocessor/directive.rb
- lib/review/preprocessor/line.rb
- lib/review/preprocessor/repository.rb
- test/test_preprocessor.rb
preproc周りを整理しました。
* ファイルを分割
* Logを他とあわせてinclude Loggableに変更
* テストを追加
> refactor: extract preprocessor

- lib/review/htmlbuilder.rb
- test/test_htmlbuilder.rb
PandocやVFMに合わせて、class属性にlevelを入れる修正です。
必要性はよく分からんなあ…というところですが、子要素のheadlineを見るようなCSSを書くよりは現実的かもしれません。
> section: add level in class

- lib/review/htmlbuilder.rb
こちらはリファクタリングのみです。
* `@section_level`は使ってなさそうなので削除
* `@use_section`を代入しているところの簡略化
* インスタンス変数を直接参照するのではなく`use_section?`を追加してこちらで参照するように変更
* `open_section(level)`と`close_sections`は必要なければ呼び出さないよう修正
*  `close_sections`は`open_section`と同様に`print`で出力するよう修正（対称性を重視）
> Refactor `<section>`

- doc/config.yml.sample
`use_section` パラメータをconfig.yml.sampleに追加します。
> add description about use_section parameter

- NEWS.ja.md
- NEWS.md
> NEWS 5.2.0

- lib/review/catalog.rb
> Fix undefined constant `Date`

- README.md
discussionsページへのリンクをREADME.mdに入れておきます。
> note about discussion site

- lib/review/htmlbuilder.rb
- lib/review/idgxmlbuilder.rb
- lib/review/topbuilder.rb
> approve rubocop 1.25.1's suggestion about Lint/ElseLayout

- NEWS.ja.md
- NEWS.md
> 5.4.0リリースノート

- lib/review/version.rb
> set version 5.4.0

- test/test_img_math.rb
手元でテストが通らない環境があったので、テストの方を変更しておきます。
> Skip tests without pdftocairo

- review.gemspec
rexmlは標準配布物のままではありますがbundled gemになったので、gemspecに追加しておきます。
> load rexml as gem

- NEWS.ja.md
- NEWS.md
- lib/review/version.rb
> Bump up v5.6.0

- .github/workflows/ruby-tex.yml
- .github/workflows/ruby-win.yml
- .github/workflows/ruby.yml
Ruby 3.2のActionも来ているようなのでテストに入れてみます。
> test Ruby 3.2

- NEWS.ja.md
- NEWS.md
> NEWS 5.7.0

- .github/workflows/ruby-tex.yml
- lib/review/configure.rb
- lib/review/img_graph.rb
- review.gemspec
- test/test_img_graph.rb
- test/test_latexbuilder.rb
- test/test_latexbuilder_v2.rb
playwright-runner側で外部依存を少し減らしたので、実際にビルドするビルドテストを追加してみます。
> add test for imggraph build

- doc/config.yml.sample
- doc/format.ja.md
- doc/format.md
mermaid graphの設定方法をformatドキュメントに追加します。
> Mermaidの設定方法を追加

- doc/config.yml.sample
- doc/format.ja.md
- doc/format.md
`playwright:`じゃなくて`playwright_options:`にしたのだった
> use playwright_options

- templates/latex/review-jlreq/review-jlreq.cls
- templates/latex/review-jsbook/review-jsbook.cls
> supported: better line breaks for long urls

- NEWS.ja.md
- NEWS.md
> [WIP] NEWS 5.8.0

- NEWS.ja.md
- NEWS.md
- lib/review/version.rb
> 5.10.0リリース準備
